-- Migration: 20260215_audit_event_types
-- Description: Add missing AuditEventType enum values for auth and admin events
-- Author: Claude
-- Date: 2026-02-15

-- Auth event types (passkeys, OAuth)
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'OAUTH_LOGIN';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PASSKEY_LOGIN';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PASSKEY_REGISTERED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PASSKEY_DELETED';

-- Admin event types (billing, vendor, user management, compliance)
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'STRIPE_REFUND';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ACCOUNTING_EXPORT';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'USER_UPDATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'USER_IMPERSONATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'USER_CREATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'USER_SUSPEND';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'USER_UNSUSPEND';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'USER_DATA_EXPORT';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'USER_DATA_DELETE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CACHE_INVALIDATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ALERT_DISMISS';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'IAP_DOWNGRADE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'VENDOR_CREATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'VENDOR_UPDATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'VENDOR_DELETE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'VENDOR_CONTRACT_UPDATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DISPUTE_EVIDENCE_SUBMIT';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DISPUTE_AUTO_EVIDENCE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'MARKET_DATA_IMPORT';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'WAITLIST_INVITE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'WAITLIST_STATUS_UPDATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'WAITLIST_DELETE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CONTACT_UPDATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CONTACT_DELETE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'WHITELIST_CREATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'WHITELIST_UPDATE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'WHITELIST_DELETE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'WHITELIST_TOGGLE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_CHANGE_PLAN';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_CANCEL';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CREDIT_APPLY';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CRON_TOGGLE';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CRON_TRIGGER';

-- AdminAction enum extensions for admin_audit_log
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'STRIPE_REFUND';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'ACCOUNTING_EXPORT';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'IAP_DOWNGRADE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'VENDOR_CREATE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'VENDOR_UPDATE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'VENDOR_DELETE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'VENDOR_CONTRACT_UPDATE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'DISPUTE_EVIDENCE_SUBMIT';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'DISPUTE_AUTO_EVIDENCE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'MARKET_DATA_IMPORT';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'WAITLIST_INVITE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'WAITLIST_STATUS_UPDATE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'WAITLIST_DELETE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CONTACT_UPDATE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CONTACT_DELETE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'WHITELIST_CREATE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_CHANGE_PLAN';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CREDIT_APPLY';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CRON_TOGGLE';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CRON_TRIGGER';
