-- Migration: 20260303_pipeline_om_validation
-- Description: Adds OM validation workflow columns to pipeline_properties
-- ADR-106: OM Validation Workflow
-- Author: Claude
-- Date: 2026-03-03

ALTER TABLE pipeline_properties
    ADD COLUMN IF NOT EXISTS om_validation_status TEXT NOT NULL DEFAULT 'not_uploaded',
    -- 'not_uploaded' | 'incomplete' | 'validated'
    ADD COLUMN IF NOT EXISTS om_questions         JSONB,
    -- OMQuestion[] — generated by Claude, answered by user
    ADD COLUMN IF NOT EXISTS om_validated_data    JSONB;
    -- Final merged data (raw om_data + user-supplied answers + corrections)
