// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountActiveAlertsBySeverity = `-- name: CountActiveAlertsBySeverity :many
SELECT severity, COUNT(*) as count
FROM system_alerts
WHERE dismissed = false AND ("expiresAt" IS NULL OR "expiresAt" > NOW())
GROUP BY severity
`

type CountActiveAlertsBySeverityRow struct {
	Severity string `json:"severity"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountActiveAlertsBySeverity(ctx context.Context) ([]CountActiveAlertsBySeverityRow, error) {
	rows, err := q.db.Query(ctx, CountActiveAlertsBySeverity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveAlertsBySeverityRow{}
	for rows.Next() {
		var i CountActiveAlertsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const CountAdminAuditLogs = `-- name: CountAdminAuditLogs :one
SELECT COUNT(*) FROM admin_audit_log
WHERE ($1::text IS NULL OR "actorType"::text = $1)
  AND ($2::text IS NULL OR action::text = $2)
  AND ($3::text IS NULL OR resource = $3)
  AND ($4::text IS NULL OR "adminId" = $4)
`

type CountAdminAuditLogsParams struct {
	ActorType      pgtype.Text `json:"actor_type"`
	ActionFilter   pgtype.Text `json:"action_filter"`
	ResourceFilter pgtype.Text `json:"resource_filter"`
	AdminID        pgtype.Text `json:"admin_id"`
}

func (q *Queries) CountAdminAuditLogs(ctx context.Context, arg CountAdminAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountAdminAuditLogs,
		arg.ActorType,
		arg.ActionFilter,
		arg.ResourceFilter,
		arg.AdminID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountAuditLogsByEventType = `-- name: CountAuditLogsByEventType :many
SELECT event::text, COUNT(*) as count
FROM audit_logs
WHERE "createdAt" >= $1 AND "createdAt" <= $2
GROUP BY event::text
ORDER BY count DESC
`

type CountAuditLogsByEventTypeParams struct {
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	CreatedAt_2 pgtype.Timestamp `json:"createdAt_2"`
}

type CountAuditLogsByEventTypeRow struct {
	Event string `json:"event"`
	Count int64  `json:"count"`
}

func (q *Queries) CountAuditLogsByEventType(ctx context.Context, arg CountAuditLogsByEventTypeParams) ([]CountAuditLogsByEventTypeRow, error) {
	rows, err := q.db.Query(ctx, CountAuditLogsByEventType, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditLogsByEventTypeRow{}
	for rows.Next() {
		var i CountAuditLogsByEventTypeRow
		if err := rows.Scan(&i.Event, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const CreateAdminAuditLog = `-- name: CreateAdminAuditLog :exec

INSERT INTO admin_audit_log (
    id, "adminId", "adminEmail", "actorType", action, resource, "resourceId",
    details, "ipAddress", "userAgent", "createdAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW()
)
`

type CreateAdminAuditLogParams struct {
	ID         string          `json:"id"`
	AdminId    string          `json:"adminId"`
	AdminEmail string          `json:"adminEmail"`
	ActorType  interface{}     `json:"actorType"`
	Action     interface{}     `json:"action"`
	Resource   string          `json:"resource"`
	ResourceId pgtype.Text     `json:"resourceId"`
	Details    json.RawMessage `json:"details"`
	IpAddress  string          `json:"ipAddress"`
	UserAgent  string          `json:"userAgent"`
}

// Admin Audit Log Queries
func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) error {
	_, err := q.db.Exec(ctx, CreateAdminAuditLog,
		arg.ID,
		arg.AdminId,
		arg.AdminEmail,
		arg.ActorType,
		arg.Action,
		arg.Resource,
		arg.ResourceId,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const CreateAdminSession = `-- name: CreateAdminSession :one

INSERT INTO admin_sessions (
    id, "userId", "tokenHash", "ipAddress", "userAgent",
    "deviceName", location, "createdAt", "lastActive", "expiresAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW(), $8
) RETURNING id, "userId", "tokenHash", "ipAddress", "userAgent", "deviceName", location, "createdAt", "lastActive", "expiresAt", "revokedAt"
`

type CreateAdminSessionParams struct {
	ID         string           `json:"id"`
	UserId     string           `json:"userId"`
	TokenHash  string           `json:"tokenHash"`
	IpAddress  string           `json:"ipAddress"`
	UserAgent  string           `json:"userAgent"`
	DeviceName pgtype.Text      `json:"deviceName"`
	Location   pgtype.Text      `json:"location"`
	ExpiresAt  pgtype.Timestamp `json:"expiresAt"`
}

// Admin Session Queries
func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, CreateAdminSession,
		arg.ID,
		arg.UserId,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceName,
		arg.Location,
		arg.ExpiresAt,
	)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceName,
		&i.Location,
		&i.CreatedAt,
		&i.LastActive,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const CreateAdminTwoFactor = `-- name: CreateAdminTwoFactor :one
INSERT INTO admin_two_factor (
    id, "userId", secret, enabled, "backupCodes", "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, false, $4, NOW(), NOW()
) RETURNING id, "userId", secret, enabled, "backupCodes", "createdAt", "updatedAt"
`

type CreateAdminTwoFactorParams struct {
	ID          string   `json:"id"`
	UserId      string   `json:"userId"`
	Secret      string   `json:"secret"`
	BackupCodes []string `json:"backupCodes"`
}

func (q *Queries) CreateAdminTwoFactor(ctx context.Context, arg CreateAdminTwoFactorParams) (AdminTwoFactor, error) {
	row := q.db.QueryRow(ctx, CreateAdminTwoFactor,
		arg.ID,
		arg.UserId,
		arg.Secret,
		arg.BackupCodes,
	)
	var i AdminTwoFactor
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Secret,
		&i.Enabled,
		&i.BackupCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateAuditLog = `-- name: CreateAuditLog :exec


INSERT INTO audit_logs (
    id, "createdAt", "userId", event, description, "ipAddress", "userAgent",
    metadata, success, error, action, "complianceFlags", endpoint,
    "performanceMetrics", "requestId", resource, "securityContext", "sessionId", severity
) VALUES (
    $1, NOW(), $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
`

type CreateAuditLogParams struct {
	ID                 string      `json:"id"`
	UserId             pgtype.Text `json:"userId"`
	Event              interface{} `json:"event"`
	Description        pgtype.Text `json:"description"`
	IpAddress          pgtype.Text `json:"ipAddress"`
	UserAgent          pgtype.Text `json:"userAgent"`
	Metadata           []byte      `json:"metadata"`
	Success            bool        `json:"success"`
	Error              pgtype.Text `json:"error"`
	Action             pgtype.Text `json:"action"`
	ComplianceFlags    []byte      `json:"complianceFlags"`
	Endpoint           pgtype.Text `json:"endpoint"`
	PerformanceMetrics []byte      `json:"performanceMetrics"`
	RequestId          pgtype.Text `json:"requestId"`
	Resource           pgtype.Text `json:"resource"`
	SecurityContext    []byte      `json:"securityContext"`
	SessionId          pgtype.Text `json:"sessionId"`
	Severity           string      `json:"severity"`
}

// Admin and Audit Queries
// Audit Log Queries
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, CreateAuditLog,
		arg.ID,
		arg.UserId,
		arg.Event,
		arg.Description,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
		arg.Success,
		arg.Error,
		arg.Action,
		arg.ComplianceFlags,
		arg.Endpoint,
		arg.PerformanceMetrics,
		arg.RequestId,
		arg.Resource,
		arg.SecurityContext,
		arg.SessionId,
		arg.Severity,
	)
	return err
}

const CreateSystemAlert = `-- name: CreateSystemAlert :one
INSERT INTO system_alerts (
    id, type, severity, title, description, "alertKey", metadata,
    "firstSeen", "lastSeen", "occurrenceCount", dismissed, "actionRequired",
    "expiresAt", "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8, 1, false, $9, $10, NOW(), NOW()
) RETURNING id, type, severity, title, description, "alertKey", metadata, "firstSeen", "lastSeen", "occurrenceCount", dismissed, "actionRequired", "expiresAt", "createdAt", "updatedAt"
`

type CreateSystemAlertParams struct {
	ID             string           `json:"id"`
	Type           string           `json:"type"`
	Severity       string           `json:"severity"`
	Title          string           `json:"title"`
	Description    string           `json:"description"`
	AlertKey       string           `json:"alertKey"`
	Metadata       string           `json:"metadata"`
	FirstSeen      pgtype.Timestamp `json:"firstSeen"`
	ActionRequired bool             `json:"actionRequired"`
	ExpiresAt      pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) CreateSystemAlert(ctx context.Context, arg CreateSystemAlertParams) (SystemAlert, error) {
	row := q.db.QueryRow(ctx, CreateSystemAlert,
		arg.ID,
		arg.Type,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.AlertKey,
		arg.Metadata,
		arg.FirstSeen,
		arg.ActionRequired,
		arg.ExpiresAt,
	)
	var i SystemAlert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.AlertKey,
		&i.Metadata,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.Dismissed,
		&i.ActionRequired,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteAdminTwoFactor = `-- name: DeleteAdminTwoFactor :exec
DELETE FROM admin_two_factor WHERE "userId" = $1
`

func (q *Queries) DeleteAdminTwoFactor(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, DeleteAdminTwoFactor, userid)
	return err
}

const DeleteAuditLogsOlderThan = `-- name: DeleteAuditLogsOlderThan :exec
DELETE FROM audit_logs WHERE "createdAt" < $1
`

func (q *Queries) DeleteAuditLogsOlderThan(ctx context.Context, createdat pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, DeleteAuditLogsOlderThan, createdat)
	return err
}

const DeleteExpiredAdminSessions = `-- name: DeleteExpiredAdminSessions :exec
DELETE FROM admin_sessions WHERE "expiresAt" < NOW()
`

func (q *Queries) DeleteExpiredAdminSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, DeleteExpiredAdminSessions)
	return err
}

const DeleteExpiredSystemAlerts = `-- name: DeleteExpiredSystemAlerts :exec
DELETE FROM system_alerts WHERE "expiresAt" IS NOT NULL AND "expiresAt" < NOW()
`

func (q *Queries) DeleteExpiredSystemAlerts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, DeleteExpiredSystemAlerts)
	return err
}

const DisableAdminTwoFactor = `-- name: DisableAdminTwoFactor :exec
UPDATE admin_two_factor SET
    enabled = false,
    "updatedAt" = NOW()
WHERE "userId" = $1
`

func (q *Queries) DisableAdminTwoFactor(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, DisableAdminTwoFactor, userid)
	return err
}

const DismissSystemAlert = `-- name: DismissSystemAlert :exec
UPDATE system_alerts SET
    dismissed = true,
    "updatedAt" = NOW()
WHERE id = $1
`

func (q *Queries) DismissSystemAlert(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DismissSystemAlert, id)
	return err
}

const DismissSystemAlertByKey = `-- name: DismissSystemAlertByKey :exec
UPDATE system_alerts SET
    dismissed = true,
    "updatedAt" = NOW()
WHERE "alertKey" = $1
`

func (q *Queries) DismissSystemAlertByKey(ctx context.Context, alertkey string) error {
	_, err := q.db.Exec(ctx, DismissSystemAlertByKey, alertkey)
	return err
}

const EnableAdminTwoFactor = `-- name: EnableAdminTwoFactor :exec
UPDATE admin_two_factor SET
    enabled = true,
    "updatedAt" = NOW()
WHERE "userId" = $1
`

func (q *Queries) EnableAdminTwoFactor(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, EnableAdminTwoFactor, userid)
	return err
}

const GetAdminAuditLogByID = `-- name: GetAdminAuditLogByID :one
SELECT id, "adminId", "adminEmail", "actorType"::text, action::text, resource, "resourceId",
    details, "ipAddress", "userAgent", "createdAt"
FROM admin_audit_log WHERE id = $1
`

type GetAdminAuditLogByIDRow struct {
	ID         string           `json:"id"`
	AdminId    string           `json:"adminId"`
	AdminEmail string           `json:"adminEmail"`
	ActorType  string           `json:"actorType"`
	Action     string           `json:"action"`
	Resource   string           `json:"resource"`
	ResourceId pgtype.Text      `json:"resourceId"`
	Details    json.RawMessage  `json:"details"`
	IpAddress  string           `json:"ipAddress"`
	UserAgent  string           `json:"userAgent"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) GetAdminAuditLogByID(ctx context.Context, id string) (GetAdminAuditLogByIDRow, error) {
	row := q.db.QueryRow(ctx, GetAdminAuditLogByID, id)
	var i GetAdminAuditLogByIDRow
	err := row.Scan(
		&i.ID,
		&i.AdminId,
		&i.AdminEmail,
		&i.ActorType,
		&i.Action,
		&i.Resource,
		&i.ResourceId,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const GetAdminSessionByID = `-- name: GetAdminSessionByID :one
SELECT id, "userId", "tokenHash", "ipAddress", "userAgent", "deviceName", location, "createdAt", "lastActive", "expiresAt", "revokedAt" FROM admin_sessions
WHERE id = $1 AND "revokedAt" IS NULL AND "expiresAt" > NOW()
`

func (q *Queries) GetAdminSessionByID(ctx context.Context, id string) (AdminSession, error) {
	row := q.db.QueryRow(ctx, GetAdminSessionByID, id)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceName,
		&i.Location,
		&i.CreatedAt,
		&i.LastActive,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const GetAdminSessionByTokenHash = `-- name: GetAdminSessionByTokenHash :one
SELECT id, "userId", "tokenHash", "ipAddress", "userAgent", "deviceName", location, "createdAt", "lastActive", "expiresAt", "revokedAt" FROM admin_sessions
WHERE "tokenHash" = $1 AND "revokedAt" IS NULL AND "expiresAt" > NOW()
`

func (q *Queries) GetAdminSessionByTokenHash(ctx context.Context, tokenhash string) (AdminSession, error) {
	row := q.db.QueryRow(ctx, GetAdminSessionByTokenHash, tokenhash)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceName,
		&i.Location,
		&i.CreatedAt,
		&i.LastActive,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const GetAdminTwoFactorByUserID = `-- name: GetAdminTwoFactorByUserID :one

SELECT id, "userId", secret, enabled, "backupCodes", "createdAt", "updatedAt" FROM admin_two_factor WHERE "userId" = $1
`

// Admin Two-Factor Queries
func (q *Queries) GetAdminTwoFactorByUserID(ctx context.Context, userid string) (AdminTwoFactor, error) {
	row := q.db.QueryRow(ctx, GetAdminTwoFactorByUserID, userid)
	var i AdminTwoFactor
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Secret,
		&i.Enabled,
		&i.BackupCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, "createdAt", "userId", event::text, description, "ipAddress", "userAgent",
    metadata, success, error, action, "complianceFlags", endpoint,
    "performanceMetrics", "requestId", resource, "securityContext", "sessionId", severity
FROM audit_logs WHERE id = $1
`

type GetAuditLogByIDRow struct {
	ID                 string           `json:"id"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UserId             pgtype.Text      `json:"userId"`
	Event              string           `json:"event"`
	Description        pgtype.Text      `json:"description"`
	IpAddress          pgtype.Text      `json:"ipAddress"`
	UserAgent          pgtype.Text      `json:"userAgent"`
	Metadata           []byte           `json:"metadata"`
	Success            bool             `json:"success"`
	Error              pgtype.Text      `json:"error"`
	Action             pgtype.Text      `json:"action"`
	ComplianceFlags    []byte           `json:"complianceFlags"`
	Endpoint           pgtype.Text      `json:"endpoint"`
	PerformanceMetrics []byte           `json:"performanceMetrics"`
	RequestId          pgtype.Text      `json:"requestId"`
	Resource           pgtype.Text      `json:"resource"`
	SecurityContext    []byte           `json:"securityContext"`
	SessionId          pgtype.Text      `json:"sessionId"`
	Severity           string           `json:"severity"`
}

func (q *Queries) GetAuditLogByID(ctx context.Context, id string) (GetAuditLogByIDRow, error) {
	row := q.db.QueryRow(ctx, GetAuditLogByID, id)
	var i GetAuditLogByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserId,
		&i.Event,
		&i.Description,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.Success,
		&i.Error,
		&i.Action,
		&i.ComplianceFlags,
		&i.Endpoint,
		&i.PerformanceMetrics,
		&i.RequestId,
		&i.Resource,
		&i.SecurityContext,
		&i.SessionId,
		&i.Severity,
	)
	return i, err
}

const GetSystemAlertByID = `-- name: GetSystemAlertByID :one

SELECT id, type, severity, title, description, "alertKey", metadata, "firstSeen", "lastSeen", "occurrenceCount", dismissed, "actionRequired", "expiresAt", "createdAt", "updatedAt" FROM system_alerts WHERE id = $1
`

// System Alerts Queries
func (q *Queries) GetSystemAlertByID(ctx context.Context, id string) (SystemAlert, error) {
	row := q.db.QueryRow(ctx, GetSystemAlertByID, id)
	var i SystemAlert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.AlertKey,
		&i.Metadata,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.Dismissed,
		&i.ActionRequired,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetSystemAlertByKey = `-- name: GetSystemAlertByKey :one
SELECT id, type, severity, title, description, "alertKey", metadata, "firstSeen", "lastSeen", "occurrenceCount", dismissed, "actionRequired", "expiresAt", "createdAt", "updatedAt" FROM system_alerts WHERE "alertKey" = $1
`

func (q *Queries) GetSystemAlertByKey(ctx context.Context, alertkey string) (SystemAlert, error) {
	row := q.db.QueryRow(ctx, GetSystemAlertByKey, alertkey)
	var i SystemAlert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.AlertKey,
		&i.Metadata,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.Dismissed,
		&i.ActionRequired,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListActiveAdminSessions = `-- name: ListActiveAdminSessions :many
SELECT id, "userId", "tokenHash", "ipAddress", "userAgent", "deviceName", location, "createdAt", "lastActive", "expiresAt", "revokedAt" FROM admin_sessions
WHERE "revokedAt" IS NULL AND "expiresAt" > NOW()
ORDER BY "lastActive" DESC
`

func (q *Queries) ListActiveAdminSessions(ctx context.Context) ([]AdminSession, error) {
	rows, err := q.db.Query(ctx, ListActiveAdminSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminSession{}
	for rows.Next() {
		var i AdminSession
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.TokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.DeviceName,
			&i.Location,
			&i.CreatedAt,
			&i.LastActive,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListActiveSystemAlerts = `-- name: ListActiveSystemAlerts :many
SELECT id, type, severity, title, description, "alertKey", metadata, "firstSeen", "lastSeen", "occurrenceCount", dismissed, "actionRequired", "expiresAt", "createdAt", "updatedAt" FROM system_alerts
WHERE dismissed = false AND ("expiresAt" IS NULL OR "expiresAt" > NOW())
ORDER BY
    CASE severity
        WHEN 'critical' THEN 1
        WHEN 'error' THEN 2
        WHEN 'warning' THEN 3
        ELSE 4
    END,
    "lastSeen" DESC
LIMIT $1 OFFSET $2
`

type ListActiveSystemAlertsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveSystemAlerts(ctx context.Context, arg ListActiveSystemAlertsParams) ([]SystemAlert, error) {
	rows, err := q.db.Query(ctx, ListActiveSystemAlerts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemAlert{}
	for rows.Next() {
		var i SystemAlert
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.AlertKey,
			&i.Metadata,
			&i.FirstSeen,
			&i.LastSeen,
			&i.OccurrenceCount,
			&i.Dismissed,
			&i.ActionRequired,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAdminAuditLogs = `-- name: ListAdminAuditLogs :many
SELECT id, "adminId", "adminEmail", "actorType"::text, action::text, resource, "resourceId",
    details, "ipAddress", "userAgent", "createdAt"
FROM admin_audit_log
WHERE ($1::text IS NULL OR "actorType"::text = $1)
  AND ($2::text IS NULL OR action::text = $2)
  AND ($3::text IS NULL OR resource = $3)
  AND ($4::text IS NULL OR "adminId" = $4)
ORDER BY "createdAt" DESC
LIMIT $6 OFFSET $5
`

type ListAdminAuditLogsParams struct {
	ActorType      pgtype.Text `json:"actor_type"`
	ActionFilter   pgtype.Text `json:"action_filter"`
	ResourceFilter pgtype.Text `json:"resource_filter"`
	AdminID        pgtype.Text `json:"admin_id"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
}

type ListAdminAuditLogsRow struct {
	ID         string           `json:"id"`
	AdminId    string           `json:"adminId"`
	AdminEmail string           `json:"adminEmail"`
	ActorType  string           `json:"actorType"`
	Action     string           `json:"action"`
	Resource   string           `json:"resource"`
	ResourceId pgtype.Text      `json:"resourceId"`
	Details    json.RawMessage  `json:"details"`
	IpAddress  string           `json:"ipAddress"`
	UserAgent  string           `json:"userAgent"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) ListAdminAuditLogs(ctx context.Context, arg ListAdminAuditLogsParams) ([]ListAdminAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, ListAdminAuditLogs,
		arg.ActorType,
		arg.ActionFilter,
		arg.ResourceFilter,
		arg.AdminID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAuditLogsRow{}
	for rows.Next() {
		var i ListAdminAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminId,
			&i.AdminEmail,
			&i.ActorType,
			&i.Action,
			&i.Resource,
			&i.ResourceId,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAdminAuditLogsByAction = `-- name: ListAdminAuditLogsByAction :many
SELECT id, "adminId", "adminEmail", "actorType"::text, action::text, resource, "resourceId",
    details, "ipAddress", "userAgent", "createdAt"
FROM admin_audit_log
WHERE action::text = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListAdminAuditLogsByActionParams struct {
	Action interface{} `json:"action"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListAdminAuditLogsByActionRow struct {
	ID         string           `json:"id"`
	AdminId    string           `json:"adminId"`
	AdminEmail string           `json:"adminEmail"`
	ActorType  string           `json:"actorType"`
	Action     string           `json:"action"`
	Resource   string           `json:"resource"`
	ResourceId pgtype.Text      `json:"resourceId"`
	Details    json.RawMessage  `json:"details"`
	IpAddress  string           `json:"ipAddress"`
	UserAgent  string           `json:"userAgent"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) ListAdminAuditLogsByAction(ctx context.Context, arg ListAdminAuditLogsByActionParams) ([]ListAdminAuditLogsByActionRow, error) {
	rows, err := q.db.Query(ctx, ListAdminAuditLogsByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAuditLogsByActionRow{}
	for rows.Next() {
		var i ListAdminAuditLogsByActionRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminId,
			&i.AdminEmail,
			&i.ActorType,
			&i.Action,
			&i.Resource,
			&i.ResourceId,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAdminAuditLogsByAdmin = `-- name: ListAdminAuditLogsByAdmin :many
SELECT id, "adminId", "adminEmail", "actorType"::text, action::text, resource, "resourceId",
    details, "ipAddress", "userAgent", "createdAt"
FROM admin_audit_log
WHERE "adminId" = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListAdminAuditLogsByAdminParams struct {
	AdminId string `json:"adminId"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListAdminAuditLogsByAdminRow struct {
	ID         string           `json:"id"`
	AdminId    string           `json:"adminId"`
	AdminEmail string           `json:"adminEmail"`
	ActorType  string           `json:"actorType"`
	Action     string           `json:"action"`
	Resource   string           `json:"resource"`
	ResourceId pgtype.Text      `json:"resourceId"`
	Details    json.RawMessage  `json:"details"`
	IpAddress  string           `json:"ipAddress"`
	UserAgent  string           `json:"userAgent"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) ListAdminAuditLogsByAdmin(ctx context.Context, arg ListAdminAuditLogsByAdminParams) ([]ListAdminAuditLogsByAdminRow, error) {
	rows, err := q.db.Query(ctx, ListAdminAuditLogsByAdmin, arg.AdminId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAuditLogsByAdminRow{}
	for rows.Next() {
		var i ListAdminAuditLogsByAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminId,
			&i.AdminEmail,
			&i.ActorType,
			&i.Action,
			&i.Resource,
			&i.ResourceId,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAdminAuditLogsByDateRange = `-- name: ListAdminAuditLogsByDateRange :many
SELECT id, "adminId", "adminEmail", "actorType"::text, action::text, resource, "resourceId",
    details, "ipAddress", "userAgent", "createdAt"
FROM admin_audit_log
WHERE "createdAt" >= $1 AND "createdAt" <= $2
ORDER BY "createdAt" DESC
LIMIT $3 OFFSET $4
`

type ListAdminAuditLogsByDateRangeParams struct {
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	CreatedAt_2 pgtype.Timestamp `json:"createdAt_2"`
	Limit       int32            `json:"limit"`
	Offset      int32            `json:"offset"`
}

type ListAdminAuditLogsByDateRangeRow struct {
	ID         string           `json:"id"`
	AdminId    string           `json:"adminId"`
	AdminEmail string           `json:"adminEmail"`
	ActorType  string           `json:"actorType"`
	Action     string           `json:"action"`
	Resource   string           `json:"resource"`
	ResourceId pgtype.Text      `json:"resourceId"`
	Details    json.RawMessage  `json:"details"`
	IpAddress  string           `json:"ipAddress"`
	UserAgent  string           `json:"userAgent"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) ListAdminAuditLogsByDateRange(ctx context.Context, arg ListAdminAuditLogsByDateRangeParams) ([]ListAdminAuditLogsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, ListAdminAuditLogsByDateRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAuditLogsByDateRangeRow{}
	for rows.Next() {
		var i ListAdminAuditLogsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminId,
			&i.AdminEmail,
			&i.ActorType,
			&i.Action,
			&i.Resource,
			&i.ResourceId,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAdminAuditLogsByResource = `-- name: ListAdminAuditLogsByResource :many
SELECT id, "adminId", "adminEmail", "actorType"::text, action::text, resource, "resourceId",
    details, "ipAddress", "userAgent", "createdAt"
FROM admin_audit_log
WHERE resource = $1 AND ("resourceId" = $2 OR $2 IS NULL)
ORDER BY "createdAt" DESC
LIMIT $3 OFFSET $4
`

type ListAdminAuditLogsByResourceParams struct {
	Resource   string      `json:"resource"`
	ResourceId pgtype.Text `json:"resourceId"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListAdminAuditLogsByResourceRow struct {
	ID         string           `json:"id"`
	AdminId    string           `json:"adminId"`
	AdminEmail string           `json:"adminEmail"`
	ActorType  string           `json:"actorType"`
	Action     string           `json:"action"`
	Resource   string           `json:"resource"`
	ResourceId pgtype.Text      `json:"resourceId"`
	Details    json.RawMessage  `json:"details"`
	IpAddress  string           `json:"ipAddress"`
	UserAgent  string           `json:"userAgent"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) ListAdminAuditLogsByResource(ctx context.Context, arg ListAdminAuditLogsByResourceParams) ([]ListAdminAuditLogsByResourceRow, error) {
	rows, err := q.db.Query(ctx, ListAdminAuditLogsByResource,
		arg.Resource,
		arg.ResourceId,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAuditLogsByResourceRow{}
	for rows.Next() {
		var i ListAdminAuditLogsByResourceRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminId,
			&i.AdminEmail,
			&i.ActorType,
			&i.Action,
			&i.Resource,
			&i.ResourceId,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAdminSessionsByUser = `-- name: ListAdminSessionsByUser :many
SELECT id, "userId", "tokenHash", "ipAddress", "userAgent", "deviceName", location, "createdAt", "lastActive", "expiresAt", "revokedAt" FROM admin_sessions
WHERE "userId" = $1 AND "revokedAt" IS NULL
ORDER BY "createdAt" DESC
`

func (q *Queries) ListAdminSessionsByUser(ctx context.Context, userid string) ([]AdminSession, error) {
	rows, err := q.db.Query(ctx, ListAdminSessionsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminSession{}
	for rows.Next() {
		var i AdminSession
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.TokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.DeviceName,
			&i.Location,
			&i.CreatedAt,
			&i.LastActive,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAuditLogs = `-- name: ListAuditLogs :many
SELECT id, "createdAt", "userId", event::text, description, "ipAddress", "userAgent",
    metadata, success, error, action, "complianceFlags", endpoint,
    "performanceMetrics", "requestId", resource, "securityContext", "sessionId", severity
FROM audit_logs
ORDER BY "createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAuditLogsRow struct {
	ID                 string           `json:"id"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UserId             pgtype.Text      `json:"userId"`
	Event              string           `json:"event"`
	Description        pgtype.Text      `json:"description"`
	IpAddress          pgtype.Text      `json:"ipAddress"`
	UserAgent          pgtype.Text      `json:"userAgent"`
	Metadata           []byte           `json:"metadata"`
	Success            bool             `json:"success"`
	Error              pgtype.Text      `json:"error"`
	Action             pgtype.Text      `json:"action"`
	ComplianceFlags    []byte           `json:"complianceFlags"`
	Endpoint           pgtype.Text      `json:"endpoint"`
	PerformanceMetrics []byte           `json:"performanceMetrics"`
	RequestId          pgtype.Text      `json:"requestId"`
	Resource           pgtype.Text      `json:"resource"`
	SecurityContext    []byte           `json:"securityContext"`
	SessionId          pgtype.Text      `json:"sessionId"`
	Severity           string           `json:"severity"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, ListAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserId,
			&i.Event,
			&i.Description,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.Success,
			&i.Error,
			&i.Action,
			&i.ComplianceFlags,
			&i.Endpoint,
			&i.PerformanceMetrics,
			&i.RequestId,
			&i.Resource,
			&i.SecurityContext,
			&i.SessionId,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAuditLogsByDateRange = `-- name: ListAuditLogsByDateRange :many
SELECT id, "createdAt", "userId", event::text, description, "ipAddress", "userAgent",
    metadata, success, error, action, "complianceFlags", endpoint,
    "performanceMetrics", "requestId", resource, "securityContext", "sessionId", severity
FROM audit_logs
WHERE "createdAt" >= $1 AND "createdAt" <= $2
ORDER BY "createdAt" DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogsByDateRangeParams struct {
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	CreatedAt_2 pgtype.Timestamp `json:"createdAt_2"`
	Limit       int32            `json:"limit"`
	Offset      int32            `json:"offset"`
}

type ListAuditLogsByDateRangeRow struct {
	ID                 string           `json:"id"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UserId             pgtype.Text      `json:"userId"`
	Event              string           `json:"event"`
	Description        pgtype.Text      `json:"description"`
	IpAddress          pgtype.Text      `json:"ipAddress"`
	UserAgent          pgtype.Text      `json:"userAgent"`
	Metadata           []byte           `json:"metadata"`
	Success            bool             `json:"success"`
	Error              pgtype.Text      `json:"error"`
	Action             pgtype.Text      `json:"action"`
	ComplianceFlags    []byte           `json:"complianceFlags"`
	Endpoint           pgtype.Text      `json:"endpoint"`
	PerformanceMetrics []byte           `json:"performanceMetrics"`
	RequestId          pgtype.Text      `json:"requestId"`
	Resource           pgtype.Text      `json:"resource"`
	SecurityContext    []byte           `json:"securityContext"`
	SessionId          pgtype.Text      `json:"sessionId"`
	Severity           string           `json:"severity"`
}

func (q *Queries) ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]ListAuditLogsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, ListAuditLogsByDateRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByDateRangeRow{}
	for rows.Next() {
		var i ListAuditLogsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserId,
			&i.Event,
			&i.Description,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.Success,
			&i.Error,
			&i.Action,
			&i.ComplianceFlags,
			&i.Endpoint,
			&i.PerformanceMetrics,
			&i.RequestId,
			&i.Resource,
			&i.SecurityContext,
			&i.SessionId,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAuditLogsByEventType = `-- name: ListAuditLogsByEventType :many
SELECT id, "createdAt", "userId", event::text, description, "ipAddress", "userAgent",
    metadata, success, error, action, "complianceFlags", endpoint,
    "performanceMetrics", "requestId", resource, "securityContext", "sessionId", severity
FROM audit_logs
WHERE event::text = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByEventTypeParams struct {
	Event  interface{} `json:"event"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListAuditLogsByEventTypeRow struct {
	ID                 string           `json:"id"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UserId             pgtype.Text      `json:"userId"`
	Event              string           `json:"event"`
	Description        pgtype.Text      `json:"description"`
	IpAddress          pgtype.Text      `json:"ipAddress"`
	UserAgent          pgtype.Text      `json:"userAgent"`
	Metadata           []byte           `json:"metadata"`
	Success            bool             `json:"success"`
	Error              pgtype.Text      `json:"error"`
	Action             pgtype.Text      `json:"action"`
	ComplianceFlags    []byte           `json:"complianceFlags"`
	Endpoint           pgtype.Text      `json:"endpoint"`
	PerformanceMetrics []byte           `json:"performanceMetrics"`
	RequestId          pgtype.Text      `json:"requestId"`
	Resource           pgtype.Text      `json:"resource"`
	SecurityContext    []byte           `json:"securityContext"`
	SessionId          pgtype.Text      `json:"sessionId"`
	Severity           string           `json:"severity"`
}

func (q *Queries) ListAuditLogsByEventType(ctx context.Context, arg ListAuditLogsByEventTypeParams) ([]ListAuditLogsByEventTypeRow, error) {
	rows, err := q.db.Query(ctx, ListAuditLogsByEventType, arg.Event, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByEventTypeRow{}
	for rows.Next() {
		var i ListAuditLogsByEventTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserId,
			&i.Event,
			&i.Description,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.Success,
			&i.Error,
			&i.Action,
			&i.ComplianceFlags,
			&i.Endpoint,
			&i.PerformanceMetrics,
			&i.RequestId,
			&i.Resource,
			&i.SecurityContext,
			&i.SessionId,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAuditLogsBySeverity = `-- name: ListAuditLogsBySeverity :many
SELECT id, "createdAt", "userId", event::text, description, "ipAddress", "userAgent",
    metadata, success, error, action, "complianceFlags", endpoint,
    "performanceMetrics", "requestId", resource, "securityContext", "sessionId", severity
FROM audit_logs
WHERE severity = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsBySeverityParams struct {
	Severity string `json:"severity"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type ListAuditLogsBySeverityRow struct {
	ID                 string           `json:"id"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UserId             pgtype.Text      `json:"userId"`
	Event              string           `json:"event"`
	Description        pgtype.Text      `json:"description"`
	IpAddress          pgtype.Text      `json:"ipAddress"`
	UserAgent          pgtype.Text      `json:"userAgent"`
	Metadata           []byte           `json:"metadata"`
	Success            bool             `json:"success"`
	Error              pgtype.Text      `json:"error"`
	Action             pgtype.Text      `json:"action"`
	ComplianceFlags    []byte           `json:"complianceFlags"`
	Endpoint           pgtype.Text      `json:"endpoint"`
	PerformanceMetrics []byte           `json:"performanceMetrics"`
	RequestId          pgtype.Text      `json:"requestId"`
	Resource           pgtype.Text      `json:"resource"`
	SecurityContext    []byte           `json:"securityContext"`
	SessionId          pgtype.Text      `json:"sessionId"`
	Severity           string           `json:"severity"`
}

func (q *Queries) ListAuditLogsBySeverity(ctx context.Context, arg ListAuditLogsBySeverityParams) ([]ListAuditLogsBySeverityRow, error) {
	rows, err := q.db.Query(ctx, ListAuditLogsBySeverity, arg.Severity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsBySeverityRow{}
	for rows.Next() {
		var i ListAuditLogsBySeverityRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserId,
			&i.Event,
			&i.Description,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.Success,
			&i.Error,
			&i.Action,
			&i.ComplianceFlags,
			&i.Endpoint,
			&i.PerformanceMetrics,
			&i.RequestId,
			&i.Resource,
			&i.SecurityContext,
			&i.SessionId,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, "createdAt", "userId", event::text, description, "ipAddress", "userAgent",
    metadata, success, error, action, "complianceFlags", endpoint,
    "performanceMetrics", "requestId", resource, "securityContext", "sessionId", severity
FROM audit_logs
WHERE "userId" = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByUserParams struct {
	UserId pgtype.Text `json:"userId"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListAuditLogsByUserRow struct {
	ID                 string           `json:"id"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UserId             pgtype.Text      `json:"userId"`
	Event              string           `json:"event"`
	Description        pgtype.Text      `json:"description"`
	IpAddress          pgtype.Text      `json:"ipAddress"`
	UserAgent          pgtype.Text      `json:"userAgent"`
	Metadata           []byte           `json:"metadata"`
	Success            bool             `json:"success"`
	Error              pgtype.Text      `json:"error"`
	Action             pgtype.Text      `json:"action"`
	ComplianceFlags    []byte           `json:"complianceFlags"`
	Endpoint           pgtype.Text      `json:"endpoint"`
	PerformanceMetrics []byte           `json:"performanceMetrics"`
	RequestId          pgtype.Text      `json:"requestId"`
	Resource           pgtype.Text      `json:"resource"`
	SecurityContext    []byte           `json:"securityContext"`
	SessionId          pgtype.Text      `json:"sessionId"`
	Severity           string           `json:"severity"`
}

func (q *Queries) ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]ListAuditLogsByUserRow, error) {
	rows, err := q.db.Query(ctx, ListAuditLogsByUser, arg.UserId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByUserRow{}
	for rows.Next() {
		var i ListAuditLogsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserId,
			&i.Event,
			&i.Description,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.Success,
			&i.Error,
			&i.Action,
			&i.ComplianceFlags,
			&i.Endpoint,
			&i.PerformanceMetrics,
			&i.RequestId,
			&i.Resource,
			&i.SecurityContext,
			&i.SessionId,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSystemAlertsBySeverity = `-- name: ListSystemAlertsBySeverity :many
SELECT id, type, severity, title, description, "alertKey", metadata, "firstSeen", "lastSeen", "occurrenceCount", dismissed, "actionRequired", "expiresAt", "createdAt", "updatedAt" FROM system_alerts
WHERE severity = $1 AND dismissed = false
ORDER BY "lastSeen" DESC
LIMIT $2 OFFSET $3
`

type ListSystemAlertsBySeverityParams struct {
	Severity string `json:"severity"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListSystemAlertsBySeverity(ctx context.Context, arg ListSystemAlertsBySeverityParams) ([]SystemAlert, error) {
	rows, err := q.db.Query(ctx, ListSystemAlertsBySeverity, arg.Severity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemAlert{}
	for rows.Next() {
		var i SystemAlert
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.AlertKey,
			&i.Metadata,
			&i.FirstSeen,
			&i.LastSeen,
			&i.OccurrenceCount,
			&i.Dismissed,
			&i.ActionRequired,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSystemAlertsRequiringAction = `-- name: ListSystemAlertsRequiringAction :many
SELECT id, type, severity, title, description, "alertKey", metadata, "firstSeen", "lastSeen", "occurrenceCount", dismissed, "actionRequired", "expiresAt", "createdAt", "updatedAt" FROM system_alerts
WHERE "actionRequired" = true AND dismissed = false
ORDER BY "lastSeen" DESC
`

func (q *Queries) ListSystemAlertsRequiringAction(ctx context.Context) ([]SystemAlert, error) {
	rows, err := q.db.Query(ctx, ListSystemAlertsRequiringAction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemAlert{}
	for rows.Next() {
		var i SystemAlert
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.AlertKey,
			&i.Metadata,
			&i.FirstSeen,
			&i.LastSeen,
			&i.OccurrenceCount,
			&i.Dismissed,
			&i.ActionRequired,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RevokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE admin_sessions SET "revokedAt" = NOW() WHERE id = $1
`

func (q *Queries) RevokeAdminSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, RevokeAdminSession, id)
	return err
}

const RevokeAllAdminSessionsByUser = `-- name: RevokeAllAdminSessionsByUser :exec
UPDATE admin_sessions SET "revokedAt" = NOW()
WHERE "userId" = $1 AND "revokedAt" IS NULL
`

func (q *Queries) RevokeAllAdminSessionsByUser(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, RevokeAllAdminSessionsByUser, userid)
	return err
}

const UpdateAdminSessionLastActive = `-- name: UpdateAdminSessionLastActive :exec
UPDATE admin_sessions SET "lastActive" = NOW() WHERE id = $1
`

func (q *Queries) UpdateAdminSessionLastActive(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, UpdateAdminSessionLastActive, id)
	return err
}

const UpdateAdminTwoFactorBackupCodes = `-- name: UpdateAdminTwoFactorBackupCodes :exec
UPDATE admin_two_factor SET
    "backupCodes" = $2,
    "updatedAt" = NOW()
WHERE "userId" = $1
`

type UpdateAdminTwoFactorBackupCodesParams struct {
	UserId      string   `json:"userId"`
	BackupCodes []string `json:"backupCodes"`
}

func (q *Queries) UpdateAdminTwoFactorBackupCodes(ctx context.Context, arg UpdateAdminTwoFactorBackupCodesParams) error {
	_, err := q.db.Exec(ctx, UpdateAdminTwoFactorBackupCodes, arg.UserId, arg.BackupCodes)
	return err
}

const UpsertSystemAlert = `-- name: UpsertSystemAlert :one
INSERT INTO system_alerts (
    id, type, severity, title, description, "alertKey", metadata,
    "firstSeen", "lastSeen", "occurrenceCount", dismissed, "actionRequired",
    "expiresAt", "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW(), 1, false, $8, $9, NOW(), NOW()
)
ON CONFLICT ("alertKey")
DO UPDATE SET
    "lastSeen" = NOW(),
    "occurrenceCount" = system_alerts."occurrenceCount" + 1,
    severity = EXCLUDED.severity,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    metadata = EXCLUDED.metadata,
    "updatedAt" = NOW()
RETURNING id, type, severity, title, description, "alertKey", metadata, "firstSeen", "lastSeen", "occurrenceCount", dismissed, "actionRequired", "expiresAt", "createdAt", "updatedAt"
`

type UpsertSystemAlertParams struct {
	ID             string           `json:"id"`
	Type           string           `json:"type"`
	Severity       string           `json:"severity"`
	Title          string           `json:"title"`
	Description    string           `json:"description"`
	AlertKey       string           `json:"alertKey"`
	Metadata       string           `json:"metadata"`
	ActionRequired bool             `json:"actionRequired"`
	ExpiresAt      pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) UpsertSystemAlert(ctx context.Context, arg UpsertSystemAlertParams) (SystemAlert, error) {
	row := q.db.QueryRow(ctx, UpsertSystemAlert,
		arg.ID,
		arg.Type,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.AlertKey,
		arg.Metadata,
		arg.ActionRequired,
		arg.ExpiresAt,
	)
	var i SystemAlert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.AlertKey,
		&i.Metadata,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.Dismissed,
		&i.ActionRequired,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
