// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountAdminAuditLogs = `-- name: CountAdminAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE ($1::text IS NULL OR "actorType"::text = $1)
  AND ($2::text IS NULL OR (action::text = $2 OR event::text = $2))
  AND ($3::text IS NULL OR resource = $3)
  AND ($4::text IS NULL OR ("adminId" = $4 OR "userId" = $4))
`

type CountAdminAuditLogsParams struct {
	ActorType      pgtype.Text `json:"actor_type"`
	ActionFilter   pgtype.Text `json:"action_filter"`
	ResourceFilter pgtype.Text `json:"resource_filter"`
	AdminID        pgtype.Text `json:"admin_id"`
}

func (q *Queries) CountAdminAuditLogs(ctx context.Context, arg CountAdminAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountAdminAuditLogs,
		arg.ActorType,
		arg.ActionFilter,
		arg.ResourceFilter,
		arg.AdminID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountAdminAuditLogsByDetailsText = `-- name: CountAdminAuditLogsByDetailsText :one
SELECT COUNT(*) FROM audit_logs
WHERE metadata::text ILIKE '%' || $1::text || '%'
  AND ($2::text IS NULL OR "actorType"::text = $2)
  AND ($3::text IS NULL OR action::text = $3)
  AND ($4::text IS NULL OR resource = $4)
`

type CountAdminAuditLogsByDetailsTextParams struct {
	SearchText string      `json:"search_text"`
	ActorType  pgtype.Text `json:"actor_type"`
	Action     pgtype.Text `json:"action"`
	Resource   pgtype.Text `json:"resource"`
}

func (q *Queries) CountAdminAuditLogsByDetailsText(ctx context.Context, arg CountAdminAuditLogsByDetailsTextParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountAdminAuditLogsByDetailsText,
		arg.SearchText,
		arg.ActorType,
		arg.Action,
		arg.Resource,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountOldAdminAuditLogs = `-- name: CountOldAdminAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE "createdAt" < $1 AND "actorType" IS NOT NULL
`

func (q *Queries) CountOldAdminAuditLogs(ctx context.Context, cutoffTimestamp pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, CountOldAdminAuditLogs, cutoffTimestamp)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateAdminAuditLog = `-- name: CreateAdminAuditLog :exec

INSERT INTO audit_logs (
    id, "adminId", "adminEmail", "actorType", event, action, resource, "resourceId",
    metadata, "ipAddress", "userAgent", "createdAt"
) VALUES (
    $1,
    $2,
    $3,
    $4::"AuditActorType",
    'ADMIN_ACTION'::"AuditEventType",
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    NOW()
)
`

type CreateAdminAuditLogParams struct {
	ID         string      `json:"id"`
	AdminID    pgtype.Text `json:"admin_id"`
	AdminEmail pgtype.Text `json:"admin_email"`
	ActorType  interface{} `json:"actor_type"`
	Action     pgtype.Text `json:"action"`
	Resource   pgtype.Text `json:"resource"`
	ResourceID pgtype.Text `json:"resource_id"`
	Details    []byte      `json:"details"`
	IpAddress  pgtype.Text `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
}

// Admin Audit Log Queries (Unified audit_logs table)
func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) error {
	_, err := q.db.Exec(ctx, CreateAdminAuditLog,
		arg.ID,
		arg.AdminID,
		arg.AdminEmail,
		arg.ActorType,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const DeleteOldAdminAuditLogs = `-- name: DeleteOldAdminAuditLogs :execrows
DELETE FROM audit_logs
WHERE "createdAt" < $1 AND "actorType" IS NOT NULL
`

func (q *Queries) DeleteOldAdminAuditLogs(ctx context.Context, cutoffTimestamp pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteOldAdminAuditLogs, cutoffTimestamp)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ListAdminAuditLogs = `-- name: ListAdminAuditLogs :many
SELECT id, COALESCE("adminId", "userId") as "adminId", COALESCE("adminEmail", '') as "adminEmail",
    "actorType"::text, COALESCE(action::text, event::text) as action, resource, "resourceId",
    metadata as details, "ipAddress", "userAgent", "createdAt"
FROM audit_logs
WHERE ($1::text IS NULL OR "actorType"::text = $1)
  AND ($2::text IS NULL OR (action::text = $2 OR event::text = $2))
  AND ($3::text IS NULL OR resource = $3)
  AND ($4::text IS NULL OR ("adminId" = $4 OR "userId" = $4))
ORDER BY "createdAt" DESC
LIMIT $6 OFFSET $5
`

type ListAdminAuditLogsParams struct {
	ActorType      pgtype.Text `json:"actor_type"`
	ActionFilter   pgtype.Text `json:"action_filter"`
	ResourceFilter pgtype.Text `json:"resource_filter"`
	AdminID        pgtype.Text `json:"admin_id"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
}

type ListAdminAuditLogsRow struct {
	ID         string           `json:"id"`
	AdminId    pgtype.Text      `json:"adminId"`
	AdminEmail string           `json:"adminEmail"`
	ActorType  string           `json:"actorType"`
	Action     interface{}      `json:"action"`
	Resource   pgtype.Text      `json:"resource"`
	ResourceId pgtype.Text      `json:"resourceId"`
	Details    []byte           `json:"details"`
	IpAddress  pgtype.Text      `json:"ipAddress"`
	UserAgent  pgtype.Text      `json:"userAgent"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) ListAdminAuditLogs(ctx context.Context, arg ListAdminAuditLogsParams) ([]ListAdminAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, ListAdminAuditLogs,
		arg.ActorType,
		arg.ActionFilter,
		arg.ResourceFilter,
		arg.AdminID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAuditLogsRow{}
	for rows.Next() {
		var i ListAdminAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminId,
			&i.AdminEmail,
			&i.ActorType,
			&i.Action,
			&i.Resource,
			&i.ResourceId,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchAdminAuditLogsByDetailsText = `-- name: SearchAdminAuditLogsByDetailsText :many
SELECT id, "adminId", "adminEmail", "actorType"::text, action::text, resource, "resourceId",
    metadata as details, "ipAddress", "userAgent", "createdAt"
FROM audit_logs
WHERE metadata::text ILIKE '%' || $1::text || '%'
  AND ($2::text IS NULL OR "actorType"::text = $2)
  AND ($3::text IS NULL OR action::text = $3)
  AND ($4::text IS NULL OR resource = $4)
ORDER BY "createdAt" DESC
LIMIT $6 OFFSET $5
`

type SearchAdminAuditLogsByDetailsTextParams struct {
	SearchText string      `json:"search_text"`
	ActorType  pgtype.Text `json:"actor_type"`
	Action     pgtype.Text `json:"action"`
	Resource   pgtype.Text `json:"resource"`
	Offset     int32       `json:"offset"`
	Limit      int32       `json:"limit"`
}

type SearchAdminAuditLogsByDetailsTextRow struct {
	ID         string           `json:"id"`
	AdminId    pgtype.Text      `json:"adminId"`
	AdminEmail pgtype.Text      `json:"adminEmail"`
	ActorType  string           `json:"actorType"`
	Action     string           `json:"action"`
	Resource   pgtype.Text      `json:"resource"`
	ResourceId pgtype.Text      `json:"resourceId"`
	Details    []byte           `json:"details"`
	IpAddress  pgtype.Text      `json:"ipAddress"`
	UserAgent  pgtype.Text      `json:"userAgent"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) SearchAdminAuditLogsByDetailsText(ctx context.Context, arg SearchAdminAuditLogsByDetailsTextParams) ([]SearchAdminAuditLogsByDetailsTextRow, error) {
	rows, err := q.db.Query(ctx, SearchAdminAuditLogsByDetailsText,
		arg.SearchText,
		arg.ActorType,
		arg.Action,
		arg.Resource,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAdminAuditLogsByDetailsTextRow{}
	for rows.Next() {
		var i SearchAdminAuditLogsByDetailsTextRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminId,
			&i.AdminEmail,
			&i.ActorType,
			&i.Action,
			&i.Resource,
			&i.ResourceId,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
