// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_subscriptions_ext.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountSubscriptionsFiltered = `-- name: CountSubscriptionsFiltered :one

SELECT COUNT(*)
FROM subscriptions s
JOIN users u ON s."userId" = u.id
WHERE ($1::text IS NULL OR s.tier::text = $1)
  AND ($2::text IS NULL OR s.status::text = $2)
  AND ($3::text IS NULL OR LOWER(u.email) LIKE '%' || LOWER($3) || '%')
`

type CountSubscriptionsFilteredParams struct {
	TierFilter   pgtype.Text `json:"tier_filter"`
	StatusFilter pgtype.Text `json:"status_filter"`
	EmailSearch  pgtype.Text `json:"email_search"`
}

// Admin Subscription Management Queries
func (q *Queries) CountSubscriptionsFiltered(ctx context.Context, arg CountSubscriptionsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountSubscriptionsFiltered, arg.TierFilter, arg.StatusFilter, arg.EmailSearch)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetSubscriptionDetailAdmin = `-- name: GetSubscriptionDetailAdmin :one
SELECT s.id, s."userId", u.email, u."firstName", u."lastName",
    s.tier::text, s.status::text, s."stripeSubscriptionId", s."stripeCustomerId",
    s."currentPeriodStart", s."currentPeriodEnd", s."trialEnd",
    s."cancelAtPeriodEnd", s."createdAt", s."updatedAt"
FROM subscriptions s
JOIN users u ON s."userId" = u.id
WHERE s.id = $1
`

type GetSubscriptionDetailAdminRow struct {
	ID                   string           `json:"id"`
	UserId               string           `json:"userId"`
	Email                string           `json:"email"`
	FirstName            pgtype.Text      `json:"firstName"`
	LastName             pgtype.Text      `json:"lastName"`
	STier                string           `json:"s_tier"`
	SStatus              string           `json:"s_status"`
	StripeSubscriptionId pgtype.Text      `json:"stripeSubscriptionId"`
	StripeCustomerId     pgtype.Text      `json:"stripeCustomerId"`
	CurrentPeriodStart   pgtype.Timestamp `json:"currentPeriodStart"`
	CurrentPeriodEnd     pgtype.Timestamp `json:"currentPeriodEnd"`
	TrialEnd             pgtype.Timestamp `json:"trialEnd"`
	CancelAtPeriodEnd    bool             `json:"cancelAtPeriodEnd"`
	CreatedAt            pgtype.Timestamp `json:"createdAt"`
	UpdatedAt            pgtype.Timestamp `json:"updatedAt"`
}

func (q *Queries) GetSubscriptionDetailAdmin(ctx context.Context, id string) (GetSubscriptionDetailAdminRow, error) {
	row := q.db.QueryRow(ctx, GetSubscriptionDetailAdmin, id)
	var i GetSubscriptionDetailAdminRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.STier,
		&i.SStatus,
		&i.StripeSubscriptionId,
		&i.StripeCustomerId,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetSubscriptionStatusStats = `-- name: GetSubscriptionStatusStats :one
SELECT
    COUNT(*) FILTER (WHERE status::text = 'ACTIVE') AS active_count,
    COUNT(*) FILTER (WHERE status::text = 'TRIALING') AS trialing_count,
    COUNT(*) FILTER (WHERE status::text = 'PAST_DUE') AS past_due_count,
    COUNT(*) FILTER (WHERE status::text = 'FREE') AS free_count
FROM subscriptions
`

type GetSubscriptionStatusStatsRow struct {
	ActiveCount   int64 `json:"active_count"`
	TrialingCount int64 `json:"trialing_count"`
	PastDueCount  int64 `json:"past_due_count"`
	FreeCount     int64 `json:"free_count"`
}

func (q *Queries) GetSubscriptionStatusStats(ctx context.Context) (GetSubscriptionStatusStatsRow, error) {
	row := q.db.QueryRow(ctx, GetSubscriptionStatusStats)
	var i GetSubscriptionStatusStatsRow
	err := row.Scan(
		&i.ActiveCount,
		&i.TrialingCount,
		&i.PastDueCount,
		&i.FreeCount,
	)
	return i, err
}

const GetSubscriptionStripeAndStatus = `-- name: GetSubscriptionStripeAndStatus :one
SELECT "stripeSubscriptionId", status::text FROM subscriptions WHERE id = $1
`

type GetSubscriptionStripeAndStatusRow struct {
	StripeSubscriptionId pgtype.Text `json:"stripeSubscriptionId"`
	Status               string      `json:"status"`
}

func (q *Queries) GetSubscriptionStripeAndStatus(ctx context.Context, id string) (GetSubscriptionStripeAndStatusRow, error) {
	row := q.db.QueryRow(ctx, GetSubscriptionStripeAndStatus, id)
	var i GetSubscriptionStripeAndStatusRow
	err := row.Scan(&i.StripeSubscriptionId, &i.Status)
	return i, err
}

const GetSubscriptionStripeID = `-- name: GetSubscriptionStripeID :one
SELECT "stripeSubscriptionId", tier::text FROM subscriptions WHERE id = $1
`

type GetSubscriptionStripeIDRow struct {
	StripeSubscriptionId pgtype.Text `json:"stripeSubscriptionId"`
	Tier                 string      `json:"tier"`
}

func (q *Queries) GetSubscriptionStripeID(ctx context.Context, id string) (GetSubscriptionStripeIDRow, error) {
	row := q.db.QueryRow(ctx, GetSubscriptionStripeID, id)
	var i GetSubscriptionStripeIDRow
	err := row.Scan(&i.StripeSubscriptionId, &i.Tier)
	return i, err
}

const GetSubscriptionUserID = `-- name: GetSubscriptionUserID :one
SELECT "userId" FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionUserID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, GetSubscriptionUserID, id)
	var userId string
	err := row.Scan(&userId)
	return userId, err
}

const GetUserSubscriptionInfo = `-- name: GetUserSubscriptionInfo :one
SELECT tier::text, status::text,
    COALESCE(TO_CHAR("currentPeriodStart", 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '') as start_date,
    COALESCE(TO_CHAR("currentPeriodEnd", 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '') as end_date
FROM subscriptions
WHERE "userId" = $1
ORDER BY "createdAt" DESC LIMIT 1
`

type GetUserSubscriptionInfoRow struct {
	Tier      string      `json:"tier"`
	Status    string      `json:"status"`
	StartDate interface{} `json:"start_date"`
	EndDate   interface{} `json:"end_date"`
}

func (q *Queries) GetUserSubscriptionInfo(ctx context.Context, userid string) (GetUserSubscriptionInfoRow, error) {
	row := q.db.QueryRow(ctx, GetUserSubscriptionInfo, userid)
	var i GetUserSubscriptionInfoRow
	err := row.Scan(
		&i.Tier,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const ListSubscriptionsFiltered = `-- name: ListSubscriptionsFiltered :many
SELECT s.id, s."userId", u.email, u."firstName", u."lastName",
    s.tier::text, s.status::text, s."stripeSubscriptionId", s."stripeCustomerId",
    s."currentPeriodStart", s."currentPeriodEnd", s."trialEnd",
    s."cancelAtPeriodEnd", s."createdAt", s."updatedAt"
FROM subscriptions s
JOIN users u ON s."userId" = u.id
WHERE ($1::text IS NULL OR s.tier::text = $1)
  AND ($2::text IS NULL OR s.status::text = $2)
  AND ($3::text IS NULL OR LOWER(u.email) LIKE '%' || LOWER($3) || '%')
ORDER BY s."createdAt" DESC
LIMIT $5 OFFSET $4
`

type ListSubscriptionsFilteredParams struct {
	TierFilter   pgtype.Text `json:"tier_filter"`
	StatusFilter pgtype.Text `json:"status_filter"`
	EmailSearch  pgtype.Text `json:"email_search"`
	Offset       int32       `json:"offset"`
	Limit        int32       `json:"limit"`
}

type ListSubscriptionsFilteredRow struct {
	ID                   string           `json:"id"`
	UserId               string           `json:"userId"`
	Email                string           `json:"email"`
	FirstName            pgtype.Text      `json:"firstName"`
	LastName             pgtype.Text      `json:"lastName"`
	STier                string           `json:"s_tier"`
	SStatus              string           `json:"s_status"`
	StripeSubscriptionId pgtype.Text      `json:"stripeSubscriptionId"`
	StripeCustomerId     pgtype.Text      `json:"stripeCustomerId"`
	CurrentPeriodStart   pgtype.Timestamp `json:"currentPeriodStart"`
	CurrentPeriodEnd     pgtype.Timestamp `json:"currentPeriodEnd"`
	TrialEnd             pgtype.Timestamp `json:"trialEnd"`
	CancelAtPeriodEnd    bool             `json:"cancelAtPeriodEnd"`
	CreatedAt            pgtype.Timestamp `json:"createdAt"`
	UpdatedAt            pgtype.Timestamp `json:"updatedAt"`
}

func (q *Queries) ListSubscriptionsFiltered(ctx context.Context, arg ListSubscriptionsFilteredParams) ([]ListSubscriptionsFilteredRow, error) {
	rows, err := q.db.Query(ctx, ListSubscriptionsFiltered,
		arg.TierFilter,
		arg.StatusFilter,
		arg.EmailSearch,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsFilteredRow{}
	for rows.Next() {
		var i ListSubscriptionsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.STier,
			&i.SStatus,
			&i.StripeSubscriptionId,
			&i.StripeCustomerId,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.TrialEnd,
			&i.CancelAtPeriodEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
