// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analysis_cache.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const DeleteAnalysisCacheByUserAndKey = `-- name: DeleteAnalysisCacheByUserAndKey :exec
DELETE FROM analysis_cache
WHERE "userId" = $1 AND key = $2
`

type DeleteAnalysisCacheByUserAndKeyParams struct {
	UserId string `json:"userId"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteAnalysisCacheByUserAndKey(ctx context.Context, arg DeleteAnalysisCacheByUserAndKeyParams) error {
	_, err := q.db.Exec(ctx, DeleteAnalysisCacheByUserAndKey, arg.UserId, arg.Key)
	return err
}

const GetAnalysisContext = `-- name: GetAnalysisContext :one

SELECT content, "metricsData", "narrativeData", "lastAccessedAt"
FROM analysis_cache
WHERE "userId" = $1
  AND feature = 'dual_agent_market_analysis'
  AND location ILIKE $2
  AND "supersededBy" IS NULL
ORDER BY "lastAccessedAt" DESC
LIMIT 1
`

type GetAnalysisContextParams struct {
	UserId   string `json:"userId"`
	Location string `json:"location"`
}

type GetAnalysisContextRow struct {
	Content        string           `json:"content"`
	MetricsData    []byte           `json:"metricsData"`
	NarrativeData  []byte           `json:"narrativeData"`
	LastAccessedAt pgtype.Timestamp `json:"lastAccessedAt"`
}

// Analysis Cache Queries
// Table: analysis_cache (schema 002_cache.sql)
// These queries supplement existing queries in cache.sql
func (q *Queries) GetAnalysisContext(ctx context.Context, arg GetAnalysisContextParams) (GetAnalysisContextRow, error) {
	row := q.db.QueryRow(ctx, GetAnalysisContext, arg.UserId, arg.Location)
	var i GetAnalysisContextRow
	err := row.Scan(
		&i.Content,
		&i.MetricsData,
		&i.NarrativeData,
		&i.LastAccessedAt,
	)
	return i, err
}

const GetInvestmentPlanCacheByID = `-- name: GetInvestmentPlanCacheByID :one
SELECT id, key
FROM analysis_cache
WHERE id = $1 AND "userId" = $2 AND key LIKE 'investment_plan_%'
`

type GetInvestmentPlanCacheByIDParams struct {
	ID     string `json:"id"`
	UserId string `json:"userId"`
}

type GetInvestmentPlanCacheByIDRow struct {
	ID  string `json:"id"`
	Key string `json:"key"`
}

func (q *Queries) GetInvestmentPlanCacheByID(ctx context.Context, arg GetInvestmentPlanCacheByIDParams) (GetInvestmentPlanCacheByIDRow, error) {
	row := q.db.QueryRow(ctx, GetInvestmentPlanCacheByID, arg.ID, arg.UserId)
	var i GetInvestmentPlanCacheByIDRow
	err := row.Scan(&i.ID, &i.Key)
	return i, err
}
