// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_extended.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateEmailVerificationCode = `-- name: CreateEmailVerificationCode :one
INSERT INTO email_verification_codes (
    id, email, code, "expiresAt", verified, attempts, "createdAt"
) VALUES (
    $1, $2, $3, $4, false, 0, NOW()
) RETURNING id, email, code, "expiresAt", verified, attempts, "createdAt"
`

type CreateEmailVerificationCodeParams struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	Code      string           `json:"code"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) CreateEmailVerificationCode(ctx context.Context, arg CreateEmailVerificationCodeParams) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, CreateEmailVerificationCode,
		arg.ID,
		arg.Email,
		arg.Code,
		arg.ExpiresAt,
	)
	var i EmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.Verified,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const CreatePasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (
    id, token, "userId", email, "expiresAt", used, "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, false, NOW(), NOW()
) RETURNING id, token, "userId", email, "expiresAt", used, "createdAt", "updatedAt"
`

type CreatePasswordResetTokenParams struct {
	ID        string           `json:"id"`
	Token     string           `json:"token"`
	UserId    string           `json:"userId"`
	Email     string           `json:"email"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, CreatePasswordResetToken,
		arg.ID,
		arg.Token,
		arg.UserId,
		arg.Email,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserId,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateSilentLoginSession = `-- name: CreateSilentLoginSession :one
INSERT INTO silent_login_sessions (
    id, "userId", "jwtToken", "clientUrl", "createdAt", "expiresAt", "lastAccessedAt", active
) VALUES (
    $1, $2, $3, $4, NOW(), $5, NOW(), true
) RETURNING id, "userId", "jwtToken", "clientUrl", "createdAt", "expiresAt", "lastAccessedAt", active
`

type CreateSilentLoginSessionParams struct {
	ID        string           `json:"id"`
	UserId    string           `json:"userId"`
	JwtToken  string           `json:"jwtToken"`
	ClientUrl pgtype.Text      `json:"clientUrl"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) CreateSilentLoginSession(ctx context.Context, arg CreateSilentLoginSessionParams) (SilentLoginSession, error) {
	row := q.db.QueryRow(ctx, CreateSilentLoginSession,
		arg.ID,
		arg.UserId,
		arg.JwtToken,
		arg.ClientUrl,
		arg.ExpiresAt,
	)
	var i SilentLoginSession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.JwtToken,
		&i.ClientUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.Active,
	)
	return i, err
}

const DeactivateSilentLoginSession = `-- name: DeactivateSilentLoginSession :exec
UPDATE silent_login_sessions
SET active = false
WHERE id = $1
`

func (q *Queries) DeactivateSilentLoginSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeactivateSilentLoginSession, id)
	return err
}

const DeactivateUserSilentLoginSessions = `-- name: DeactivateUserSilentLoginSessions :exec
UPDATE silent_login_sessions
SET active = false
WHERE "userId" = $1
`

func (q *Queries) DeactivateUserSilentLoginSessions(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, DeactivateUserSilentLoginSessions, userid)
	return err
}

const DeleteEmailVerificationCodesByEmail = `-- name: DeleteEmailVerificationCodesByEmail :exec
DELETE FROM email_verification_codes WHERE email = $1
`

func (q *Queries) DeleteEmailVerificationCodesByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, DeleteEmailVerificationCodesByEmail, email)
	return err
}

const DeleteExpiredEmailVerificationCodes = `-- name: DeleteExpiredEmailVerificationCodes :exec
DELETE FROM email_verification_codes WHERE "expiresAt" < NOW()
`

func (q *Queries) DeleteExpiredEmailVerificationCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, DeleteExpiredEmailVerificationCodes)
	return err
}

const DeleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens WHERE "expiresAt" < NOW()
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, DeleteExpiredPasswordResetTokens)
	return err
}

const DeleteExpiredSilentLoginSessions = `-- name: DeleteExpiredSilentLoginSessions :exec
DELETE FROM silent_login_sessions WHERE "expiresAt" < NOW()
`

func (q *Queries) DeleteExpiredSilentLoginSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, DeleteExpiredSilentLoginSessions)
	return err
}

const GetActiveSilentLoginSessionsByUser = `-- name: GetActiveSilentLoginSessionsByUser :many
SELECT id, "userId", "jwtToken", "clientUrl", "createdAt", "expiresAt", "lastAccessedAt", active FROM silent_login_sessions
WHERE "userId" = $1 AND active = true AND "expiresAt" > NOW()
ORDER BY "createdAt" DESC
`

func (q *Queries) GetActiveSilentLoginSessionsByUser(ctx context.Context, userid string) ([]SilentLoginSession, error) {
	rows, err := q.db.Query(ctx, GetActiveSilentLoginSessionsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SilentLoginSession{}
	for rows.Next() {
		var i SilentLoginSession
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.JwtToken,
			&i.ClientUrl,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastAccessedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEmailVerificationCode = `-- name: GetEmailVerificationCode :one

SELECT id, email, code, "expiresAt", verified, attempts, "createdAt" FROM email_verification_codes
WHERE email = $1 AND code = $2 AND verified = false AND "expiresAt" > NOW()
`

type GetEmailVerificationCodeParams struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

// Email Verification Code Queries
func (q *Queries) GetEmailVerificationCode(ctx context.Context, arg GetEmailVerificationCodeParams) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, GetEmailVerificationCode, arg.Email, arg.Code)
	var i EmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.Verified,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const GetEmailVerificationCodeByID = `-- name: GetEmailVerificationCodeByID :one
SELECT id, email, code, "expiresAt", verified, attempts, "createdAt" FROM email_verification_codes WHERE id = $1
`

func (q *Queries) GetEmailVerificationCodeByID(ctx context.Context, id string) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, GetEmailVerificationCodeByID, id)
	var i EmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.Verified,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const GetLatestEmailVerificationCode = `-- name: GetLatestEmailVerificationCode :one
SELECT id, email, code, "expiresAt", verified, attempts, "createdAt" FROM email_verification_codes
WHERE email = $1 AND verified = false AND "expiresAt" > NOW()
ORDER BY "createdAt" DESC
LIMIT 1
`

func (q *Queries) GetLatestEmailVerificationCode(ctx context.Context, email string) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, GetLatestEmailVerificationCode, email)
	var i EmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.Verified,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const GetPasswordResetTokenByID = `-- name: GetPasswordResetTokenByID :one
SELECT id, token, "userId", email, "expiresAt", used, "createdAt", "updatedAt" FROM password_reset_tokens WHERE id = $1
`

func (q *Queries) GetPasswordResetTokenByID(ctx context.Context, id string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, GetPasswordResetTokenByID, id)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserId,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetPasswordResetTokenByToken = `-- name: GetPasswordResetTokenByToken :one

SELECT id, token, "userId", email, "expiresAt", used, "createdAt", "updatedAt" FROM password_reset_tokens
WHERE token = $1 AND used = false AND "expiresAt" > NOW()
`

// Password Reset Token Queries
func (q *Queries) GetPasswordResetTokenByToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, GetPasswordResetTokenByToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserId,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetPasswordResetTokensByUser = `-- name: GetPasswordResetTokensByUser :many
SELECT id, token, "userId", email, "expiresAt", used, "createdAt", "updatedAt" FROM password_reset_tokens
WHERE "userId" = $1
ORDER BY "createdAt" DESC
LIMIT $2
`

type GetPasswordResetTokensByUserParams struct {
	UserId string `json:"userId"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetPasswordResetTokensByUser(ctx context.Context, arg GetPasswordResetTokensByUserParams) ([]PasswordResetToken, error) {
	rows, err := q.db.Query(ctx, GetPasswordResetTokensByUser, arg.UserId, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PasswordResetToken{}
	for rows.Next() {
		var i PasswordResetToken
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.UserId,
			&i.Email,
			&i.ExpiresAt,
			&i.Used,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSilentLoginSessionByID = `-- name: GetSilentLoginSessionByID :one

SELECT id, "userId", "jwtToken", "clientUrl", "createdAt", "expiresAt", "lastAccessedAt", active FROM silent_login_sessions
WHERE id = $1 AND active = true AND "expiresAt" > NOW()
`

// Silent Login Session Queries
func (q *Queries) GetSilentLoginSessionByID(ctx context.Context, id string) (SilentLoginSession, error) {
	row := q.db.QueryRow(ctx, GetSilentLoginSessionByID, id)
	var i SilentLoginSession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.JwtToken,
		&i.ClientUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.Active,
	)
	return i, err
}

const IncrementEmailVerificationAttempts = `-- name: IncrementEmailVerificationAttempts :exec
UPDATE email_verification_codes
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementEmailVerificationAttempts(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, IncrementEmailVerificationAttempts, id)
	return err
}

const InvalidateUserPasswordResetTokens = `-- name: InvalidateUserPasswordResetTokens :exec
UPDATE password_reset_tokens
SET used = true, "updatedAt" = NOW()
WHERE "userId" = $1 AND used = false
`

func (q *Queries) InvalidateUserPasswordResetTokens(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, InvalidateUserPasswordResetTokens, userid)
	return err
}

const MarkEmailVerificationCodeVerified = `-- name: MarkEmailVerificationCodeVerified :exec
UPDATE email_verification_codes
SET verified = true
WHERE id = $1
`

func (q *Queries) MarkEmailVerificationCodeVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, MarkEmailVerificationCodeVerified, id)
	return err
}

const MarkPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens
SET used = true, "updatedAt" = NOW()
WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, MarkPasswordResetTokenUsed, id)
	return err
}

const UpdateSilentLoginSessionAccess = `-- name: UpdateSilentLoginSessionAccess :exec
UPDATE silent_login_sessions
SET "lastAccessedAt" = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSilentLoginSessionAccess(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, UpdateSilentLoginSessionAccess, id)
	return err
}
