// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cache.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountAllCache = `-- name: CountAllCache :one
SELECT COUNT(*) FROM analysis_cache
`

func (q *Queries) CountAllCache(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountAllCache)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountCacheByUser = `-- name: CountCacheByUser :one
SELECT COUNT(*) FROM analysis_cache WHERE "userId" = $1
`

func (q *Queries) CountCacheByUser(ctx context.Context, userid string) (int64, error) {
	row := q.db.QueryRow(ctx, CountCacheByUser, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountCacheByUserFeatureActive = `-- name: CountCacheByUserFeatureActive :one
SELECT COUNT(*) FROM analysis_cache
WHERE "userId" = $1 AND feature = $2
    AND "supersededBy" IS NULL AND "expiresAt" > NOW()
`

type CountCacheByUserFeatureActiveParams struct {
	UserId  string `json:"userId"`
	Feature string `json:"feature"`
}

func (q *Queries) CountCacheByUserFeatureActive(ctx context.Context, arg CountCacheByUserFeatureActiveParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountCacheByUserFeatureActive, arg.UserId, arg.Feature)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountExpiredCache = `-- name: CountExpiredCache :one
SELECT COUNT(*) FROM analysis_cache WHERE "expiresAt" < NOW()
`

func (q *Queries) CountExpiredCache(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountExpiredCache)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountInvestmentPlanHistory = `-- name: CountInvestmentPlanHistory :one
SELECT COUNT(*)
FROM analysis_cache
WHERE "userId" = $1
    AND feature = 'investment_planning'
    AND "supersededBy" IS NULL
    AND ($2::text IS NULL OR $2 = '' OR location ILIKE '%' || $2 || '%')
`

type CountInvestmentPlanHistoryParams struct {
	UserId string      `json:"userId"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) CountInvestmentPlanHistory(ctx context.Context, arg CountInvestmentPlanHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountInvestmentPlanHistory, arg.UserId, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountMarketAnalysisHistory = `-- name: CountMarketAnalysisHistory :one
SELECT COUNT(*)
FROM analysis_cache
WHERE "userId" = $1
    AND feature IN ('dual_agent_market_analysis', 'market_analysis_v2')
    AND "supersededBy" IS NULL
    AND ($2::text IS NULL OR $2 = '' OR location ILIKE '%' || $2 || '%')
`

type CountMarketAnalysisHistoryParams struct {
	UserId string      `json:"userId"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) CountMarketAnalysisHistory(ctx context.Context, arg CountMarketAnalysisHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountMarketAnalysisHistory, arg.UserId, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountTrendsHistory = `-- name: CountTrendsHistory :one
SELECT COUNT(*)
FROM analysis_cache
WHERE "userId" = $1
    AND feature = 'market_trends'
    AND "supersededBy" IS NULL
    AND "expiresAt" > NOW()
`

func (q *Queries) CountTrendsHistory(ctx context.Context, userid string) (int64, error) {
	row := q.db.QueryRow(ctx, CountTrendsHistory, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteAiResponseCacheByUserAndFeature = `-- name: DeleteAiResponseCacheByUserAndFeature :exec
DELETE FROM analysis_cache WHERE "userId" = $1 AND feature = $2
`

type DeleteAiResponseCacheByUserAndFeatureParams struct {
	UserId  string `json:"userId"`
	Feature string `json:"feature"`
}

func (q *Queries) DeleteAiResponseCacheByUserAndFeature(ctx context.Context, arg DeleteAiResponseCacheByUserAndFeatureParams) error {
	_, err := q.db.Exec(ctx, DeleteAiResponseCacheByUserAndFeature, arg.UserId, arg.Feature)
	return err
}

const DeleteAiResponseCacheByUserAndKey = `-- name: DeleteAiResponseCacheByUserAndKey :exec
DELETE FROM analysis_cache WHERE "userId" = $1 AND key = $2
`

type DeleteAiResponseCacheByUserAndKeyParams struct {
	UserId string `json:"userId"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteAiResponseCacheByUserAndKey(ctx context.Context, arg DeleteAiResponseCacheByUserAndKeyParams) error {
	_, err := q.db.Exec(ctx, DeleteAiResponseCacheByUserAndKey, arg.UserId, arg.Key)
	return err
}

const DeleteAllCacheRows = `-- name: DeleteAllCacheRows :execrows
DELETE FROM analysis_cache
`

func (q *Queries) DeleteAllCacheRows(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteAllCacheRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteAllExpiredCache = `-- name: DeleteAllExpiredCache :execrows
DELETE FROM analysis_cache WHERE "expiresAt" < NOW()
`

func (q *Queries) DeleteAllExpiredCache(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteAllExpiredCache)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteCacheByFeature = `-- name: DeleteCacheByFeature :execrows
DELETE FROM analysis_cache WHERE feature = $1
`

func (q *Queries) DeleteCacheByFeature(ctx context.Context, feature string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteCacheByFeature, feature)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteCacheByIDAndUserID = `-- name: DeleteCacheByIDAndUserID :exec
DELETE FROM analysis_cache WHERE id = $1 AND "userId" = $2
`

type DeleteCacheByIDAndUserIDParams struct {
	ID     string `json:"id"`
	UserId string `json:"userId"`
}

func (q *Queries) DeleteCacheByIDAndUserID(ctx context.Context, arg DeleteCacheByIDAndUserIDParams) error {
	_, err := q.db.Exec(ctx, DeleteCacheByIDAndUserID, arg.ID, arg.UserId)
	return err
}

const DeleteCacheByKey = `-- name: DeleteCacheByKey :exec
DELETE FROM analysis_cache WHERE key = $1
`

func (q *Queries) DeleteCacheByKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, DeleteCacheByKey, key)
	return err
}

const DeleteCacheByKeyRows = `-- name: DeleteCacheByKeyRows :execrows
DELETE FROM analysis_cache WHERE key = $1
`

func (q *Queries) DeleteCacheByKeyRows(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteCacheByKeyRows, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteCacheByUserAndKey = `-- name: DeleteCacheByUserAndKey :exec
DELETE FROM analysis_cache
WHERE "userId" = $1 AND key = $2
`

type DeleteCacheByUserAndKeyParams struct {
	UserId string `json:"userId"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteCacheByUserAndKey(ctx context.Context, arg DeleteCacheByUserAndKeyParams) error {
	_, err := q.db.Exec(ctx, DeleteCacheByUserAndKey, arg.UserId, arg.Key)
	return err
}

const DeleteCacheByUserAndKeyRows = `-- name: DeleteCacheByUserAndKeyRows :execrows
DELETE FROM analysis_cache WHERE "userId" = $1 AND key = $2
`

type DeleteCacheByUserAndKeyRowsParams struct {
	UserId string `json:"userId"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteCacheByUserAndKeyRows(ctx context.Context, arg DeleteCacheByUserAndKeyRowsParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteCacheByUserAndKeyRows, arg.UserId, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteCacheByUserID = `-- name: DeleteCacheByUserID :exec
DELETE FROM analysis_cache WHERE "userId" = $1
`

func (q *Queries) DeleteCacheByUserID(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, DeleteCacheByUserID, userid)
	return err
}

const DeleteCacheByUserIDRows = `-- name: DeleteCacheByUserIDRows :execrows
DELETE FROM analysis_cache WHERE "userId" = $1
`

func (q *Queries) DeleteCacheByUserIDRows(ctx context.Context, userid string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteCacheByUserIDRows, userid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteCacheOlderThan = `-- name: DeleteCacheOlderThan :execrows
DELETE FROM analysis_cache WHERE "createdAt" < $1
`

func (q *Queries) DeleteCacheOlderThan(ctx context.Context, createdat pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteCacheOlderThan, createdat)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExpiredCache = `-- name: DeleteExpiredCache :execrows
DELETE FROM analysis_cache WHERE "expiresAt" < NOW()
`

func (q *Queries) DeleteExpiredCache(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredCache)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const GetActiveTrendCacheContent = `-- name: GetActiveTrendCacheContent :one
SELECT content FROM analysis_cache
WHERE "userId" = $1 AND key = $2
    AND feature = 'market_trends'
    AND "supersededBy" IS NULL
    AND "expiresAt" > NOW()
`

type GetActiveTrendCacheContentParams struct {
	UserId string `json:"userId"`
	Key    string `json:"key"`
}

func (q *Queries) GetActiveTrendCacheContent(ctx context.Context, arg GetActiveTrendCacheContentParams) (string, error) {
	row := q.db.QueryRow(ctx, GetActiveTrendCacheContent, arg.UserId, arg.Key)
	var content string
	err := row.Scan(&content)
	return content, err
}

const GetCacheByID = `-- name: GetCacheByID :one
SELECT id, key, "userId", location, feature, prompt, "promptHash", complexity, "investorProfile", "marketData", content, "fullReport", "metricsData", "narrativeData", metadata, "createdAt", "expiresAt", "lastAccessedAt", "accessCount", "supersededBy", "supersededAt", "cacheHits", "generationCost", "savingsGenerated" FROM analysis_cache WHERE id = $1
`

func (q *Queries) GetCacheByID(ctx context.Context, id string) (AnalysisCache, error) {
	row := q.db.QueryRow(ctx, GetCacheByID, id)
	var i AnalysisCache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserId,
		&i.Location,
		&i.Feature,
		&i.Prompt,
		&i.PromptHash,
		&i.Complexity,
		&i.InvestorProfile,
		&i.MarketData,
		&i.Content,
		&i.FullReport,
		&i.MetricsData,
		&i.NarrativeData,
		&i.Metadata,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.CacheHits,
		&i.GenerationCost,
		&i.SavingsGenerated,
	)
	return i, err
}

const GetCacheByKey = `-- name: GetCacheByKey :one
SELECT id, key, "userId", location, feature, prompt, "promptHash", complexity, "investorProfile", "marketData", content, "fullReport", "metricsData", "narrativeData", metadata, "createdAt", "expiresAt", "lastAccessedAt", "accessCount", "supersededBy", "supersededAt", "cacheHits", "generationCost", "savingsGenerated" FROM analysis_cache
WHERE key = $1 AND "expiresAt" > NOW()
`

func (q *Queries) GetCacheByKey(ctx context.Context, key string) (AnalysisCache, error) {
	row := q.db.QueryRow(ctx, GetCacheByKey, key)
	var i AnalysisCache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserId,
		&i.Location,
		&i.Feature,
		&i.Prompt,
		&i.PromptHash,
		&i.Complexity,
		&i.InvestorProfile,
		&i.MarketData,
		&i.Content,
		&i.FullReport,
		&i.MetricsData,
		&i.NarrativeData,
		&i.Metadata,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.CacheHits,
		&i.GenerationCost,
		&i.SavingsGenerated,
	)
	return i, err
}

const GetCacheByUserAndKey = `-- name: GetCacheByUserAndKey :one
SELECT id, key, "userId", location, feature, prompt, "promptHash", complexity, "investorProfile", "marketData", content, "fullReport", "metricsData", "narrativeData", metadata, "createdAt", "expiresAt", "lastAccessedAt", "accessCount", "supersededBy", "supersededAt", "cacheHits", "generationCost", "savingsGenerated" FROM analysis_cache
WHERE "userId" = $1 AND key = $2 AND "expiresAt" > NOW()
`

type GetCacheByUserAndKeyParams struct {
	UserId string `json:"userId"`
	Key    string `json:"key"`
}

func (q *Queries) GetCacheByUserAndKey(ctx context.Context, arg GetCacheByUserAndKeyParams) (AnalysisCache, error) {
	row := q.db.QueryRow(ctx, GetCacheByUserAndKey, arg.UserId, arg.Key)
	var i AnalysisCache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserId,
		&i.Location,
		&i.Feature,
		&i.Prompt,
		&i.PromptHash,
		&i.Complexity,
		&i.InvestorProfile,
		&i.MarketData,
		&i.Content,
		&i.FullReport,
		&i.MetricsData,
		&i.NarrativeData,
		&i.Metadata,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.CacheHits,
		&i.GenerationCost,
		&i.SavingsGenerated,
	)
	return i, err
}

const GetCacheByUserAndKeyNoExpiry = `-- name: GetCacheByUserAndKeyNoExpiry :one
SELECT id, key, "userId", location, feature, prompt, "promptHash", complexity, "investorProfile", "marketData", content, "fullReport", "metricsData", "narrativeData", metadata, "createdAt", "expiresAt", "lastAccessedAt", "accessCount", "supersededBy", "supersededAt", "cacheHits", "generationCost", "savingsGenerated" FROM analysis_cache
WHERE "userId" = $1 AND key = $2
`

type GetCacheByUserAndKeyNoExpiryParams struct {
	UserId string `json:"userId"`
	Key    string `json:"key"`
}

// Used for investment plans which shouldn't expire like ephemeral cached data
func (q *Queries) GetCacheByUserAndKeyNoExpiry(ctx context.Context, arg GetCacheByUserAndKeyNoExpiryParams) (AnalysisCache, error) {
	row := q.db.QueryRow(ctx, GetCacheByUserAndKeyNoExpiry, arg.UserId, arg.Key)
	var i AnalysisCache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserId,
		&i.Location,
		&i.Feature,
		&i.Prompt,
		&i.PromptHash,
		&i.Complexity,
		&i.InvestorProfile,
		&i.MarketData,
		&i.Content,
		&i.FullReport,
		&i.MetricsData,
		&i.NarrativeData,
		&i.Metadata,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.CacheHits,
		&i.GenerationCost,
		&i.SavingsGenerated,
	)
	return i, err
}

const GetCacheIDAndKeyByIDUserKeyLike = `-- name: GetCacheIDAndKeyByIDUserKeyLike :one
SELECT id, key FROM analysis_cache WHERE id = $1 AND "userId" = $2 AND key LIKE $3
`

type GetCacheIDAndKeyByIDUserKeyLikeParams struct {
	ID     string `json:"id"`
	UserId string `json:"userId"`
	Key    string `json:"key"`
}

type GetCacheIDAndKeyByIDUserKeyLikeRow struct {
	ID  string `json:"id"`
	Key string `json:"key"`
}

func (q *Queries) GetCacheIDAndKeyByIDUserKeyLike(ctx context.Context, arg GetCacheIDAndKeyByIDUserKeyLikeParams) (GetCacheIDAndKeyByIDUserKeyLikeRow, error) {
	row := q.db.QueryRow(ctx, GetCacheIDAndKeyByIDUserKeyLike, arg.ID, arg.UserId, arg.Key)
	var i GetCacheIDAndKeyByIDUserKeyLikeRow
	err := row.Scan(&i.ID, &i.Key)
	return i, err
}

const GetCacheIDAndKeyByUserAndKey = `-- name: GetCacheIDAndKeyByUserAndKey :one
SELECT id, key FROM analysis_cache WHERE key = $1 AND "userId" = $2
`

type GetCacheIDAndKeyByUserAndKeyParams struct {
	Key    string `json:"key"`
	UserId string `json:"userId"`
}

type GetCacheIDAndKeyByUserAndKeyRow struct {
	ID  string `json:"id"`
	Key string `json:"key"`
}

func (q *Queries) GetCacheIDAndKeyByUserAndKey(ctx context.Context, arg GetCacheIDAndKeyByUserAndKeyParams) (GetCacheIDAndKeyByUserAndKeyRow, error) {
	row := q.db.QueryRow(ctx, GetCacheIDAndKeyByUserAndKey, arg.Key, arg.UserId)
	var i GetCacheIDAndKeyByUserAndKeyRow
	err := row.Scan(&i.ID, &i.Key)
	return i, err
}

const GetCacheStats = `-- name: GetCacheStats :one
SELECT
    COUNT(*) as total_entries,
    COUNT(*) FILTER (WHERE "expiresAt" < NOW()) as expired_entries,
    COUNT(DISTINCT "userId") as unique_users,
    COUNT(DISTINCT feature) as feature_count
FROM analysis_cache
`

type GetCacheStatsRow struct {
	TotalEntries   int64 `json:"total_entries"`
	ExpiredEntries int64 `json:"expired_entries"`
	UniqueUsers    int64 `json:"unique_users"`
	FeatureCount   int64 `json:"feature_count"`
}

func (q *Queries) GetCacheStats(ctx context.Context) (GetCacheStatsRow, error) {
	row := q.db.QueryRow(ctx, GetCacheStats)
	var i GetCacheStatsRow
	err := row.Scan(
		&i.TotalEntries,
		&i.ExpiredEntries,
		&i.UniqueUsers,
		&i.FeatureCount,
	)
	return i, err
}

const GetLatestMarketAnalysisByLocation = `-- name: GetLatestMarketAnalysisByLocation :one
SELECT content, "metricsData", "narrativeData", "lastAccessedAt"
FROM analysis_cache
WHERE "userId" = $1
    AND feature = 'dual_agent_market_analysis'
    AND location ILIKE $2
    AND "supersededBy" IS NULL
ORDER BY "lastAccessedAt" DESC
LIMIT 1
`

type GetLatestMarketAnalysisByLocationParams struct {
	UserId   string `json:"userId"`
	Location string `json:"location"`
}

type GetLatestMarketAnalysisByLocationRow struct {
	Content        string           `json:"content"`
	MetricsData    []byte           `json:"metricsData"`
	NarrativeData  []byte           `json:"narrativeData"`
	LastAccessedAt pgtype.Timestamp `json:"lastAccessedAt"`
}

func (q *Queries) GetLatestMarketAnalysisByLocation(ctx context.Context, arg GetLatestMarketAnalysisByLocationParams) (GetLatestMarketAnalysisByLocationRow, error) {
	row := q.db.QueryRow(ctx, GetLatestMarketAnalysisByLocation, arg.UserId, arg.Location)
	var i GetLatestMarketAnalysisByLocationRow
	err := row.Scan(
		&i.Content,
		&i.MetricsData,
		&i.NarrativeData,
		&i.LastAccessedAt,
	)
	return i, err
}

const ListCacheByFeature = `-- name: ListCacheByFeature :many
SELECT id, key, "userId", location, feature, prompt, "promptHash", complexity, "investorProfile", "marketData", content, "fullReport", "metricsData", "narrativeData", metadata, "createdAt", "expiresAt", "lastAccessedAt", "accessCount", "supersededBy", "supersededAt", "cacheHits", "generationCost", "savingsGenerated" FROM analysis_cache
WHERE feature = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListCacheByFeatureParams struct {
	Feature string `json:"feature"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListCacheByFeature(ctx context.Context, arg ListCacheByFeatureParams) ([]AnalysisCache, error) {
	rows, err := q.db.Query(ctx, ListCacheByFeature, arg.Feature, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalysisCache{}
	for rows.Next() {
		var i AnalysisCache
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserId,
			&i.Location,
			&i.Feature,
			&i.Prompt,
			&i.PromptHash,
			&i.Complexity,
			&i.InvestorProfile,
			&i.MarketData,
			&i.Content,
			&i.FullReport,
			&i.MetricsData,
			&i.NarrativeData,
			&i.Metadata,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.SupersededBy,
			&i.SupersededAt,
			&i.CacheHits,
			&i.GenerationCost,
			&i.SavingsGenerated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCacheByLocation = `-- name: ListCacheByLocation :many
SELECT id, key, "userId", location, feature, prompt, "promptHash", complexity, "investorProfile", "marketData", content, "fullReport", "metricsData", "narrativeData", metadata, "createdAt", "expiresAt", "lastAccessedAt", "accessCount", "supersededBy", "supersededAt", "cacheHits", "generationCost", "savingsGenerated" FROM analysis_cache
WHERE location = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListCacheByLocationParams struct {
	Location string `json:"location"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListCacheByLocation(ctx context.Context, arg ListCacheByLocationParams) ([]AnalysisCache, error) {
	rows, err := q.db.Query(ctx, ListCacheByLocation, arg.Location, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalysisCache{}
	for rows.Next() {
		var i AnalysisCache
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserId,
			&i.Location,
			&i.Feature,
			&i.Prompt,
			&i.PromptHash,
			&i.Complexity,
			&i.InvestorProfile,
			&i.MarketData,
			&i.Content,
			&i.FullReport,
			&i.MetricsData,
			&i.NarrativeData,
			&i.Metadata,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.SupersededBy,
			&i.SupersededAt,
			&i.CacheHits,
			&i.GenerationCost,
			&i.SavingsGenerated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCacheByUser = `-- name: ListCacheByUser :many
SELECT id, key, "userId", location, feature, prompt, "promptHash", complexity, "investorProfile", "marketData", content, "fullReport", "metricsData", "narrativeData", metadata, "createdAt", "expiresAt", "lastAccessedAt", "accessCount", "supersededBy", "supersededAt", "cacheHits", "generationCost", "savingsGenerated" FROM analysis_cache
WHERE "userId" = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListCacheByUserParams struct {
	UserId string `json:"userId"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListCacheByUser(ctx context.Context, arg ListCacheByUserParams) ([]AnalysisCache, error) {
	rows, err := q.db.Query(ctx, ListCacheByUser, arg.UserId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalysisCache{}
	for rows.Next() {
		var i AnalysisCache
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserId,
			&i.Location,
			&i.Feature,
			&i.Prompt,
			&i.PromptHash,
			&i.Complexity,
			&i.InvestorProfile,
			&i.MarketData,
			&i.Content,
			&i.FullReport,
			&i.MetricsData,
			&i.NarrativeData,
			&i.Metadata,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.SupersededBy,
			&i.SupersededAt,
			&i.CacheHits,
			&i.GenerationCost,
			&i.SavingsGenerated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCacheByUserAndFeature = `-- name: ListCacheByUserAndFeature :many
SELECT id, key, "userId", location, feature, prompt, "promptHash", complexity, "investorProfile", "marketData", content, "fullReport", "metricsData", "narrativeData", metadata, "createdAt", "expiresAt", "lastAccessedAt", "accessCount", "supersededBy", "supersededAt", "cacheHits", "generationCost", "savingsGenerated" FROM analysis_cache
WHERE "userId" = $1 AND feature = $2 AND "expiresAt" > NOW()
ORDER BY "lastAccessedAt" DESC
LIMIT $3 OFFSET $4
`

type ListCacheByUserAndFeatureParams struct {
	UserId  string `json:"userId"`
	Feature string `json:"feature"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListCacheByUserAndFeature(ctx context.Context, arg ListCacheByUserAndFeatureParams) ([]AnalysisCache, error) {
	rows, err := q.db.Query(ctx, ListCacheByUserAndFeature,
		arg.UserId,
		arg.Feature,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalysisCache{}
	for rows.Next() {
		var i AnalysisCache
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserId,
			&i.Location,
			&i.Feature,
			&i.Prompt,
			&i.PromptHash,
			&i.Complexity,
			&i.InvestorProfile,
			&i.MarketData,
			&i.Content,
			&i.FullReport,
			&i.MetricsData,
			&i.NarrativeData,
			&i.Metadata,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.SupersededBy,
			&i.SupersededAt,
			&i.CacheHits,
			&i.GenerationCost,
			&i.SavingsGenerated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCacheByUserFeatureActive = `-- name: ListCacheByUserFeatureActive :many
SELECT id, key, location, content, "lastAccessedAt"
FROM analysis_cache
WHERE "userId" = $1 AND feature = $2
    AND "supersededBy" IS NULL AND "expiresAt" > NOW()
ORDER BY "lastAccessedAt" DESC
LIMIT $3 OFFSET $4
`

type ListCacheByUserFeatureActiveParams struct {
	UserId  string `json:"userId"`
	Feature string `json:"feature"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListCacheByUserFeatureActiveRow struct {
	ID             string           `json:"id"`
	Key            string           `json:"key"`
	Location       string           `json:"location"`
	Content        string           `json:"content"`
	LastAccessedAt pgtype.Timestamp `json:"lastAccessedAt"`
}

func (q *Queries) ListCacheByUserFeatureActive(ctx context.Context, arg ListCacheByUserFeatureActiveParams) ([]ListCacheByUserFeatureActiveRow, error) {
	rows, err := q.db.Query(ctx, ListCacheByUserFeatureActive,
		arg.UserId,
		arg.Feature,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCacheByUserFeatureActiveRow{}
	for rows.Next() {
		var i ListCacheByUserFeatureActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Location,
			&i.Content,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListInvestmentPlanHistory = `-- name: ListInvestmentPlanHistory :many
SELECT
    id, key, "userId", location, metadata, "metricsData", "investorProfile", "lastAccessedAt"
FROM analysis_cache
WHERE "userId" = $1
    AND feature = 'investment_planning'
    AND "supersededBy" IS NULL
    AND ($2::text IS NULL OR $2 = '' OR location ILIKE '%' || $2 || '%')
ORDER BY "lastAccessedAt" DESC
LIMIT $4 OFFSET $3
`

type ListInvestmentPlanHistoryParams struct {
	UserId string      `json:"userId"`
	Search pgtype.Text `json:"search"`
	Off    int32       `json:"off"`
	Lim    int32       `json:"lim"`
}

type ListInvestmentPlanHistoryRow struct {
	ID              string           `json:"id"`
	Key             string           `json:"key"`
	UserId          string           `json:"userId"`
	Location        string           `json:"location"`
	Metadata        json.RawMessage  `json:"metadata"`
	MetricsData     []byte           `json:"metricsData"`
	InvestorProfile []byte           `json:"investorProfile"`
	LastAccessedAt  pgtype.Timestamp `json:"lastAccessedAt"`
}

func (q *Queries) ListInvestmentPlanHistory(ctx context.Context, arg ListInvestmentPlanHistoryParams) ([]ListInvestmentPlanHistoryRow, error) {
	rows, err := q.db.Query(ctx, ListInvestmentPlanHistory,
		arg.UserId,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvestmentPlanHistoryRow{}
	for rows.Next() {
		var i ListInvestmentPlanHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserId,
			&i.Location,
			&i.Metadata,
			&i.MetricsData,
			&i.InvestorProfile,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMarketAnalysisHistory = `-- name: ListMarketAnalysisHistory :many
SELECT
    id, key, location, content, "metricsData", "narrativeData", "lastAccessedAt", "fullReport"
FROM analysis_cache
WHERE "userId" = $1
    AND feature IN ('dual_agent_market_analysis', 'market_analysis_v2')
    AND "supersededBy" IS NULL
    AND ($2::text IS NULL OR $2 = '' OR location ILIKE '%' || $2 || '%')
ORDER BY "lastAccessedAt" DESC
LIMIT $4 OFFSET $3
`

type ListMarketAnalysisHistoryParams struct {
	UserId string      `json:"userId"`
	Search pgtype.Text `json:"search"`
	Off    int32       `json:"off"`
	Lim    int32       `json:"lim"`
}

type ListMarketAnalysisHistoryRow struct {
	ID             string           `json:"id"`
	Key            string           `json:"key"`
	Location       string           `json:"location"`
	Content        string           `json:"content"`
	MetricsData    []byte           `json:"metricsData"`
	NarrativeData  []byte           `json:"narrativeData"`
	LastAccessedAt pgtype.Timestamp `json:"lastAccessedAt"`
	FullReport     pgtype.Text      `json:"fullReport"`
}

func (q *Queries) ListMarketAnalysisHistory(ctx context.Context, arg ListMarketAnalysisHistoryParams) ([]ListMarketAnalysisHistoryRow, error) {
	rows, err := q.db.Query(ctx, ListMarketAnalysisHistory,
		arg.UserId,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketAnalysisHistoryRow{}
	for rows.Next() {
		var i ListMarketAnalysisHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Location,
			&i.Content,
			&i.MetricsData,
			&i.NarrativeData,
			&i.LastAccessedAt,
			&i.FullReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTrendsHistory = `-- name: ListTrendsHistory :many

SELECT id, key, location, content, "lastAccessedAt"
FROM analysis_cache
WHERE "userId" = $1
    AND feature = 'market_trends'
    AND "supersededBy" IS NULL
    AND "expiresAt" > NOW()
ORDER BY "lastAccessedAt" DESC
LIMIT $2 OFFSET $3
`

type ListTrendsHistoryParams struct {
	UserId string `json:"userId"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListTrendsHistoryRow struct {
	ID             string           `json:"id"`
	Key            string           `json:"key"`
	Location       string           `json:"location"`
	Content        string           `json:"content"`
	LastAccessedAt pgtype.Timestamp `json:"lastAccessedAt"`
}

// Market Trends queries (ADR-083 Phase R2)
func (q *Queries) ListTrendsHistory(ctx context.Context, arg ListTrendsHistoryParams) ([]ListTrendsHistoryRow, error) {
	rows, err := q.db.Query(ctx, ListTrendsHistory, arg.UserId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrendsHistoryRow{}
	for rows.Next() {
		var i ListTrendsHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Location,
			&i.Content,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateCacheAccess = `-- name: UpdateCacheAccess :exec
UPDATE analysis_cache
SET "lastAccessedAt" = NOW(), "accessCount" = "accessCount" + 1
WHERE key = $1
`

func (q *Queries) UpdateCacheAccess(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, UpdateCacheAccess, key)
	return err
}

const UpdateCacheAccessByUserAndKey = `-- name: UpdateCacheAccessByUserAndKey :exec
UPDATE analysis_cache
SET "lastAccessedAt" = NOW(), "accessCount" = "accessCount" + 1
WHERE "userId" = $1 AND key = $2
`

type UpdateCacheAccessByUserAndKeyParams struct {
	UserId string `json:"userId"`
	Key    string `json:"key"`
}

func (q *Queries) UpdateCacheAccessByUserAndKey(ctx context.Context, arg UpdateCacheAccessByUserAndKeyParams) error {
	_, err := q.db.Exec(ctx, UpdateCacheAccessByUserAndKey, arg.UserId, arg.Key)
	return err
}

const UpdateTrendLastAccessed = `-- name: UpdateTrendLastAccessed :exec
UPDATE analysis_cache
SET "lastAccessedAt" = NOW()
WHERE key = $1 AND feature = 'market_trends'
`

func (q *Queries) UpdateTrendLastAccessed(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, UpdateTrendLastAccessed, key)
	return err
}

const UpsertAnalysisReport = `-- name: UpsertAnalysisReport :one
INSERT INTO analysis_cache (
    id, key, "userId", location, feature, content, "fullReport",
    "metricsData", "narrativeData", metadata,
    "expiresAt", "createdAt", "lastAccessedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW()
)
ON CONFLICT (key) DO UPDATE SET
    content = EXCLUDED.content,
    "fullReport" = EXCLUDED."fullReport",
    feature = EXCLUDED.feature,
    "metricsData" = EXCLUDED."metricsData",
    "narrativeData" = EXCLUDED."narrativeData",
    metadata = EXCLUDED.metadata,
    "expiresAt" = EXCLUDED."expiresAt",
    "lastAccessedAt" = NOW()
RETURNING id, key, "userId", location, feature, prompt, "promptHash", complexity, "investorProfile", "marketData", content, "fullReport", "metricsData", "narrativeData", metadata, "createdAt", "expiresAt", "lastAccessedAt", "accessCount", "supersededBy", "supersededAt", "cacheHits", "generationCost", "savingsGenerated"
`

type UpsertAnalysisReportParams struct {
	ID            string           `json:"id"`
	Key           string           `json:"key"`
	UserId        string           `json:"userId"`
	Location      string           `json:"location"`
	Feature       string           `json:"feature"`
	Content       string           `json:"content"`
	FullReport    pgtype.Text      `json:"fullReport"`
	MetricsData   []byte           `json:"metricsData"`
	NarrativeData []byte           `json:"narrativeData"`
	Metadata      json.RawMessage  `json:"metadata"`
	ExpiresAt     pgtype.Timestamp `json:"expiresAt"`
}

// ADR-074: Upsert analysis report with fullReport column for V2 markdown reports
func (q *Queries) UpsertAnalysisReport(ctx context.Context, arg UpsertAnalysisReportParams) (AnalysisCache, error) {
	row := q.db.QueryRow(ctx, UpsertAnalysisReport,
		arg.ID,
		arg.Key,
		arg.UserId,
		arg.Location,
		arg.Feature,
		arg.Content,
		arg.FullReport,
		arg.MetricsData,
		arg.NarrativeData,
		arg.Metadata,
		arg.ExpiresAt,
	)
	var i AnalysisCache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserId,
		&i.Location,
		&i.Feature,
		&i.Prompt,
		&i.PromptHash,
		&i.Complexity,
		&i.InvestorProfile,
		&i.MarketData,
		&i.Content,
		&i.FullReport,
		&i.MetricsData,
		&i.NarrativeData,
		&i.Metadata,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.CacheHits,
		&i.GenerationCost,
		&i.SavingsGenerated,
	)
	return i, err
}

const UpsertCache = `-- name: UpsertCache :one
INSERT INTO analysis_cache (
    id, key, "userId", location, feature, content,
    "metricsData", "narrativeData", metadata,
    "expiresAt", "createdAt", "lastAccessedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW()
)
ON CONFLICT (key) DO UPDATE SET
    content = EXCLUDED.content,
    feature = EXCLUDED.feature,
    "metricsData" = EXCLUDED."metricsData",
    "narrativeData" = EXCLUDED."narrativeData",
    metadata = EXCLUDED.metadata,
    "expiresAt" = EXCLUDED."expiresAt",
    "lastAccessedAt" = NOW()
RETURNING id, key, "userId", location, feature, prompt, "promptHash", complexity, "investorProfile", "marketData", content, "fullReport", "metricsData", "narrativeData", metadata, "createdAt", "expiresAt", "lastAccessedAt", "accessCount", "supersededBy", "supersededAt", "cacheHits", "generationCost", "savingsGenerated"
`

type UpsertCacheParams struct {
	ID            string           `json:"id"`
	Key           string           `json:"key"`
	UserId        string           `json:"userId"`
	Location      string           `json:"location"`
	Feature       string           `json:"feature"`
	Content       string           `json:"content"`
	MetricsData   []byte           `json:"metricsData"`
	NarrativeData []byte           `json:"narrativeData"`
	Metadata      json.RawMessage  `json:"metadata"`
	ExpiresAt     pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) UpsertCache(ctx context.Context, arg UpsertCacheParams) (AnalysisCache, error) {
	row := q.db.QueryRow(ctx, UpsertCache,
		arg.ID,
		arg.Key,
		arg.UserId,
		arg.Location,
		arg.Feature,
		arg.Content,
		arg.MetricsData,
		arg.NarrativeData,
		arg.Metadata,
		arg.ExpiresAt,
	)
	var i AnalysisCache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserId,
		&i.Location,
		&i.Feature,
		&i.Prompt,
		&i.PromptHash,
		&i.Complexity,
		&i.InvestorProfile,
		&i.MarketData,
		&i.Content,
		&i.FullReport,
		&i.MetricsData,
		&i.NarrativeData,
		&i.Metadata,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.CacheHits,
		&i.GenerationCost,
		&i.SavingsGenerated,
	)
	return i, err
}

const UpsertTrendCache = `-- name: UpsertTrendCache :exec
INSERT INTO analysis_cache (
    id, key, "userId", location, feature, content, "createdAt", "expiresAt", "lastAccessedAt"
)
VALUES ($1, $2, $3, $4, 'market_trends', $5, $6, $7, $6)
ON CONFLICT (key) DO UPDATE
SET content = EXCLUDED.content,
    "lastAccessedAt" = NOW()
`

type UpsertTrendCacheParams struct {
	ID        string           `json:"id"`
	Key       string           `json:"key"`
	UserId    string           `json:"userId"`
	Location  string           `json:"location"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) UpsertTrendCache(ctx context.Context, arg UpsertTrendCacheParams) error {
	_, err := q.db.Exec(ctx, UpsertTrendCache,
		arg.ID,
		arg.Key,
		arg.UserId,
		arg.Location,
		arg.Content,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
