// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compliance.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CountUserConsents = `-- name: CountUserConsents :one
SELECT COUNT(*) FROM user_consents
`

func (q *Queries) CountUserConsents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountUserConsents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountUserConsentsByType = `-- name: CountUserConsentsByType :one
SELECT COUNT(*) FROM user_consents WHERE consent_type = $1
`

func (q *Queries) CountUserConsentsByType(ctx context.Context, consentType string) (int64, error) {
	row := q.db.QueryRow(ctx, CountUserConsentsByType, consentType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateUserConsent = `-- name: CreateUserConsent :one
INSERT INTO user_consents (
    user_id, consent_type, version, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, consent_type, version, granted_at, revoked_at, ip_address, user_agent, created_at
`

type CreateUserConsentParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	ConsentType string      `json:"consent_type"`
	Version     string      `json:"version"`
	IpAddress   pgtype.Text `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateUserConsent(ctx context.Context, arg CreateUserConsentParams) (UserConsent, error) {
	row := q.db.QueryRow(ctx, CreateUserConsent,
		arg.UserID,
		arg.ConsentType,
		arg.Version,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i UserConsent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConsentType,
		&i.Version,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const GetConsentSummary = `-- name: GetConsentSummary :many
SELECT
    consent_type,
    COUNT(*) FILTER (WHERE revoked_at IS NULL) as active_count,
    COUNT(*) FILTER (WHERE revoked_at IS NOT NULL) as revoked_count,
    COUNT(*) as total_count
FROM user_consents
GROUP BY consent_type
ORDER BY consent_type
`

type GetConsentSummaryRow struct {
	ConsentType  string `json:"consent_type"`
	ActiveCount  int64  `json:"active_count"`
	RevokedCount int64  `json:"revoked_count"`
	TotalCount   int64  `json:"total_count"`
}

func (q *Queries) GetConsentSummary(ctx context.Context) ([]GetConsentSummaryRow, error) {
	rows, err := q.db.Query(ctx, GetConsentSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConsentSummaryRow{}
	for rows.Next() {
		var i GetConsentSummaryRow
		if err := rows.Scan(
			&i.ConsentType,
			&i.ActiveCount,
			&i.RevokedCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserConsent = `-- name: GetUserConsent :one
SELECT id, user_id, consent_type, version, granted_at, revoked_at, ip_address, user_agent, created_at FROM user_consents
WHERE user_id = $1 AND consent_type = $2 AND revoked_at IS NULL
`

type GetUserConsentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ConsentType string    `json:"consent_type"`
}

func (q *Queries) GetUserConsent(ctx context.Context, arg GetUserConsentParams) (UserConsent, error) {
	row := q.db.QueryRow(ctx, GetUserConsent, arg.UserID, arg.ConsentType)
	var i UserConsent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConsentType,
		&i.Version,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const ListUserConsents = `-- name: ListUserConsents :many

SELECT id, user_id, consent_type, version, granted_at, revoked_at, ip_address, user_agent, created_at FROM user_consents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUserConsentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Compliance Queries
func (q *Queries) ListUserConsents(ctx context.Context, arg ListUserConsentsParams) ([]UserConsent, error) {
	rows, err := q.db.Query(ctx, ListUserConsents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserConsent{}
	for rows.Next() {
		var i UserConsent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConsentType,
			&i.Version,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUserConsentsByType = `-- name: ListUserConsentsByType :many
SELECT id, user_id, consent_type, version, granted_at, revoked_at, ip_address, user_agent, created_at FROM user_consents
WHERE consent_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserConsentsByTypeParams struct {
	ConsentType string `json:"consent_type"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListUserConsentsByType(ctx context.Context, arg ListUserConsentsByTypeParams) ([]UserConsent, error) {
	rows, err := q.db.Query(ctx, ListUserConsentsByType, arg.ConsentType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserConsent{}
	for rows.Next() {
		var i UserConsent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConsentType,
			&i.Version,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RevokeUserConsent = `-- name: RevokeUserConsent :exec
UPDATE user_consents SET revoked_at = NOW()
WHERE user_id = $1 AND consent_type = $2 AND revoked_at IS NULL
`

type RevokeUserConsentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ConsentType string    `json:"consent_type"`
}

func (q *Queries) RevokeUserConsent(ctx context.Context, arg RevokeUserConsentParams) error {
	_, err := q.db.Exec(ctx, RevokeUserConsent, arg.UserID, arg.ConsentType)
	return err
}
