// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const ArchiveDiscoverySession = `-- name: ArchiveDiscoverySession :one
UPDATE discovery_sessions SET
    status = 'ARCHIVED',
    "archivedAt" = NOW(),
    "updatedAt" = NOW()
WHERE id = $1 AND "userId" = $2
RETURNING id, "userId", "searchCriteria", location, "propertyCount", "cachedPropertyIds", name, notes, status, "createdAt", "updatedAt", "lastAccessedAt", "archivedAt", "expiresAt", "chatSessionCount", "evaluationCount"
`

type ArchiveDiscoverySessionParams struct {
	ID     string `json:"id"`
	UserId string `json:"userId"`
}

func (q *Queries) ArchiveDiscoverySession(ctx context.Context, arg ArchiveDiscoverySessionParams) (DiscoverySession, error) {
	row := q.db.QueryRow(ctx, ArchiveDiscoverySession, arg.ID, arg.UserId)
	var i DiscoverySession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.SearchCriteria,
		&i.Location,
		&i.PropertyCount,
		&i.CachedPropertyIds,
		&i.Name,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.ChatSessionCount,
		&i.EvaluationCount,
	)
	return i, err
}

const AutoArchiveOldSessions = `-- name: AutoArchiveOldSessions :exec
UPDATE discovery_sessions SET
    status = 'ARCHIVED',
    "archivedAt" = NOW(),
    "updatedAt" = NOW()
WHERE status = 'ACTIVE'
  AND "createdAt" < NOW() - INTERVAL '30 days'
`

func (q *Queries) AutoArchiveOldSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, AutoArchiveOldSessions)
	return err
}

const CountSessionActivitiesByType = `-- name: CountSessionActivitiesByType :one
SELECT COUNT(*) FROM discovery_session_activities
WHERE "discoverySessionId" = $1 AND "activityType" = $2
`

type CountSessionActivitiesByTypeParams struct {
	DiscoverySessionId string `json:"discoverySessionId"`
	ActivityType       string `json:"activityType"`
}

func (q *Queries) CountSessionActivitiesByType(ctx context.Context, arg CountSessionActivitiesByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountSessionActivitiesByType, arg.DiscoverySessionId, arg.ActivityType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountSessionEvaluations = `-- name: CountSessionEvaluations :one
SELECT COUNT(*) FROM discovery_session_evaluations
WHERE "discoverySessionId" = $1
`

func (q *Queries) CountSessionEvaluations(ctx context.Context, discoverysessionid string) (int64, error) {
	row := q.db.QueryRow(ctx, CountSessionEvaluations, discoverysessionid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountSessionProperties = `-- name: CountSessionProperties :one
SELECT COUNT(*) FROM discovery_session_properties
WHERE "discoverySessionId" = $1
`

func (q *Queries) CountSessionProperties(ctx context.Context, discoverysessionid string) (int64, error) {
	row := q.db.QueryRow(ctx, CountSessionProperties, discoverysessionid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountUserDiscoverySessions = `-- name: CountUserDiscoverySessions :one
SELECT COUNT(*) FROM discovery_sessions
WHERE "userId" = $1 AND status = $2
`

type CountUserDiscoverySessionsParams struct {
	UserId string `json:"userId"`
	Status string `json:"status"`
}

func (q *Queries) CountUserDiscoverySessions(ctx context.Context, arg CountUserDiscoverySessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountUserDiscoverySessions, arg.UserId, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateActivityLink = `-- name: CreateActivityLink :one

INSERT INTO discovery_session_activities (
    id, "discoverySessionId", "activityType", "activityId", "createdAt"
) VALUES (
    $1, $2, $3, $4, NOW()
)
ON CONFLICT ("discoverySessionId", "activityType", "activityId") DO NOTHING
RETURNING id, "discoverySessionId", "activityType", "activityId", "createdAt"
`

type CreateActivityLinkParams struct {
	ID                 string `json:"id"`
	DiscoverySessionId string `json:"discoverySessionId"`
	ActivityType       string `json:"activityType"`
	ActivityId         string `json:"activityId"`
}

// Activity Linking Queries
func (q *Queries) CreateActivityLink(ctx context.Context, arg CreateActivityLinkParams) (DiscoverySessionActivity, error) {
	row := q.db.QueryRow(ctx, CreateActivityLink,
		arg.ID,
		arg.DiscoverySessionId,
		arg.ActivityType,
		arg.ActivityId,
	)
	var i DiscoverySessionActivity
	err := row.Scan(
		&i.ID,
		&i.DiscoverySessionId,
		&i.ActivityType,
		&i.ActivityId,
		&i.CreatedAt,
	)
	return i, err
}

const CreateDiscoverySession = `-- name: CreateDiscoverySession :one

INSERT INTO discovery_sessions (
    id, "userId", "searchCriteria", location, "propertyCount",
    "cachedPropertyIds", status, "createdAt", "updatedAt", "lastAccessedAt", "expiresAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, 'ACTIVE', NOW(), NOW(), NOW(), NOW() + INTERVAL '180 days'
) RETURNING id, "userId", "searchCriteria", location, "propertyCount", "cachedPropertyIds", name, notes, status, "createdAt", "updatedAt", "lastAccessedAt", "archivedAt", "expiresAt", "chatSessionCount", "evaluationCount"
`

type CreateDiscoverySessionParams struct {
	ID                string          `json:"id"`
	UserId            string          `json:"userId"`
	SearchCriteria    json.RawMessage `json:"searchCriteria"`
	Location          string          `json:"location"`
	PropertyCount     int32           `json:"propertyCount"`
	CachedPropertyIds []string        `json:"cachedPropertyIds"`
}

// Discovery Session Queries
func (q *Queries) CreateDiscoverySession(ctx context.Context, arg CreateDiscoverySessionParams) (DiscoverySession, error) {
	row := q.db.QueryRow(ctx, CreateDiscoverySession,
		arg.ID,
		arg.UserId,
		arg.SearchCriteria,
		arg.Location,
		arg.PropertyCount,
		arg.CachedPropertyIds,
	)
	var i DiscoverySession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.SearchCriteria,
		&i.Location,
		&i.PropertyCount,
		&i.CachedPropertyIds,
		&i.Name,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.ChatSessionCount,
		&i.EvaluationCount,
	)
	return i, err
}

const CreateDiscoverySessionEvaluation = `-- name: CreateDiscoverySessionEvaluation :one

INSERT INTO discovery_session_evaluations (
    id, "discoverySessionId", "propertyId", address, price, "estimatedRent",
    scenarios, recommendation, "riskLevel", score, status, "createdAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW()
)
ON CONFLICT ("discoverySessionId", "propertyId") DO UPDATE SET
    scenarios = EXCLUDED.scenarios,
    recommendation = EXCLUDED.recommendation,
    "riskLevel" = EXCLUDED."riskLevel",
    score = EXCLUDED.score,
    status = EXCLUDED.status
RETURNING id, "discoverySessionId", "propertyId", address, price, "estimatedRent", scenarios, recommendation, "riskLevel", score, status, "createdAt"
`

type CreateDiscoverySessionEvaluationParams struct {
	ID                 string          `json:"id"`
	DiscoverySessionId string          `json:"discoverySessionId"`
	PropertyId         string          `json:"propertyId"`
	Address            string          `json:"address"`
	Price              int32           `json:"price"`
	EstimatedRent      pgtype.Int4     `json:"estimatedRent"`
	Scenarios          json.RawMessage `json:"scenarios"`
	Recommendation     pgtype.Text     `json:"recommendation"`
	RiskLevel          pgtype.Text     `json:"riskLevel"`
	Score              pgtype.Int4     `json:"score"`
	Status             string          `json:"status"`
}

// Discovery Session Evaluations Queries
func (q *Queries) CreateDiscoverySessionEvaluation(ctx context.Context, arg CreateDiscoverySessionEvaluationParams) (DiscoverySessionEvaluation, error) {
	row := q.db.QueryRow(ctx, CreateDiscoverySessionEvaluation,
		arg.ID,
		arg.DiscoverySessionId,
		arg.PropertyId,
		arg.Address,
		arg.Price,
		arg.EstimatedRent,
		arg.Scenarios,
		arg.Recommendation,
		arg.RiskLevel,
		arg.Score,
		arg.Status,
	)
	var i DiscoverySessionEvaluation
	err := row.Scan(
		&i.ID,
		&i.DiscoverySessionId,
		&i.PropertyId,
		&i.Address,
		&i.Price,
		&i.EstimatedRent,
		&i.Scenarios,
		&i.Recommendation,
		&i.RiskLevel,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const CreateDiscoverySessionProperty = `-- name: CreateDiscoverySessionProperty :one

INSERT INTO discovery_session_properties (
    id, "discoverySessionId", "listingId", address, city, state, "zipCode",
    price, "estimatedRent", "capRateMin", "capRateMax", beds, baths, sqft,
    "yearBuilt", "propertyType", "listingDate", "daysOnMarket", "imageUrl",
    "listingSearchUrl", "googleSearchUrl", latitude, longitude, "createdAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, NOW()
)
ON CONFLICT ("discoverySessionId", "listingId") DO NOTHING
RETURNING id, "discoverySessionId", "listingId", address, city, state, "zipCode", price, "estimatedRent", "capRateMin", "capRateMax", beds, baths, sqft, "yearBuilt", "propertyType", "listingDate", "daysOnMarket", "imageUrl", "listingSearchUrl", "googleSearchUrl", latitude, longitude, "createdAt"
`

type CreateDiscoverySessionPropertyParams struct {
	ID                 string         `json:"id"`
	DiscoverySessionId string         `json:"discoverySessionId"`
	ListingId          string         `json:"listingId"`
	Address            string         `json:"address"`
	City               string         `json:"city"`
	State              string         `json:"state"`
	ZipCode            pgtype.Text    `json:"zipCode"`
	Price              int32          `json:"price"`
	EstimatedRent      pgtype.Int4    `json:"estimatedRent"`
	CapRateMin         pgtype.Numeric `json:"capRateMin"`
	CapRateMax         pgtype.Numeric `json:"capRateMax"`
	Beds               int32          `json:"beds"`
	Baths              pgtype.Numeric `json:"baths"`
	Sqft               pgtype.Int4    `json:"sqft"`
	YearBuilt          pgtype.Int4    `json:"yearBuilt"`
	PropertyType       pgtype.Text    `json:"propertyType"`
	ListingDate        pgtype.Text    `json:"listingDate"`
	DaysOnMarket       pgtype.Int4    `json:"daysOnMarket"`
	ImageUrl           pgtype.Text    `json:"imageUrl"`
	ListingSearchUrl   pgtype.Text    `json:"listingSearchUrl"`
	GoogleSearchUrl    pgtype.Text    `json:"googleSearchUrl"`
	Latitude           pgtype.Numeric `json:"latitude"`
	Longitude          pgtype.Numeric `json:"longitude"`
}

// Discovery Session Properties Queries
func (q *Queries) CreateDiscoverySessionProperty(ctx context.Context, arg CreateDiscoverySessionPropertyParams) (DiscoverySessionProperty, error) {
	row := q.db.QueryRow(ctx, CreateDiscoverySessionProperty,
		arg.ID,
		arg.DiscoverySessionId,
		arg.ListingId,
		arg.Address,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Price,
		arg.EstimatedRent,
		arg.CapRateMin,
		arg.CapRateMax,
		arg.Beds,
		arg.Baths,
		arg.Sqft,
		arg.YearBuilt,
		arg.PropertyType,
		arg.ListingDate,
		arg.DaysOnMarket,
		arg.ImageUrl,
		arg.ListingSearchUrl,
		arg.GoogleSearchUrl,
		arg.Latitude,
		arg.Longitude,
	)
	var i DiscoverySessionProperty
	err := row.Scan(
		&i.ID,
		&i.DiscoverySessionId,
		&i.ListingId,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Price,
		&i.EstimatedRent,
		&i.CapRateMin,
		&i.CapRateMax,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.YearBuilt,
		&i.PropertyType,
		&i.ListingDate,
		&i.DaysOnMarket,
		&i.ImageUrl,
		&i.ListingSearchUrl,
		&i.GoogleSearchUrl,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteActivityLink = `-- name: DeleteActivityLink :exec
DELETE FROM discovery_session_activities
WHERE "discoverySessionId" = $1 AND "activityType" = $2 AND "activityId" = $3
`

type DeleteActivityLinkParams struct {
	DiscoverySessionId string `json:"discoverySessionId"`
	ActivityType       string `json:"activityType"`
	ActivityId         string `json:"activityId"`
}

func (q *Queries) DeleteActivityLink(ctx context.Context, arg DeleteActivityLinkParams) error {
	_, err := q.db.Exec(ctx, DeleteActivityLink, arg.DiscoverySessionId, arg.ActivityType, arg.ActivityId)
	return err
}

const DeleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM discovery_sessions
WHERE "expiresAt" < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, DeleteExpiredSessions)
	return err
}

const DeleteSessionEvaluations = `-- name: DeleteSessionEvaluations :exec
DELETE FROM discovery_session_evaluations
WHERE "discoverySessionId" = $1
`

func (q *Queries) DeleteSessionEvaluations(ctx context.Context, discoverysessionid string) error {
	_, err := q.db.Exec(ctx, DeleteSessionEvaluations, discoverysessionid)
	return err
}

const DeleteSessionProperties = `-- name: DeleteSessionProperties :exec
DELETE FROM discovery_session_properties
WHERE "discoverySessionId" = $1
`

func (q *Queries) DeleteSessionProperties(ctx context.Context, discoverysessionid string) error {
	_, err := q.db.Exec(ctx, DeleteSessionProperties, discoverysessionid)
	return err
}

const GetActivityLink = `-- name: GetActivityLink :one
SELECT id, "discoverySessionId", "activityType", "activityId", "createdAt" FROM discovery_session_activities
WHERE "discoverySessionId" = $1 AND "activityType" = $2 AND "activityId" = $3
`

type GetActivityLinkParams struct {
	DiscoverySessionId string `json:"discoverySessionId"`
	ActivityType       string `json:"activityType"`
	ActivityId         string `json:"activityId"`
}

func (q *Queries) GetActivityLink(ctx context.Context, arg GetActivityLinkParams) (DiscoverySessionActivity, error) {
	row := q.db.QueryRow(ctx, GetActivityLink, arg.DiscoverySessionId, arg.ActivityType, arg.ActivityId)
	var i DiscoverySessionActivity
	err := row.Scan(
		&i.ID,
		&i.DiscoverySessionId,
		&i.ActivityType,
		&i.ActivityId,
		&i.CreatedAt,
	)
	return i, err
}

const GetDiscoverySession = `-- name: GetDiscoverySession :one
SELECT id, "userId", "searchCriteria", location, "propertyCount", "cachedPropertyIds", name, notes, status, "createdAt", "updatedAt", "lastAccessedAt", "archivedAt", "expiresAt", "chatSessionCount", "evaluationCount" FROM discovery_sessions WHERE id = $1
`

func (q *Queries) GetDiscoverySession(ctx context.Context, id string) (DiscoverySession, error) {
	row := q.db.QueryRow(ctx, GetDiscoverySession, id)
	var i DiscoverySession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.SearchCriteria,
		&i.Location,
		&i.PropertyCount,
		&i.CachedPropertyIds,
		&i.Name,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.ChatSessionCount,
		&i.EvaluationCount,
	)
	return i, err
}

const GetDiscoverySessionByUser = `-- name: GetDiscoverySessionByUser :one
SELECT id, "userId", "searchCriteria", location, "propertyCount", "cachedPropertyIds", name, notes, status, "createdAt", "updatedAt", "lastAccessedAt", "archivedAt", "expiresAt", "chatSessionCount", "evaluationCount" FROM discovery_sessions WHERE id = $1 AND "userId" = $2
`

type GetDiscoverySessionByUserParams struct {
	ID     string `json:"id"`
	UserId string `json:"userId"`
}

func (q *Queries) GetDiscoverySessionByUser(ctx context.Context, arg GetDiscoverySessionByUserParams) (DiscoverySession, error) {
	row := q.db.QueryRow(ctx, GetDiscoverySessionByUser, arg.ID, arg.UserId)
	var i DiscoverySession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.SearchCriteria,
		&i.Location,
		&i.PropertyCount,
		&i.CachedPropertyIds,
		&i.Name,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.ChatSessionCount,
		&i.EvaluationCount,
	)
	return i, err
}

const GetSessionEvaluation = `-- name: GetSessionEvaluation :one
SELECT id, "discoverySessionId", "propertyId", address, price, "estimatedRent", scenarios, recommendation, "riskLevel", score, status, "createdAt" FROM discovery_session_evaluations
WHERE "discoverySessionId" = $1 AND "propertyId" = $2
`

type GetSessionEvaluationParams struct {
	DiscoverySessionId string `json:"discoverySessionId"`
	PropertyId         string `json:"propertyId"`
}

func (q *Queries) GetSessionEvaluation(ctx context.Context, arg GetSessionEvaluationParams) (DiscoverySessionEvaluation, error) {
	row := q.db.QueryRow(ctx, GetSessionEvaluation, arg.DiscoverySessionId, arg.PropertyId)
	var i DiscoverySessionEvaluation
	err := row.Scan(
		&i.ID,
		&i.DiscoverySessionId,
		&i.PropertyId,
		&i.Address,
		&i.Price,
		&i.EstimatedRent,
		&i.Scenarios,
		&i.Recommendation,
		&i.RiskLevel,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const GetSessionProperty = `-- name: GetSessionProperty :one
SELECT id, "discoverySessionId", "listingId", address, city, state, "zipCode", price, "estimatedRent", "capRateMin", "capRateMax", beds, baths, sqft, "yearBuilt", "propertyType", "listingDate", "daysOnMarket", "imageUrl", "listingSearchUrl", "googleSearchUrl", latitude, longitude, "createdAt" FROM discovery_session_properties
WHERE "discoverySessionId" = $1 AND "listingId" = $2
`

type GetSessionPropertyParams struct {
	DiscoverySessionId string `json:"discoverySessionId"`
	ListingId          string `json:"listingId"`
}

func (q *Queries) GetSessionProperty(ctx context.Context, arg GetSessionPropertyParams) (DiscoverySessionProperty, error) {
	row := q.db.QueryRow(ctx, GetSessionProperty, arg.DiscoverySessionId, arg.ListingId)
	var i DiscoverySessionProperty
	err := row.Scan(
		&i.ID,
		&i.DiscoverySessionId,
		&i.ListingId,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Price,
		&i.EstimatedRent,
		&i.CapRateMin,
		&i.CapRateMax,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.YearBuilt,
		&i.PropertyType,
		&i.ListingDate,
		&i.DaysOnMarket,
		&i.ImageUrl,
		&i.ListingSearchUrl,
		&i.GoogleSearchUrl,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const IncrementChatSessionCount = `-- name: IncrementChatSessionCount :exec
UPDATE discovery_sessions SET
    "chatSessionCount" = "chatSessionCount" + 1,
    "updatedAt" = NOW()
WHERE id = $1
`

func (q *Queries) IncrementChatSessionCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, IncrementChatSessionCount, id)
	return err
}

const IncrementEvaluationCount = `-- name: IncrementEvaluationCount :exec
UPDATE discovery_sessions SET
    "evaluationCount" = "evaluationCount" + 1,
    "updatedAt" = NOW()
WHERE id = $1
`

func (q *Queries) IncrementEvaluationCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, IncrementEvaluationCount, id)
	return err
}

const ListSessionActivities = `-- name: ListSessionActivities :many
SELECT id, "discoverySessionId", "activityType", "activityId", "createdAt" FROM discovery_session_activities
WHERE "discoverySessionId" = $1
ORDER BY "createdAt" DESC
`

func (q *Queries) ListSessionActivities(ctx context.Context, discoverysessionid string) ([]DiscoverySessionActivity, error) {
	rows, err := q.db.Query(ctx, ListSessionActivities, discoverysessionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverySessionActivity{}
	for rows.Next() {
		var i DiscoverySessionActivity
		if err := rows.Scan(
			&i.ID,
			&i.DiscoverySessionId,
			&i.ActivityType,
			&i.ActivityId,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSessionEvaluations = `-- name: ListSessionEvaluations :many
SELECT id, "discoverySessionId", "propertyId", address, price, "estimatedRent", scenarios, recommendation, "riskLevel", score, status, "createdAt" FROM discovery_session_evaluations
WHERE "discoverySessionId" = $1
ORDER BY "createdAt" DESC
`

func (q *Queries) ListSessionEvaluations(ctx context.Context, discoverysessionid string) ([]DiscoverySessionEvaluation, error) {
	rows, err := q.db.Query(ctx, ListSessionEvaluations, discoverysessionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverySessionEvaluation{}
	for rows.Next() {
		var i DiscoverySessionEvaluation
		if err := rows.Scan(
			&i.ID,
			&i.DiscoverySessionId,
			&i.PropertyId,
			&i.Address,
			&i.Price,
			&i.EstimatedRent,
			&i.Scenarios,
			&i.Recommendation,
			&i.RiskLevel,
			&i.Score,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSessionProperties = `-- name: ListSessionProperties :many
SELECT id, "discoverySessionId", "listingId", address, city, state, "zipCode", price, "estimatedRent", "capRateMin", "capRateMax", beds, baths, sqft, "yearBuilt", "propertyType", "listingDate", "daysOnMarket", "imageUrl", "listingSearchUrl", "googleSearchUrl", latitude, longitude, "createdAt" FROM discovery_session_properties
WHERE "discoverySessionId" = $1
ORDER BY price ASC
`

func (q *Queries) ListSessionProperties(ctx context.Context, discoverysessionid string) ([]DiscoverySessionProperty, error) {
	rows, err := q.db.Query(ctx, ListSessionProperties, discoverysessionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverySessionProperty{}
	for rows.Next() {
		var i DiscoverySessionProperty
		if err := rows.Scan(
			&i.ID,
			&i.DiscoverySessionId,
			&i.ListingId,
			&i.Address,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.Price,
			&i.EstimatedRent,
			&i.CapRateMin,
			&i.CapRateMax,
			&i.Beds,
			&i.Baths,
			&i.Sqft,
			&i.YearBuilt,
			&i.PropertyType,
			&i.ListingDate,
			&i.DaysOnMarket,
			&i.ImageUrl,
			&i.ListingSearchUrl,
			&i.GoogleSearchUrl,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUserDiscoverySessions = `-- name: ListUserDiscoverySessions :many
SELECT id, "userId", "searchCriteria", location, "propertyCount", "cachedPropertyIds", name, notes, status, "createdAt", "updatedAt", "lastAccessedAt", "archivedAt", "expiresAt", "chatSessionCount", "evaluationCount" FROM discovery_sessions
WHERE "userId" = $1 AND status = $2
ORDER BY "lastAccessedAt" DESC
LIMIT $3 OFFSET $4
`

type ListUserDiscoverySessionsParams struct {
	UserId string `json:"userId"`
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListUserDiscoverySessions(ctx context.Context, arg ListUserDiscoverySessionsParams) ([]DiscoverySession, error) {
	rows, err := q.db.Query(ctx, ListUserDiscoverySessions,
		arg.UserId,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverySession{}
	for rows.Next() {
		var i DiscoverySession
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.SearchCriteria,
			&i.Location,
			&i.PropertyCount,
			&i.CachedPropertyIds,
			&i.Name,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.ArchivedAt,
			&i.ExpiresAt,
			&i.ChatSessionCount,
			&i.EvaluationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RestoreDiscoverySession = `-- name: RestoreDiscoverySession :one
UPDATE discovery_sessions SET
    status = 'ACTIVE',
    "archivedAt" = NULL,
    "updatedAt" = NOW()
WHERE id = $1 AND "userId" = $2
RETURNING id, "userId", "searchCriteria", location, "propertyCount", "cachedPropertyIds", name, notes, status, "createdAt", "updatedAt", "lastAccessedAt", "archivedAt", "expiresAt", "chatSessionCount", "evaluationCount"
`

type RestoreDiscoverySessionParams struct {
	ID     string `json:"id"`
	UserId string `json:"userId"`
}

func (q *Queries) RestoreDiscoverySession(ctx context.Context, arg RestoreDiscoverySessionParams) (DiscoverySession, error) {
	row := q.db.QueryRow(ctx, RestoreDiscoverySession, arg.ID, arg.UserId)
	var i DiscoverySession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.SearchCriteria,
		&i.Location,
		&i.PropertyCount,
		&i.CachedPropertyIds,
		&i.Name,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.ChatSessionCount,
		&i.EvaluationCount,
	)
	return i, err
}

const UpdateDiscoverySession = `-- name: UpdateDiscoverySession :one
UPDATE discovery_sessions SET
    name = COALESCE($2, name),
    notes = COALESCE($3, notes),
    "updatedAt" = NOW()
WHERE id = $1 AND "userId" = $2
RETURNING id, "userId", "searchCriteria", location, "propertyCount", "cachedPropertyIds", name, notes, status, "createdAt", "updatedAt", "lastAccessedAt", "archivedAt", "expiresAt", "chatSessionCount", "evaluationCount"
`

type UpdateDiscoverySessionParams struct {
	ID    string      `json:"id"`
	Name  pgtype.Text `json:"name"`
	Notes pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateDiscoverySession(ctx context.Context, arg UpdateDiscoverySessionParams) (DiscoverySession, error) {
	row := q.db.QueryRow(ctx, UpdateDiscoverySession, arg.ID, arg.Name, arg.Notes)
	var i DiscoverySession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.SearchCriteria,
		&i.Location,
		&i.PropertyCount,
		&i.CachedPropertyIds,
		&i.Name,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.ChatSessionCount,
		&i.EvaluationCount,
	)
	return i, err
}

const UpdateDiscoverySessionAccess = `-- name: UpdateDiscoverySessionAccess :one
UPDATE discovery_sessions SET
    "lastAccessedAt" = NOW(),
    "updatedAt" = NOW()
WHERE id = $1
RETURNING id, "userId", "searchCriteria", location, "propertyCount", "cachedPropertyIds", name, notes, status, "createdAt", "updatedAt", "lastAccessedAt", "archivedAt", "expiresAt", "chatSessionCount", "evaluationCount"
`

func (q *Queries) UpdateDiscoverySessionAccess(ctx context.Context, id string) (DiscoverySession, error) {
	row := q.db.QueryRow(ctx, UpdateDiscoverySessionAccess, id)
	var i DiscoverySession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.SearchCriteria,
		&i.Location,
		&i.PropertyCount,
		&i.CachedPropertyIds,
		&i.Name,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.ChatSessionCount,
		&i.EvaluationCount,
	)
	return i, err
}
