// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: market_history.sql

package queries

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountMarketHistory = `-- name: CountMarketHistory :one
SELECT COUNT(*) FROM market_history
`

func (q *Queries) CountMarketHistory(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountMarketHistory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteMarketHistory = `-- name: DeleteMarketHistory :exec
DELETE FROM market_history WHERE market_id = $1
`

func (q *Queries) DeleteMarketHistory(ctx context.Context, marketID string) error {
	_, err := q.db.Exec(ctx, DeleteMarketHistory, marketID)
	return err
}

const GetMarketHistory = `-- name: GetMarketHistory :one

SELECT market_id, historical_peak_drop, last_updated, created_at
FROM market_history
WHERE market_id = $1
`

// ADR-088 Phase 1: Market History Queries
// CRUD operations for market historical data
func (q *Queries) GetMarketHistory(ctx context.Context, marketID string) (MarketHistory, error) {
	row := q.db.QueryRow(ctx, GetMarketHistory, marketID)
	var i MarketHistory
	err := row.Scan(
		&i.MarketID,
		&i.HistoricalPeakDrop,
		&i.LastUpdated,
		&i.CreatedAt,
	)
	return i, err
}

const ListMarketHistory = `-- name: ListMarketHistory :many
SELECT market_id, historical_peak_drop, last_updated, created_at
FROM market_history
ORDER BY market_id
`

func (q *Queries) ListMarketHistory(ctx context.Context) ([]MarketHistory, error) {
	rows, err := q.db.Query(ctx, ListMarketHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketHistory{}
	for rows.Next() {
		var i MarketHistory
		if err := rows.Scan(
			&i.MarketID,
			&i.HistoricalPeakDrop,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListStaleMarketHistory = `-- name: ListStaleMarketHistory :many
SELECT market_id, historical_peak_drop, last_updated, created_at
FROM market_history
WHERE last_updated < NOW() - INTERVAL '7 days'
ORDER BY last_updated ASC
`

// Get markets that haven't been updated in 7+ days
func (q *Queries) ListStaleMarketHistory(ctx context.Context) ([]MarketHistory, error) {
	rows, err := q.db.Query(ctx, ListStaleMarketHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketHistory{}
	for rows.Next() {
		var i MarketHistory
		if err := rows.Scan(
			&i.MarketID,
			&i.HistoricalPeakDrop,
			&i.LastUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertMarketHistory = `-- name: UpsertMarketHistory :exec
INSERT INTO market_history (market_id, historical_peak_drop, last_updated, created_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (market_id)
DO UPDATE SET
    historical_peak_drop = EXCLUDED.historical_peak_drop,
    last_updated = EXCLUDED.last_updated
`

type UpsertMarketHistoryParams struct {
	MarketID           string        `json:"market_id"`
	HistoricalPeakDrop pgtype.Float8 `json:"historical_peak_drop"`
	LastUpdated        time.Time     `json:"last_updated"`
}

func (q *Queries) UpsertMarketHistory(ctx context.Context, arg UpsertMarketHistoryParams) error {
	_, err := q.db.Exec(ctx, UpsertMarketHistory, arg.MarketID, arg.HistoricalPeakDrop, arg.LastUpdated)
	return err
}
