// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_setup_tokens.sql

package queries

import (
	"context"
	"time"
)

const CreatePasswordSetupToken = `-- name: CreatePasswordSetupToken :one

INSERT INTO password_setup_tokens (
    id, user_id, token, expires_at, created_at
) VALUES (
    $1, $2, $3, $4, NOW()
) RETURNING id, user_id, token, expires_at, used_at, created_at
`

type CreatePasswordSetupTokenParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Password Setup Token Queries (ADR-085)
func (q *Queries) CreatePasswordSetupToken(ctx context.Context, arg CreatePasswordSetupTokenParams) (PasswordSetupToken, error) {
	row := q.db.QueryRow(ctx, CreatePasswordSetupToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i PasswordSetupToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetPasswordSetupToken = `-- name: GetPasswordSetupToken :one
SELECT id, user_id, token, expires_at, used_at, created_at FROM password_setup_tokens WHERE token = $1
`

func (q *Queries) GetPasswordSetupToken(ctx context.Context, token string) (PasswordSetupToken, error) {
	row := q.db.QueryRow(ctx, GetPasswordSetupToken, token)
	var i PasswordSetupToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const MarkPasswordSetupTokenUsed = `-- name: MarkPasswordSetupTokenUsed :exec
UPDATE password_setup_tokens SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkPasswordSetupTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, MarkPasswordSetupTokenUsed, id)
	return err
}
