// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolio_v2.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountPortfolioProperties = `-- name: CountPortfolioProperties :one
SELECT COUNT(*) FROM v2_portfolio_properties
WHERE user_id = $1 AND status != 'deleted'
`

func (q *Queries) CountPortfolioProperties(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, CountPortfolioProperties, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreatePortfolioProperty = `-- name: CreatePortfolioProperty :one
INSERT INTO v2_portfolio_properties (
    id, user_id, address, city, state, zip_code,
    property_type, bedrooms, bathrooms, sqft, year_built,
    purchase_price, purchase_date, current_value, last_valued_at,
    monthly_rent, vacancy_rate, expenses,
    mortgage_balance, mortgage_rate, mortgage_payment, loan_term_years,
    lat, lng, acquisition_type, expense_frequency, revenue_frequency,
    status, property_status, notes, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15,
    $16, $17, $18,
    $19, $20, $21, $22,
    $23, $24, $25, $26, $27,
    $28, $29, $30, NOW(), NOW()
)
RETURNING id, user_id, address, city, state, zip_code, property_type, bedrooms, bathrooms, sqft, year_built, purchase_price, purchase_date, current_value, last_valued_at, monthly_rent, vacancy_rate, expenses, mortgage_balance, mortgage_rate, mortgage_payment, loan_term_years, lat, lng, acquisition_type, expense_frequency, revenue_frequency, sale_date, sale_price, status, property_status, last_confirmed_at, notes, created_at, updated_at
`

type CreatePortfolioPropertyParams struct {
	ID               string           `json:"id"`
	UserID           string           `json:"user_id"`
	Address          string           `json:"address"`
	City             string           `json:"city"`
	State            string           `json:"state"`
	ZipCode          string           `json:"zip_code"`
	PropertyType     pgtype.Text      `json:"property_type"`
	Bedrooms         pgtype.Int4      `json:"bedrooms"`
	Bathrooms        pgtype.Float8    `json:"bathrooms"`
	Sqft             pgtype.Int4      `json:"sqft"`
	YearBuilt        pgtype.Int4      `json:"year_built"`
	PurchasePrice    float64          `json:"purchase_price"`
	PurchaseDate     pgtype.Timestamp `json:"purchase_date"`
	CurrentValue     pgtype.Float8    `json:"current_value"`
	LastValuedAt     pgtype.Timestamp `json:"last_valued_at"`
	MonthlyRent      pgtype.Float8    `json:"monthly_rent"`
	VacancyRate      pgtype.Float8    `json:"vacancy_rate"`
	Expenses         []byte           `json:"expenses"`
	MortgageBalance  pgtype.Float8    `json:"mortgage_balance"`
	MortgageRate     pgtype.Float8    `json:"mortgage_rate"`
	MortgagePayment  pgtype.Float8    `json:"mortgage_payment"`
	LoanTermYears    pgtype.Int4      `json:"loan_term_years"`
	Lat              pgtype.Float8    `json:"lat"`
	Lng              pgtype.Float8    `json:"lng"`
	AcquisitionType  string           `json:"acquisition_type"`
	ExpenseFrequency string           `json:"expense_frequency"`
	RevenueFrequency string           `json:"revenue_frequency"`
	Status           string           `json:"status"`
	PropertyStatus   string           `json:"property_status"`
	Notes            pgtype.Text      `json:"notes"`
}

func (q *Queries) CreatePortfolioProperty(ctx context.Context, arg CreatePortfolioPropertyParams) (V2PortfolioProperty, error) {
	row := q.db.QueryRow(ctx, CreatePortfolioProperty,
		arg.ID,
		arg.UserID,
		arg.Address,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.PropertyType,
		arg.Bedrooms,
		arg.Bathrooms,
		arg.Sqft,
		arg.YearBuilt,
		arg.PurchasePrice,
		arg.PurchaseDate,
		arg.CurrentValue,
		arg.LastValuedAt,
		arg.MonthlyRent,
		arg.VacancyRate,
		arg.Expenses,
		arg.MortgageBalance,
		arg.MortgageRate,
		arg.MortgagePayment,
		arg.LoanTermYears,
		arg.Lat,
		arg.Lng,
		arg.AcquisitionType,
		arg.ExpenseFrequency,
		arg.RevenueFrequency,
		arg.Status,
		arg.PropertyStatus,
		arg.Notes,
	)
	var i V2PortfolioProperty
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.PropertyType,
		&i.Bedrooms,
		&i.Bathrooms,
		&i.Sqft,
		&i.YearBuilt,
		&i.PurchasePrice,
		&i.PurchaseDate,
		&i.CurrentValue,
		&i.LastValuedAt,
		&i.MonthlyRent,
		&i.VacancyRate,
		&i.Expenses,
		&i.MortgageBalance,
		&i.MortgageRate,
		&i.MortgagePayment,
		&i.LoanTermYears,
		&i.Lat,
		&i.Lng,
		&i.AcquisitionType,
		&i.ExpenseFrequency,
		&i.RevenueFrequency,
		&i.SaleDate,
		&i.SalePrice,
		&i.Status,
		&i.PropertyStatus,
		&i.LastConfirmedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetPortfolioPropertiesByIDs = `-- name: GetPortfolioPropertiesByIDs :many
SELECT id, user_id, address, city, state, zip_code,
       property_type, bedrooms, bathrooms, sqft, year_built,
       purchase_price, purchase_date, current_value, last_valued_at,
       monthly_rent, vacancy_rate, expenses,
       mortgage_balance, mortgage_rate, mortgage_payment, loan_term_years,
       lat, lng, acquisition_type, expense_frequency, revenue_frequency,
       sale_date, sale_price, status, property_status, last_confirmed_at,
       notes, created_at, updated_at
FROM v2_portfolio_properties
WHERE id = ANY($2::text[]) AND user_id = $1
`

type GetPortfolioPropertiesByIDsParams struct {
	UserID string   `json:"user_id"`
	Ids    []string `json:"ids"`
}

func (q *Queries) GetPortfolioPropertiesByIDs(ctx context.Context, arg GetPortfolioPropertiesByIDsParams) ([]V2PortfolioProperty, error) {
	rows, err := q.db.Query(ctx, GetPortfolioPropertiesByIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V2PortfolioProperty{}
	for rows.Next() {
		var i V2PortfolioProperty
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.PropertyType,
			&i.Bedrooms,
			&i.Bathrooms,
			&i.Sqft,
			&i.YearBuilt,
			&i.PurchasePrice,
			&i.PurchaseDate,
			&i.CurrentValue,
			&i.LastValuedAt,
			&i.MonthlyRent,
			&i.VacancyRate,
			&i.Expenses,
			&i.MortgageBalance,
			&i.MortgageRate,
			&i.MortgagePayment,
			&i.LoanTermYears,
			&i.Lat,
			&i.Lng,
			&i.AcquisitionType,
			&i.ExpenseFrequency,
			&i.RevenueFrequency,
			&i.SaleDate,
			&i.SalePrice,
			&i.Status,
			&i.PropertyStatus,
			&i.LastConfirmedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPortfolioProperty = `-- name: GetPortfolioProperty :one
SELECT id, user_id, address, city, state, zip_code,
       property_type, bedrooms, bathrooms, sqft, year_built,
       purchase_price, purchase_date, current_value, last_valued_at,
       monthly_rent, vacancy_rate, expenses,
       mortgage_balance, mortgage_rate, mortgage_payment, loan_term_years,
       lat, lng, acquisition_type, expense_frequency, revenue_frequency,
       sale_date, sale_price, status, property_status, last_confirmed_at,
       notes, created_at, updated_at
FROM v2_portfolio_properties
WHERE id = $1 AND user_id = $2
`

type GetPortfolioPropertyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetPortfolioProperty(ctx context.Context, arg GetPortfolioPropertyParams) (V2PortfolioProperty, error) {
	row := q.db.QueryRow(ctx, GetPortfolioProperty, arg.ID, arg.UserID)
	var i V2PortfolioProperty
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.PropertyType,
		&i.Bedrooms,
		&i.Bathrooms,
		&i.Sqft,
		&i.YearBuilt,
		&i.PurchasePrice,
		&i.PurchaseDate,
		&i.CurrentValue,
		&i.LastValuedAt,
		&i.MonthlyRent,
		&i.VacancyRate,
		&i.Expenses,
		&i.MortgageBalance,
		&i.MortgageRate,
		&i.MortgagePayment,
		&i.LoanTermYears,
		&i.Lat,
		&i.Lng,
		&i.AcquisitionType,
		&i.ExpenseFrequency,
		&i.RevenueFrequency,
		&i.SaleDate,
		&i.SalePrice,
		&i.Status,
		&i.PropertyStatus,
		&i.LastConfirmedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListPortfolioProperties = `-- name: ListPortfolioProperties :many

SELECT id, user_id, address, city, state, zip_code,
       property_type, bedrooms, bathrooms, sqft, year_built,
       purchase_price, purchase_date, current_value, last_valued_at,
       monthly_rent, vacancy_rate, expenses,
       mortgage_balance, mortgage_rate, mortgage_payment, loan_term_years,
       lat, lng, acquisition_type, expense_frequency, revenue_frequency,
       sale_date, sale_price, status, property_status, last_confirmed_at,
       notes, created_at, updated_at
FROM v2_portfolio_properties
WHERE user_id = $1 AND status != 'deleted'
ORDER BY created_at DESC
`

// V2 Portfolio Properties Queries
func (q *Queries) ListPortfolioProperties(ctx context.Context, userID string) ([]V2PortfolioProperty, error) {
	rows, err := q.db.Query(ctx, ListPortfolioProperties, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V2PortfolioProperty{}
	for rows.Next() {
		var i V2PortfolioProperty
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.PropertyType,
			&i.Bedrooms,
			&i.Bathrooms,
			&i.Sqft,
			&i.YearBuilt,
			&i.PurchasePrice,
			&i.PurchaseDate,
			&i.CurrentValue,
			&i.LastValuedAt,
			&i.MonthlyRent,
			&i.VacancyRate,
			&i.Expenses,
			&i.MortgageBalance,
			&i.MortgageRate,
			&i.MortgagePayment,
			&i.LoanTermYears,
			&i.Lat,
			&i.Lng,
			&i.AcquisitionType,
			&i.ExpenseFrequency,
			&i.RevenueFrequency,
			&i.SaleDate,
			&i.SalePrice,
			&i.Status,
			&i.PropertyStatus,
			&i.LastConfirmedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeletePortfolioProperty = `-- name: SoftDeletePortfolioProperty :exec
UPDATE v2_portfolio_properties
SET status = 'deleted', updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type SoftDeletePortfolioPropertyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeletePortfolioProperty(ctx context.Context, arg SoftDeletePortfolioPropertyParams) error {
	_, err := q.db.Exec(ctx, SoftDeletePortfolioProperty, arg.ID, arg.UserID)
	return err
}

const UpdatePortfolioProperty = `-- name: UpdatePortfolioProperty :one
UPDATE v2_portfolio_properties SET
    address = COALESCE($3::text, address),
    city = COALESCE($4::text, city),
    state = COALESCE($5::text, state),
    zip_code = COALESCE($6::text, zip_code),
    property_type = COALESCE($7::text, property_type),
    bedrooms = COALESCE($8::integer, bedrooms),
    bathrooms = COALESCE($9::double precision, bathrooms),
    sqft = COALESCE($10::integer, sqft),
    year_built = COALESCE($11::integer, year_built),
    purchase_price = COALESCE($12::double precision, purchase_price),
    purchase_date = COALESCE($13::timestamp, purchase_date),
    current_value = COALESCE($14::double precision, current_value),
    last_valued_at = COALESCE($15::timestamp, last_valued_at),
    monthly_rent = COALESCE($16::double precision, monthly_rent),
    vacancy_rate = COALESCE($17::double precision, vacancy_rate),
    expenses = COALESCE($18::jsonb, expenses),
    mortgage_balance = COALESCE($19::double precision, mortgage_balance),
    mortgage_rate = COALESCE($20::double precision, mortgage_rate),
    mortgage_payment = COALESCE($21::double precision, mortgage_payment),
    loan_term_years = COALESCE($22::integer, loan_term_years),
    lat = COALESCE($23::double precision, lat),
    lng = COALESCE($24::double precision, lng),
    acquisition_type = COALESCE($25::text, acquisition_type),
    expense_frequency = COALESCE($26::text, expense_frequency),
    revenue_frequency = COALESCE($27::text, revenue_frequency),
    sale_date = $28::timestamp,
    sale_price = $29::double precision,
    property_status = COALESCE($30::varchar, property_status),
    notes = $31::text,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, address, city, state, zip_code, property_type, bedrooms, bathrooms, sqft, year_built, purchase_price, purchase_date, current_value, last_valued_at, monthly_rent, vacancy_rate, expenses, mortgage_balance, mortgage_rate, mortgage_payment, loan_term_years, lat, lng, acquisition_type, expense_frequency, revenue_frequency, sale_date, sale_price, status, property_status, last_confirmed_at, notes, created_at, updated_at
`

type UpdatePortfolioPropertyParams struct {
	ID               string           `json:"id"`
	UserID           string           `json:"user_id"`
	Address          pgtype.Text      `json:"address"`
	City             pgtype.Text      `json:"city"`
	State            pgtype.Text      `json:"state"`
	ZipCode          pgtype.Text      `json:"zip_code"`
	PropertyType     pgtype.Text      `json:"property_type"`
	Bedrooms         pgtype.Int4      `json:"bedrooms"`
	Bathrooms        pgtype.Float8    `json:"bathrooms"`
	Sqft             pgtype.Int4      `json:"sqft"`
	YearBuilt        pgtype.Int4      `json:"year_built"`
	PurchasePrice    pgtype.Float8    `json:"purchase_price"`
	PurchaseDate     pgtype.Timestamp `json:"purchase_date"`
	CurrentValue     pgtype.Float8    `json:"current_value"`
	LastValuedAt     pgtype.Timestamp `json:"last_valued_at"`
	MonthlyRent      pgtype.Float8    `json:"monthly_rent"`
	VacancyRate      pgtype.Float8    `json:"vacancy_rate"`
	Expenses         []byte           `json:"expenses"`
	MortgageBalance  pgtype.Float8    `json:"mortgage_balance"`
	MortgageRate     pgtype.Float8    `json:"mortgage_rate"`
	MortgagePayment  pgtype.Float8    `json:"mortgage_payment"`
	LoanTermYears    pgtype.Int4      `json:"loan_term_years"`
	Lat              pgtype.Float8    `json:"lat"`
	Lng              pgtype.Float8    `json:"lng"`
	AcquisitionType  pgtype.Text      `json:"acquisition_type"`
	ExpenseFrequency pgtype.Text      `json:"expense_frequency"`
	RevenueFrequency pgtype.Text      `json:"revenue_frequency"`
	SaleDate         pgtype.Timestamp `json:"sale_date"`
	SalePrice        pgtype.Float8    `json:"sale_price"`
	PropertyStatus   pgtype.Text      `json:"property_status"`
	Notes            pgtype.Text      `json:"notes"`
}

func (q *Queries) UpdatePortfolioProperty(ctx context.Context, arg UpdatePortfolioPropertyParams) (V2PortfolioProperty, error) {
	row := q.db.QueryRow(ctx, UpdatePortfolioProperty,
		arg.ID,
		arg.UserID,
		arg.Address,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.PropertyType,
		arg.Bedrooms,
		arg.Bathrooms,
		arg.Sqft,
		arg.YearBuilt,
		arg.PurchasePrice,
		arg.PurchaseDate,
		arg.CurrentValue,
		arg.LastValuedAt,
		arg.MonthlyRent,
		arg.VacancyRate,
		arg.Expenses,
		arg.MortgageBalance,
		arg.MortgageRate,
		arg.MortgagePayment,
		arg.LoanTermYears,
		arg.Lat,
		arg.Lng,
		arg.AcquisitionType,
		arg.ExpenseFrequency,
		arg.RevenueFrequency,
		arg.SaleDate,
		arg.SalePrice,
		arg.PropertyStatus,
		arg.Notes,
	)
	var i V2PortfolioProperty
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.PropertyType,
		&i.Bedrooms,
		&i.Bathrooms,
		&i.Sqft,
		&i.YearBuilt,
		&i.PurchasePrice,
		&i.PurchaseDate,
		&i.CurrentValue,
		&i.LastValuedAt,
		&i.MonthlyRent,
		&i.VacancyRate,
		&i.Expenses,
		&i.MortgageBalance,
		&i.MortgageRate,
		&i.MortgagePayment,
		&i.LoanTermYears,
		&i.Lat,
		&i.Lng,
		&i.AcquisitionType,
		&i.ExpenseFrequency,
		&i.RevenueFrequency,
		&i.SaleDate,
		&i.SalePrice,
		&i.Status,
		&i.PropertyStatus,
		&i.LastConfirmedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
