// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolio_snapshots.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountPortfolioSnapshots = `-- name: CountPortfolioSnapshots :one
SELECT COUNT(*) FROM v2_portfolio_snapshots WHERE user_id = $1
`

// Count snapshots for a user
func (q *Queries) CountPortfolioSnapshots(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, CountPortfolioSnapshots, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateOrUpdateAdjustment = `-- name: CreateOrUpdateAdjustment :one
INSERT INTO v2_portfolio_adjustments (
    id, property_id, month, type, amount, note, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
ON CONFLICT (property_id, month, type) DO UPDATE SET
    amount = EXCLUDED.amount,
    note = EXCLUDED.note,
    updated_at = NOW()
RETURNING id, property_id, month, type, amount, note, created_at, updated_at
`

type CreateOrUpdateAdjustmentParams struct {
	ID         string           `json:"id"`
	PropertyID string           `json:"property_id"`
	Month      pgtype.Timestamp `json:"month"`
	Type       string           `json:"type"`
	Amount     float64          `json:"amount"`
	Note       pgtype.Text      `json:"note"`
}

// Create or update an adjustment for a property/month/type combination
func (q *Queries) CreateOrUpdateAdjustment(ctx context.Context, arg CreateOrUpdateAdjustmentParams) (V2PortfolioAdjustment, error) {
	row := q.db.QueryRow(ctx, CreateOrUpdateAdjustment,
		arg.ID,
		arg.PropertyID,
		arg.Month,
		arg.Type,
		arg.Amount,
		arg.Note,
	)
	var i V2PortfolioAdjustment
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Month,
		&i.Type,
		&i.Amount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateOrUpdateBaselineChange = `-- name: CreateOrUpdateBaselineChange :one
INSERT INTO v2_baseline_changes (
    id, property_id, field, effective_date, new_value, previous_value, note, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
ON CONFLICT (property_id, field, effective_date) DO UPDATE SET
    new_value = EXCLUDED.new_value,
    previous_value = EXCLUDED.previous_value,
    note = EXCLUDED.note,
    updated_at = NOW()
RETURNING id, property_id, field, effective_date, new_value, previous_value, note, created_at, updated_at
`

type CreateOrUpdateBaselineChangeParams struct {
	ID            string           `json:"id"`
	PropertyID    string           `json:"property_id"`
	Field         string           `json:"field"`
	EffectiveDate pgtype.Timestamp `json:"effective_date"`
	NewValue      float64          `json:"new_value"`
	PreviousValue pgtype.Float8    `json:"previous_value"`
	Note          pgtype.Text      `json:"note"`
}

// Create or update a baseline change for a property/field/effective_date combination
func (q *Queries) CreateOrUpdateBaselineChange(ctx context.Context, arg CreateOrUpdateBaselineChangeParams) (V2BaselineChange, error) {
	row := q.db.QueryRow(ctx, CreateOrUpdateBaselineChange,
		arg.ID,
		arg.PropertyID,
		arg.Field,
		arg.EffectiveDate,
		arg.NewValue,
		arg.PreviousValue,
		arg.Note,
	)
	var i V2BaselineChange
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Field,
		&i.EffectiveDate,
		&i.NewValue,
		&i.PreviousValue,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreatePortfolioSnapshot = `-- name: CreatePortfolioSnapshot :one
INSERT INTO v2_portfolio_snapshots (
    id, user_id, snapshot_date, total_value, total_equity, total_debt,
    monthly_cash_flow, portfolio_cap_rate, property_count, metrics_json, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW()
)
ON CONFLICT (user_id, snapshot_date) DO UPDATE SET
    total_value = EXCLUDED.total_value,
    total_equity = EXCLUDED.total_equity,
    total_debt = EXCLUDED.total_debt,
    monthly_cash_flow = EXCLUDED.monthly_cash_flow,
    portfolio_cap_rate = EXCLUDED.portfolio_cap_rate,
    property_count = EXCLUDED.property_count,
    metrics_json = EXCLUDED.metrics_json
RETURNING id, user_id, snapshot_date, total_value, total_equity, total_debt,
          monthly_cash_flow, portfolio_cap_rate, property_count, metrics_json, created_at
`

type CreatePortfolioSnapshotParams struct {
	ID               string           `json:"id"`
	UserID           string           `json:"user_id"`
	SnapshotDate     pgtype.Timestamp `json:"snapshot_date"`
	TotalValue       float64          `json:"total_value"`
	TotalEquity      float64          `json:"total_equity"`
	TotalDebt        float64          `json:"total_debt"`
	MonthlyCashFlow  float64          `json:"monthly_cash_flow"`
	PortfolioCapRate float64          `json:"portfolio_cap_rate"`
	PropertyCount    int32            `json:"property_count"`
	MetricsJson      []byte           `json:"metrics_json"`
}

// Create a new portfolio snapshot
func (q *Queries) CreatePortfolioSnapshot(ctx context.Context, arg CreatePortfolioSnapshotParams) (V2PortfolioSnapshot, error) {
	row := q.db.QueryRow(ctx, CreatePortfolioSnapshot,
		arg.ID,
		arg.UserID,
		arg.SnapshotDate,
		arg.TotalValue,
		arg.TotalEquity,
		arg.TotalDebt,
		arg.MonthlyCashFlow,
		arg.PortfolioCapRate,
		arg.PropertyCount,
		arg.MetricsJson,
	)
	var i V2PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SnapshotDate,
		&i.TotalValue,
		&i.TotalEquity,
		&i.TotalDebt,
		&i.MonthlyCashFlow,
		&i.PortfolioCapRate,
		&i.PropertyCount,
		&i.MetricsJson,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteAdjustment = `-- name: DeleteAdjustment :exec
DELETE FROM v2_portfolio_adjustments WHERE id = $1
`

// Delete an adjustment by ID
func (q *Queries) DeleteAdjustment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeleteAdjustment, id)
	return err
}

const DeleteBaselineChange = `-- name: DeleteBaselineChange :exec
DELETE FROM v2_baseline_changes WHERE id = $1
`

// Delete a baseline change by ID
func (q *Queries) DeleteBaselineChange(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeleteBaselineChange, id)
	return err
}

const DeletePortfolioSnapshots = `-- name: DeletePortfolioSnapshots :exec
DELETE FROM v2_portfolio_snapshots
WHERE user_id = $1
`

// Delete all snapshots for a user (for regeneration)
func (q *Queries) DeletePortfolioSnapshots(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, DeletePortfolioSnapshots, userID)
	return err
}

const GetEarliestPropertyDate = `-- name: GetEarliestPropertyDate :one
SELECT MIN(purchase_date) as earliest_date
FROM v2_portfolio_properties
WHERE user_id = $1 AND status != 'deleted' AND purchase_date IS NOT NULL
`

// Get the earliest purchase date from portfolio properties for backfill
func (q *Queries) GetEarliestPropertyDate(ctx context.Context, userID string) (interface{}, error) {
	row := q.db.QueryRow(ctx, GetEarliestPropertyDate, userID)
	var earliest_date interface{}
	err := row.Scan(&earliest_date)
	return earliest_date, err
}

const GetLatestBaselineChange = `-- name: GetLatestBaselineChange :one
SELECT id, property_id, field, effective_date, new_value, previous_value, note, created_at, updated_at
FROM v2_baseline_changes
WHERE property_id = $1 AND field = $2 AND effective_date < $3
ORDER BY effective_date DESC
LIMIT 1
`

type GetLatestBaselineChangeParams struct {
	PropertyID    string           `json:"property_id"`
	Field         string           `json:"field"`
	EffectiveDate pgtype.Timestamp `json:"effective_date"`
}

// Get the most recent baseline change for a property/field before a given date
func (q *Queries) GetLatestBaselineChange(ctx context.Context, arg GetLatestBaselineChangeParams) (V2BaselineChange, error) {
	row := q.db.QueryRow(ctx, GetLatestBaselineChange, arg.PropertyID, arg.Field, arg.EffectiveDate)
	var i V2BaselineChange
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Field,
		&i.EffectiveDate,
		&i.NewValue,
		&i.PreviousValue,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetLatestPortfolioSnapshot = `-- name: GetLatestPortfolioSnapshot :one
SELECT id, user_id, snapshot_date, total_value, total_equity, total_debt,
       monthly_cash_flow, portfolio_cap_rate, property_count, metrics_json, created_at
FROM v2_portfolio_snapshots
WHERE user_id = $1
ORDER BY snapshot_date DESC
LIMIT 1
`

// Get the most recent snapshot for a user
func (q *Queries) GetLatestPortfolioSnapshot(ctx context.Context, userID string) (V2PortfolioSnapshot, error) {
	row := q.db.QueryRow(ctx, GetLatestPortfolioSnapshot, userID)
	var i V2PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SnapshotDate,
		&i.TotalValue,
		&i.TotalEquity,
		&i.TotalDebt,
		&i.MonthlyCashFlow,
		&i.PortfolioCapRate,
		&i.PropertyCount,
		&i.MetricsJson,
		&i.CreatedAt,
	)
	return i, err
}

const GetPortfolioSnapshots = `-- name: GetPortfolioSnapshots :many
SELECT id, user_id, snapshot_date, total_value, total_equity, total_debt,
       monthly_cash_flow, portfolio_cap_rate, property_count, metrics_json, created_at
FROM v2_portfolio_snapshots
WHERE user_id = $1
  AND ($2::timestamp IS NULL OR snapshot_date >= $2)
  AND ($3::timestamp IS NULL OR snapshot_date <= $3)
ORDER BY snapshot_date DESC
LIMIT $4
`

type GetPortfolioSnapshotsParams struct {
	UserID  string           `json:"user_id"`
	Column2 pgtype.Timestamp `json:"column_2"`
	Column3 pgtype.Timestamp `json:"column_3"`
	Limit   int32            `json:"limit"`
}

// Portfolio Snapshots SQLC Queries
// Get portfolio snapshots for a user within a date range
func (q *Queries) GetPortfolioSnapshots(ctx context.Context, arg GetPortfolioSnapshotsParams) ([]V2PortfolioSnapshot, error) {
	rows, err := q.db.Query(ctx, GetPortfolioSnapshots,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V2PortfolioSnapshot{}
	for rows.Next() {
		var i V2PortfolioSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SnapshotDate,
			&i.TotalValue,
			&i.TotalEquity,
			&i.TotalDebt,
			&i.MonthlyCashFlow,
			&i.PortfolioCapRate,
			&i.PropertyCount,
			&i.MetricsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPropertyAdjustments = `-- name: GetPropertyAdjustments :many

SELECT id, property_id, month, type, amount, note, created_at, updated_at
FROM v2_portfolio_adjustments
WHERE property_id = $1
ORDER BY month DESC
`

// ============================================
// Portfolio Adjustments Queries
// ============================================
// Get all adjustments for a property ordered by month descending
func (q *Queries) GetPropertyAdjustments(ctx context.Context, propertyID string) ([]V2PortfolioAdjustment, error) {
	rows, err := q.db.Query(ctx, GetPropertyAdjustments, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V2PortfolioAdjustment{}
	for rows.Next() {
		var i V2PortfolioAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Month,
			&i.Type,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPropertyBaselineChanges = `-- name: GetPropertyBaselineChanges :many

SELECT id, property_id, field, effective_date, new_value, previous_value, note, created_at, updated_at
FROM v2_baseline_changes
WHERE property_id = $1
ORDER BY effective_date DESC, field ASC
`

// ============================================
// Baseline Changes Queries
// ============================================
// Get all baseline changes for a property ordered by effective date descending
func (q *Queries) GetPropertyBaselineChanges(ctx context.Context, propertyID string) ([]V2BaselineChange, error) {
	rows, err := q.db.Query(ctx, GetPropertyBaselineChanges, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V2BaselineChange{}
	for rows.Next() {
		var i V2BaselineChange
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Field,
			&i.EffectiveDate,
			&i.NewValue,
			&i.PreviousValue,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
