// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: property_cache.sql

package queries

import (
	"context"
	"encoding/json"
)

const CountPropertyCache = `-- name: CountPropertyCache :one
SELECT COUNT(*)::bigint FROM property_cache
`

// Returns the total number of entries in the property cache
func (q *Queries) CountPropertyCache(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountPropertyCache)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const DeleteOldestPropertyCache = `-- name: DeleteOldestPropertyCache :execrows
DELETE FROM property_cache
WHERE id IN (
    SELECT id FROM property_cache
    ORDER BY created_at ASC
    LIMIT $1
)
`

// Deletes the oldest N entries from the cache (FIFO eviction)
func (q *Queries) DeleteOldestPropertyCache(ctx context.Context, limit int32) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteOldestPropertyCache, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeletePropertyCacheByProvider = `-- name: DeletePropertyCacheByProvider :execrows
DELETE FROM property_cache WHERE provider = $1
`

// Deletes all cache entries for a specific provider
func (q *Queries) DeletePropertyCacheByProvider(ctx context.Context, provider string) (int64, error) {
	result, err := q.db.Exec(ctx, DeletePropertyCacheByProvider, provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeletePropertyFromCache = `-- name: DeletePropertyFromCache :exec
DELETE FROM property_cache WHERE cache_key = $1
`

// Deletes a specific property from the cache
func (q *Queries) DeletePropertyFromCache(ctx context.Context, cacheKey string) error {
	_, err := q.db.Exec(ctx, DeletePropertyFromCache, cacheKey)
	return err
}

const GetPropertyByProviderAndID = `-- name: GetPropertyByProviderAndID :one
SELECT id, cache_key, provider, property_id, content, created_at, last_accessed_at, access_count FROM property_cache WHERE provider = $1 AND property_id = $2
`

type GetPropertyByProviderAndIDParams struct {
	Provider   string `json:"provider"`
	PropertyID string `json:"property_id"`
}

// Retrieves a property by provider and property ID
func (q *Queries) GetPropertyByProviderAndID(ctx context.Context, arg GetPropertyByProviderAndIDParams) (PropertyCache, error) {
	row := q.db.QueryRow(ctx, GetPropertyByProviderAndID, arg.Provider, arg.PropertyID)
	var i PropertyCache
	err := row.Scan(
		&i.ID,
		&i.CacheKey,
		&i.Provider,
		&i.PropertyID,
		&i.Content,
		&i.CreatedAt,
		&i.LastAccessedAt,
		&i.AccessCount,
	)
	return i, err
}

const GetPropertyCacheStats = `-- name: GetPropertyCacheStats :one
SELECT
    COUNT(*)::bigint as total_entries,
    MIN(created_at) as oldest_entry,
    MAX(created_at) as newest_entry,
    SUM(access_count)::bigint as total_accesses
FROM property_cache
`

type GetPropertyCacheStatsRow struct {
	TotalEntries  int64       `json:"total_entries"`
	OldestEntry   interface{} `json:"oldest_entry"`
	NewestEntry   interface{} `json:"newest_entry"`
	TotalAccesses int64       `json:"total_accesses"`
}

// Returns cache statistics for monitoring
func (q *Queries) GetPropertyCacheStats(ctx context.Context) (GetPropertyCacheStatsRow, error) {
	row := q.db.QueryRow(ctx, GetPropertyCacheStats)
	var i GetPropertyCacheStatsRow
	err := row.Scan(
		&i.TotalEntries,
		&i.OldestEntry,
		&i.NewestEntry,
		&i.TotalAccesses,
	)
	return i, err
}

const GetPropertyFromCache = `-- name: GetPropertyFromCache :one

SELECT id, cache_key, provider, property_id, content, created_at, last_accessed_at, access_count FROM property_cache WHERE cache_key = $1
`

// Property Cache Queries
// ADR-061: Size-based FIFO cache for individual property reads
// Retrieves a single property from cache by its cache key
func (q *Queries) GetPropertyFromCache(ctx context.Context, cacheKey string) (PropertyCache, error) {
	row := q.db.QueryRow(ctx, GetPropertyFromCache, cacheKey)
	var i PropertyCache
	err := row.Scan(
		&i.ID,
		&i.CacheKey,
		&i.Provider,
		&i.PropertyID,
		&i.Content,
		&i.CreatedAt,
		&i.LastAccessedAt,
		&i.AccessCount,
	)
	return i, err
}

const UpdatePropertyCacheAccess = `-- name: UpdatePropertyCacheAccess :exec
UPDATE property_cache
SET last_accessed_at = NOW(), access_count = access_count + 1
WHERE cache_key = $1
`

// Updates access timestamp and increments access count
func (q *Queries) UpdatePropertyCacheAccess(ctx context.Context, cacheKey string) error {
	_, err := q.db.Exec(ctx, UpdatePropertyCacheAccess, cacheKey)
	return err
}

const UpsertPropertyCache = `-- name: UpsertPropertyCache :exec
INSERT INTO property_cache (cache_key, provider, property_id, content, created_at, last_accessed_at, access_count)
VALUES ($1, $2, $3, $4, NOW(), NOW(), 0)
ON CONFLICT (cache_key) DO UPDATE SET
    content = EXCLUDED.content,
    last_accessed_at = NOW(),
    access_count = property_cache.access_count + 1
`

type UpsertPropertyCacheParams struct {
	CacheKey   string          `json:"cache_key"`
	Provider   string          `json:"provider"`
	PropertyID string          `json:"property_id"`
	Content    json.RawMessage `json:"content"`
}

// Inserts or updates a property in the cache
func (q *Queries) UpsertPropertyCache(ctx context.Context, arg UpsertPropertyCacheParams) error {
	_, err := q.db.Exec(ctx, UpsertPropertyCache,
		arg.CacheKey,
		arg.Provider,
		arg.PropertyID,
		arg.Content,
	)
	return err
}
