// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetActiveSubscriptionForQuota = `-- name: GetActiveSubscriptionForQuota :one
SELECT id, "userId", tier::text, status::text,
       "currentPeriodStart", "currentPeriodEnd"
FROM subscriptions
WHERE "userId" = $1 AND status::text IN ('ACTIVE', 'TRIALING')
ORDER BY "createdAt" DESC
LIMIT 1
`

type GetActiveSubscriptionForQuotaRow struct {
	ID                 string           `json:"id"`
	UserId             string           `json:"userId"`
	Tier               string           `json:"tier"`
	Status             string           `json:"status"`
	CurrentPeriodStart pgtype.Timestamp `json:"currentPeriodStart"`
	CurrentPeriodEnd   pgtype.Timestamp `json:"currentPeriodEnd"`
}

func (q *Queries) GetActiveSubscriptionForQuota(ctx context.Context, userid string) (GetActiveSubscriptionForQuotaRow, error) {
	row := q.db.QueryRow(ctx, GetActiveSubscriptionForQuota, userid)
	var i GetActiveSubscriptionForQuotaRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Tier,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
	)
	return i, err
}

const GetV2EvaluationQuota = `-- name: GetV2EvaluationQuota :one

SELECT id, user_id, tier::text, annual_limit, used_this_period,
       period_start_date, period_end_date, created_at, updated_at
FROM v2_evaluation_quotas
WHERE user_id = $1
`

type GetV2EvaluationQuotaRow struct {
	ID              string           `json:"id"`
	UserID          string           `json:"user_id"`
	Tier            string           `json:"tier"`
	AnnualLimit     int32            `json:"annual_limit"`
	UsedThisPeriod  int32            `json:"used_this_period"`
	PeriodStartDate pgtype.Timestamp `json:"period_start_date"`
	PeriodEndDate   pgtype.Timestamp `json:"period_end_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

// V2 Evaluation Quotas Queries
func (q *Queries) GetV2EvaluationQuota(ctx context.Context, userID string) (GetV2EvaluationQuotaRow, error) {
	row := q.db.QueryRow(ctx, GetV2EvaluationQuota, userID)
	var i GetV2EvaluationQuotaRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.AnnualLimit,
		&i.UsedThisPeriod,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const IncrementV2EvaluationQuotaUsage = `-- name: IncrementV2EvaluationQuotaUsage :exec
UPDATE v2_evaluation_quotas
SET used_this_period = used_this_period + 1,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) IncrementV2EvaluationQuotaUsage(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, IncrementV2EvaluationQuotaUsage, userID)
	return err
}

const IncrementV2EvaluationQuotaUsageReturning = `-- name: IncrementV2EvaluationQuotaUsageReturning :one
UPDATE v2_evaluation_quotas
SET used_this_period = used_this_period + 1,
    updated_at = NOW()
WHERE user_id = $1
RETURNING tier::text, annual_limit, used_this_period, period_end_date
`

type IncrementV2EvaluationQuotaUsageReturningRow struct {
	Tier           string           `json:"tier"`
	AnnualLimit    int32            `json:"annual_limit"`
	UsedThisPeriod int32            `json:"used_this_period"`
	PeriodEndDate  pgtype.Timestamp `json:"period_end_date"`
}

// Increment quota usage and return updated values (for batch exports)
func (q *Queries) IncrementV2EvaluationQuotaUsageReturning(ctx context.Context, userID string) (IncrementV2EvaluationQuotaUsageReturningRow, error) {
	row := q.db.QueryRow(ctx, IncrementV2EvaluationQuotaUsageReturning, userID)
	var i IncrementV2EvaluationQuotaUsageReturningRow
	err := row.Scan(
		&i.Tier,
		&i.AnnualLimit,
		&i.UsedThisPeriod,
		&i.PeriodEndDate,
	)
	return i, err
}

const ResetV2EvaluationQuotaUsage = `-- name: ResetV2EvaluationQuotaUsage :exec
UPDATE v2_evaluation_quotas
SET used_this_period = 0,
    period_start_date = $2,
    period_end_date = $3,
    updated_at = NOW()
WHERE user_id = $1
`

type ResetV2EvaluationQuotaUsageParams struct {
	UserID          string           `json:"user_id"`
	PeriodStartDate pgtype.Timestamp `json:"period_start_date"`
	PeriodEndDate   pgtype.Timestamp `json:"period_end_date"`
}

func (q *Queries) ResetV2EvaluationQuotaUsage(ctx context.Context, arg ResetV2EvaluationQuotaUsageParams) error {
	_, err := q.db.Exec(ctx, ResetV2EvaluationQuotaUsage, arg.UserID, arg.PeriodStartDate, arg.PeriodEndDate)
	return err
}

const UpsertV2EvaluationQuota = `-- name: UpsertV2EvaluationQuota :one
INSERT INTO v2_evaluation_quotas (
    id, user_id, tier, annual_limit, used_this_period,
    period_start_date, period_end_date, created_at, updated_at
) VALUES ($1, $2, $3::text::"V2SubscriptionTier", $4, $5, $6, $7, NOW(), NOW())
ON CONFLICT (user_id) DO UPDATE SET
    tier = EXCLUDED.tier,
    annual_limit = EXCLUDED.annual_limit,
    period_start_date = EXCLUDED.period_start_date,
    period_end_date = EXCLUDED.period_end_date,
    updated_at = NOW()
RETURNING id, user_id, tier::text, annual_limit, used_this_period,
          period_start_date, period_end_date, created_at, updated_at
`

type UpsertV2EvaluationQuotaParams struct {
	ID              string           `json:"id"`
	UserID          string           `json:"user_id"`
	Column3         string           `json:"column_3"`
	AnnualLimit     int32            `json:"annual_limit"`
	UsedThisPeriod  int32            `json:"used_this_period"`
	PeriodStartDate pgtype.Timestamp `json:"period_start_date"`
	PeriodEndDate   pgtype.Timestamp `json:"period_end_date"`
}

type UpsertV2EvaluationQuotaRow struct {
	ID              string           `json:"id"`
	UserID          string           `json:"user_id"`
	Tier            string           `json:"tier"`
	AnnualLimit     int32            `json:"annual_limit"`
	UsedThisPeriod  int32            `json:"used_this_period"`
	PeriodStartDate pgtype.Timestamp `json:"period_start_date"`
	PeriodEndDate   pgtype.Timestamp `json:"period_end_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertV2EvaluationQuota(ctx context.Context, arg UpsertV2EvaluationQuotaParams) (UpsertV2EvaluationQuotaRow, error) {
	row := q.db.QueryRow(ctx, UpsertV2EvaluationQuota,
		arg.ID,
		arg.UserID,
		arg.Column3,
		arg.AnnualLimit,
		arg.UsedThisPeriod,
		arg.PeriodStartDate,
		arg.PeriodEndDate,
	)
	var i UpsertV2EvaluationQuotaRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.AnnualLimit,
		&i.UsedThisPeriod,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpsertV2EvaluationQuotaWithPeriodReset = `-- name: UpsertV2EvaluationQuotaWithPeriodReset :exec
INSERT INTO v2_evaluation_quotas (id, user_id, tier, annual_limit, used_this_period, period_start_date, period_end_date, created_at, updated_at)
VALUES ($1, $2, $3::text::"V2SubscriptionTier", $4, 0, $5, $6, NOW(), NOW())
ON CONFLICT (user_id) DO UPDATE SET
    tier = $3::text::"V2SubscriptionTier",
    annual_limit = $4,
    period_start_date = CASE WHEN v2_evaluation_quotas.period_end_date < NOW() THEN $5 ELSE v2_evaluation_quotas.period_start_date END,
    period_end_date = CASE WHEN v2_evaluation_quotas.period_end_date < NOW() THEN $6 ELSE v2_evaluation_quotas.period_end_date END,
    used_this_period = CASE WHEN v2_evaluation_quotas.period_end_date < NOW() THEN 0 ELSE v2_evaluation_quotas.used_this_period END,
    updated_at = NOW()
`

type UpsertV2EvaluationQuotaWithPeriodResetParams struct {
	ID              string           `json:"id"`
	UserID          string           `json:"user_id"`
	Column3         string           `json:"column_3"`
	AnnualLimit     int32            `json:"annual_limit"`
	PeriodStartDate pgtype.Timestamp `json:"period_start_date"`
	PeriodEndDate   pgtype.Timestamp `json:"period_end_date"`
}

func (q *Queries) UpsertV2EvaluationQuotaWithPeriodReset(ctx context.Context, arg UpsertV2EvaluationQuotaWithPeriodResetParams) error {
	_, err := q.db.Exec(ctx, UpsertV2EvaluationQuotaWithPeriodReset,
		arg.ID,
		arg.UserID,
		arg.Column3,
		arg.AnnualLimit,
		arg.PeriodStartDate,
		arg.PeriodEndDate,
	)
	return err
}
