// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const CancelInsightAccess = `-- name: CancelInsightAccess :one
UPDATE insight_access SET
    status = 'CANCELLED',
    "updatedAt" = NOW()
WHERE id = $1
RETURNING id, "userId", tier, "billingFrequency", "reportsPerPeriod", "reportsPerYear", "reportsUsed", "rolloverReports", "lastRolloverDate", "periodStartDate", "periodEndDate", "startDate", "endDate", "stripeSubId", "stripePriceId", status, "lastReportGeneratedAt", "consumptionHistory", "createdAt", "updatedAt"
`

func (q *Queries) CancelInsightAccess(ctx context.Context, id string) (InsightAccess, error) {
	row := q.db.QueryRow(ctx, CancelInsightAccess, id)
	var i InsightAccess
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Tier,
		&i.BillingFrequency,
		&i.ReportsPerPeriod,
		&i.ReportsPerYear,
		&i.ReportsUsed,
		&i.RolloverReports,
		&i.LastRolloverDate,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.StartDate,
		&i.EndDate,
		&i.StripeSubId,
		&i.StripePriceId,
		&i.Status,
		&i.LastReportGeneratedAt,
		&i.ConsumptionHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CountSnapshotsByEmail = `-- name: CountSnapshotsByEmail :one
SELECT COUNT(*) FROM snapshot_requests
WHERE email = $1 AND status IN ('COMPLETE', 'GENERATING', 'PENDING')
`

func (q *Queries) CountSnapshotsByEmail(ctx context.Context, email pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, CountSnapshotsByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountUserInvestorReports = `-- name: CountUserInvestorReports :one
SELECT COUNT(*) FROM investor_reports WHERE "userId" = $1
`

func (q *Queries) CountUserInvestorReports(ctx context.Context, userid pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, CountUserInvestorReports, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateInsightAccess = `-- name: CreateInsightAccess :one
INSERT INTO insight_access (
    id, "userId", tier, "billingFrequency", "reportsPerPeriod", "reportsPerYear",
    "reportsUsed", "rolloverReports", "periodStartDate", "periodEndDate",
    "startDate", "endDate", "stripeSubId", "stripePriceId", status,
    "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW(), NOW()
) RETURNING id, "userId", tier, "billingFrequency", "reportsPerPeriod", "reportsPerYear", "reportsUsed", "rolloverReports", "lastRolloverDate", "periodStartDate", "periodEndDate", "startDate", "endDate", "stripeSubId", "stripePriceId", status, "lastReportGeneratedAt", "consumptionHistory", "createdAt", "updatedAt"
`

type CreateInsightAccessParams struct {
	ID               string           `json:"id"`
	UserId           string           `json:"userId"`
	Tier             interface{}      `json:"tier"`
	BillingFrequency interface{}      `json:"billingFrequency"`
	ReportsPerPeriod int32            `json:"reportsPerPeriod"`
	ReportsPerYear   pgtype.Int4      `json:"reportsPerYear"`
	ReportsUsed      int32            `json:"reportsUsed"`
	RolloverReports  int32            `json:"rolloverReports"`
	PeriodStartDate  pgtype.Timestamp `json:"periodStartDate"`
	PeriodEndDate    pgtype.Timestamp `json:"periodEndDate"`
	StartDate        pgtype.Timestamp `json:"startDate"`
	EndDate          pgtype.Timestamp `json:"endDate"`
	StripeSubId      pgtype.Text      `json:"stripeSubId"`
	StripePriceId    pgtype.Text      `json:"stripePriceId"`
	Status           interface{}      `json:"status"`
}

func (q *Queries) CreateInsightAccess(ctx context.Context, arg CreateInsightAccessParams) (InsightAccess, error) {
	row := q.db.QueryRow(ctx, CreateInsightAccess,
		arg.ID,
		arg.UserId,
		arg.Tier,
		arg.BillingFrequency,
		arg.ReportsPerPeriod,
		arg.ReportsPerYear,
		arg.ReportsUsed,
		arg.RolloverReports,
		arg.PeriodStartDate,
		arg.PeriodEndDate,
		arg.StartDate,
		arg.EndDate,
		arg.StripeSubId,
		arg.StripePriceId,
		arg.Status,
	)
	var i InsightAccess
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Tier,
		&i.BillingFrequency,
		&i.ReportsPerPeriod,
		&i.ReportsPerYear,
		&i.ReportsUsed,
		&i.RolloverReports,
		&i.LastRolloverDate,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.StartDate,
		&i.EndDate,
		&i.StripeSubId,
		&i.StripePriceId,
		&i.Status,
		&i.LastReportGeneratedAt,
		&i.ConsumptionHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateInvestorReport = `-- name: CreateInvestorReport :one
INSERT INTO investor_reports (
    id, "userId", email, "propertyId", "propertyAddress", type, status,
    "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId",
    "investmentCriteria", "cacheKey", "criteriaHash", "createdAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW()
) RETURNING id, "userId", email, "propertyId", "propertyAddress", type, status, "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId", "investmentCriteria", "metricsData", "narrativeData", "fullReport", "pdfUrl", "generationCost", "generationTimeMs", "allocationDecrementedAt", "allocationSnapshot", "cacheKey", "criteriaHash", "cachedFromId", "supersededById", "supersededAt", "createdAt", "completedAt", "expiresAt"
`

type CreateInvestorReportParams struct {
	ID                 string      `json:"id"`
	UserId             pgtype.Text `json:"userId"`
	Email              pgtype.Text `json:"email"`
	PropertyId         pgtype.Text `json:"propertyId"`
	PropertyAddress    pgtype.Text `json:"propertyAddress"`
	Type               interface{} `json:"type"`
	Status             interface{} `json:"status"`
	SourceType         interface{} `json:"sourceType"`
	SourcePackId       pgtype.Text `json:"sourcePackId"`
	SourceAccessId     pgtype.Text `json:"sourceAccessId"`
	StripePaymentId    pgtype.Text `json:"stripePaymentId"`
	InvestmentCriteria []byte      `json:"investmentCriteria"`
	CacheKey           pgtype.Text `json:"cacheKey"`
	CriteriaHash       pgtype.Text `json:"criteriaHash"`
}

func (q *Queries) CreateInvestorReport(ctx context.Context, arg CreateInvestorReportParams) (InvestorReport, error) {
	row := q.db.QueryRow(ctx, CreateInvestorReport,
		arg.ID,
		arg.UserId,
		arg.Email,
		arg.PropertyId,
		arg.PropertyAddress,
		arg.Type,
		arg.Status,
		arg.SourceType,
		arg.SourcePackId,
		arg.SourceAccessId,
		arg.StripePaymentId,
		arg.InvestmentCriteria,
		arg.CacheKey,
		arg.CriteriaHash,
	)
	var i InvestorReport
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Email,
		&i.PropertyId,
		&i.PropertyAddress,
		&i.Type,
		&i.Status,
		&i.SourceType,
		&i.SourcePackId,
		&i.SourceAccessId,
		&i.StripePaymentId,
		&i.InvestmentCriteria,
		&i.MetricsData,
		&i.NarrativeData,
		&i.FullReport,
		&i.PdfUrl,
		&i.GenerationCost,
		&i.GenerationTimeMs,
		&i.AllocationDecrementedAt,
		&i.AllocationSnapshot,
		&i.CacheKey,
		&i.CriteriaHash,
		&i.CachedFromId,
		&i.SupersededById,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const CreateReportPack = `-- name: CreateReportPack :one
INSERT INTO report_packs (
    id, "userId", "totalReports", "usedReports", "purchasedAt",
    "stripePaymentId", "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, 0, NOW(), $4, NOW(), NOW()
) RETURNING id, "userId", "totalReports", "usedReports", "purchasedAt", "stripePaymentId", "lastUsedAt", "consumptionHistory", "createdAt", "updatedAt"
`

type CreateReportPackParams struct {
	ID              string      `json:"id"`
	UserId          string      `json:"userId"`
	TotalReports    int32       `json:"totalReports"`
	StripePaymentId pgtype.Text `json:"stripePaymentId"`
}

func (q *Queries) CreateReportPack(ctx context.Context, arg CreateReportPackParams) (ReportPack, error) {
	row := q.db.QueryRow(ctx, CreateReportPack,
		arg.ID,
		arg.UserId,
		arg.TotalReports,
		arg.StripePaymentId,
	)
	var i ReportPack
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.TotalReports,
		&i.UsedReports,
		&i.PurchasedAt,
		&i.StripePaymentId,
		&i.LastUsedAt,
		&i.ConsumptionHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateSnapshotRequest = `-- name: CreateSnapshotRequest :one
INSERT INTO snapshot_requests (
    id, "sessionId", "userId", email, criteria, "criteriaHash", location,
    status, "snapshotNumber", "ipAddress", "userAgent", source, "createdAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW()
) RETURNING id, "sessionId", "userId", email, criteria, "criteriaHash", location, status, "snapshotNumber", "propertiesFound", properties, "resultId", "cacheKey", "cachedAt", "cacheExpiresAt", "ipAddress", "userAgent", source, "createdAt", "completedAt", "convertedAt"
`

type CreateSnapshotRequestParams struct {
	ID             string          `json:"id"`
	SessionId      string          `json:"sessionId"`
	UserId         pgtype.Text     `json:"userId"`
	Email          pgtype.Text     `json:"email"`
	Criteria       json.RawMessage `json:"criteria"`
	CriteriaHash   pgtype.Text     `json:"criteriaHash"`
	Location       pgtype.Text     `json:"location"`
	Status         interface{}     `json:"status"`
	SnapshotNumber int32           `json:"snapshotNumber"`
	IpAddress      pgtype.Text     `json:"ipAddress"`
	UserAgent      pgtype.Text     `json:"userAgent"`
	Source         pgtype.Text     `json:"source"`
}

func (q *Queries) CreateSnapshotRequest(ctx context.Context, arg CreateSnapshotRequestParams) (SnapshotRequest, error) {
	row := q.db.QueryRow(ctx, CreateSnapshotRequest,
		arg.ID,
		arg.SessionId,
		arg.UserId,
		arg.Email,
		arg.Criteria,
		arg.CriteriaHash,
		arg.Location,
		arg.Status,
		arg.SnapshotNumber,
		arg.IpAddress,
		arg.UserAgent,
		arg.Source,
	)
	var i SnapshotRequest
	err := row.Scan(
		&i.ID,
		&i.SessionId,
		&i.UserId,
		&i.Email,
		&i.Criteria,
		&i.CriteriaHash,
		&i.Location,
		&i.Status,
		&i.SnapshotNumber,
		&i.PropertiesFound,
		&i.Properties,
		&i.ResultId,
		&i.CacheKey,
		&i.CachedAt,
		&i.CacheExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Source,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const DeleteExpiredSnapshots = `-- name: DeleteExpiredSnapshots :exec
DELETE FROM snapshot_requests
WHERE "cacheExpiresAt" IS NOT NULL AND "cacheExpiresAt" < NOW()
`

func (q *Queries) DeleteExpiredSnapshots(ctx context.Context) error {
	_, err := q.db.Exec(ctx, DeleteExpiredSnapshots)
	return err
}

const GetAllReportPacksByUserID = `-- name: GetAllReportPacksByUserID :many
SELECT id, "userId", "totalReports", "usedReports", "purchasedAt", "stripePaymentId", "lastUsedAt", "consumptionHistory", "createdAt", "updatedAt" FROM report_packs
WHERE "userId" = $1
ORDER BY "purchasedAt" DESC
`

func (q *Queries) GetAllReportPacksByUserID(ctx context.Context, userid string) ([]ReportPack, error) {
	rows, err := q.db.Query(ctx, GetAllReportPacksByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportPack{}
	for rows.Next() {
		var i ReportPack
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.TotalReports,
			&i.UsedReports,
			&i.PurchasedAt,
			&i.StripePaymentId,
			&i.LastUsedAt,
			&i.ConsumptionHistory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetInsightAccessByID = `-- name: GetInsightAccessByID :one


SELECT id, "userId", tier, "billingFrequency", "reportsPerPeriod", "reportsPerYear", "reportsUsed", "rolloverReports", "lastRolloverDate", "periodStartDate", "periodEndDate", "startDate", "endDate", "stripeSubId", "stripePriceId", status, "lastReportGeneratedAt", "consumptionHistory", "createdAt", "updatedAt" FROM insight_access WHERE id = $1
`

// Reports and Entitlements Queries
// InsightAccess Queries
func (q *Queries) GetInsightAccessByID(ctx context.Context, id string) (InsightAccess, error) {
	row := q.db.QueryRow(ctx, GetInsightAccessByID, id)
	var i InsightAccess
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Tier,
		&i.BillingFrequency,
		&i.ReportsPerPeriod,
		&i.ReportsPerYear,
		&i.ReportsUsed,
		&i.RolloverReports,
		&i.LastRolloverDate,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.StartDate,
		&i.EndDate,
		&i.StripeSubId,
		&i.StripePriceId,
		&i.Status,
		&i.LastReportGeneratedAt,
		&i.ConsumptionHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetInsightAccessByStripeSubID = `-- name: GetInsightAccessByStripeSubID :one
SELECT id, "userId", tier, "billingFrequency", "reportsPerPeriod", "reportsPerYear", "reportsUsed", "rolloverReports", "lastRolloverDate", "periodStartDate", "periodEndDate", "startDate", "endDate", "stripeSubId", "stripePriceId", status, "lastReportGeneratedAt", "consumptionHistory", "createdAt", "updatedAt" FROM insight_access WHERE "stripeSubId" = $1
`

func (q *Queries) GetInsightAccessByStripeSubID(ctx context.Context, stripesubid pgtype.Text) (InsightAccess, error) {
	row := q.db.QueryRow(ctx, GetInsightAccessByStripeSubID, stripesubid)
	var i InsightAccess
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Tier,
		&i.BillingFrequency,
		&i.ReportsPerPeriod,
		&i.ReportsPerYear,
		&i.ReportsUsed,
		&i.RolloverReports,
		&i.LastRolloverDate,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.StartDate,
		&i.EndDate,
		&i.StripeSubId,
		&i.StripePriceId,
		&i.Status,
		&i.LastReportGeneratedAt,
		&i.ConsumptionHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetInsightAccessByUserID = `-- name: GetInsightAccessByUserID :one
SELECT id, "userId", tier, "billingFrequency", "reportsPerPeriod", "reportsPerYear", "reportsUsed", "rolloverReports", "lastRolloverDate", "periodStartDate", "periodEndDate", "startDate", "endDate", "stripeSubId", "stripePriceId", status, "lastReportGeneratedAt", "consumptionHistory", "createdAt", "updatedAt" FROM insight_access WHERE "userId" = $1 AND status = 'ACTIVE'
`

func (q *Queries) GetInsightAccessByUserID(ctx context.Context, userid string) (InsightAccess, error) {
	row := q.db.QueryRow(ctx, GetInsightAccessByUserID, userid)
	var i InsightAccess
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Tier,
		&i.BillingFrequency,
		&i.ReportsPerPeriod,
		&i.ReportsPerYear,
		&i.ReportsUsed,
		&i.RolloverReports,
		&i.LastRolloverDate,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.StartDate,
		&i.EndDate,
		&i.StripeSubId,
		&i.StripePriceId,
		&i.Status,
		&i.LastReportGeneratedAt,
		&i.ConsumptionHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetInvestorReportByCacheKey = `-- name: GetInvestorReportByCacheKey :one
SELECT id, "userId", email, "propertyId", "propertyAddress", type, status, "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId", "investmentCriteria", "metricsData", "narrativeData", "fullReport", "pdfUrl", "generationCost", "generationTimeMs", "allocationDecrementedAt", "allocationSnapshot", "cacheKey", "criteriaHash", "cachedFromId", "supersededById", "supersededAt", "createdAt", "completedAt", "expiresAt" FROM investor_reports
WHERE "cacheKey" = $1 AND status = 'COMPLETE'
`

func (q *Queries) GetInvestorReportByCacheKey(ctx context.Context, cachekey pgtype.Text) (InvestorReport, error) {
	row := q.db.QueryRow(ctx, GetInvestorReportByCacheKey, cachekey)
	var i InvestorReport
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Email,
		&i.PropertyId,
		&i.PropertyAddress,
		&i.Type,
		&i.Status,
		&i.SourceType,
		&i.SourcePackId,
		&i.SourceAccessId,
		&i.StripePaymentId,
		&i.InvestmentCriteria,
		&i.MetricsData,
		&i.NarrativeData,
		&i.FullReport,
		&i.PdfUrl,
		&i.GenerationCost,
		&i.GenerationTimeMs,
		&i.AllocationDecrementedAt,
		&i.AllocationSnapshot,
		&i.CacheKey,
		&i.CriteriaHash,
		&i.CachedFromId,
		&i.SupersededById,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const GetInvestorReportByCriteriaHash = `-- name: GetInvestorReportByCriteriaHash :one
SELECT id, "userId", email, "propertyId", "propertyAddress", type, status, "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId", "investmentCriteria", "metricsData", "narrativeData", "fullReport", "pdfUrl", "generationCost", "generationTimeMs", "allocationDecrementedAt", "allocationSnapshot", "cacheKey", "criteriaHash", "cachedFromId", "supersededById", "supersededAt", "createdAt", "completedAt", "expiresAt" FROM investor_reports
WHERE "criteriaHash" = $1 AND status = 'COMPLETE' AND "supersededAt" IS NULL
ORDER BY "createdAt" DESC
LIMIT 1
`

func (q *Queries) GetInvestorReportByCriteriaHash(ctx context.Context, criteriahash pgtype.Text) (InvestorReport, error) {
	row := q.db.QueryRow(ctx, GetInvestorReportByCriteriaHash, criteriahash)
	var i InvestorReport
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Email,
		&i.PropertyId,
		&i.PropertyAddress,
		&i.Type,
		&i.Status,
		&i.SourceType,
		&i.SourcePackId,
		&i.SourceAccessId,
		&i.StripePaymentId,
		&i.InvestmentCriteria,
		&i.MetricsData,
		&i.NarrativeData,
		&i.FullReport,
		&i.PdfUrl,
		&i.GenerationCost,
		&i.GenerationTimeMs,
		&i.AllocationDecrementedAt,
		&i.AllocationSnapshot,
		&i.CacheKey,
		&i.CriteriaHash,
		&i.CachedFromId,
		&i.SupersededById,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const GetInvestorReportByID = `-- name: GetInvestorReportByID :one

SELECT id, "userId", email, "propertyId", "propertyAddress", type, status, "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId", "investmentCriteria", "metricsData", "narrativeData", "fullReport", "pdfUrl", "generationCost", "generationTimeMs", "allocationDecrementedAt", "allocationSnapshot", "cacheKey", "criteriaHash", "cachedFromId", "supersededById", "supersededAt", "createdAt", "completedAt", "expiresAt" FROM investor_reports WHERE id = $1
`

// InvestorReport Queries
func (q *Queries) GetInvestorReportByID(ctx context.Context, id string) (InvestorReport, error) {
	row := q.db.QueryRow(ctx, GetInvestorReportByID, id)
	var i InvestorReport
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Email,
		&i.PropertyId,
		&i.PropertyAddress,
		&i.Type,
		&i.Status,
		&i.SourceType,
		&i.SourcePackId,
		&i.SourceAccessId,
		&i.StripePaymentId,
		&i.InvestmentCriteria,
		&i.MetricsData,
		&i.NarrativeData,
		&i.FullReport,
		&i.PdfUrl,
		&i.GenerationCost,
		&i.GenerationTimeMs,
		&i.AllocationDecrementedAt,
		&i.AllocationSnapshot,
		&i.CacheKey,
		&i.CriteriaHash,
		&i.CachedFromId,
		&i.SupersededById,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const GetInvestorReportByIDAndUser = `-- name: GetInvestorReportByIDAndUser :one
SELECT id, "userId", email, "propertyId", "propertyAddress", type, status, "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId", "investmentCriteria", "metricsData", "narrativeData", "fullReport", "pdfUrl", "generationCost", "generationTimeMs", "allocationDecrementedAt", "allocationSnapshot", "cacheKey", "criteriaHash", "cachedFromId", "supersededById", "supersededAt", "createdAt", "completedAt", "expiresAt" FROM investor_reports WHERE id = $1 AND "userId" = $2
`

type GetInvestorReportByIDAndUserParams struct {
	ID     string      `json:"id"`
	UserId pgtype.Text `json:"userId"`
}

func (q *Queries) GetInvestorReportByIDAndUser(ctx context.Context, arg GetInvestorReportByIDAndUserParams) (InvestorReport, error) {
	row := q.db.QueryRow(ctx, GetInvestorReportByIDAndUser, arg.ID, arg.UserId)
	var i InvestorReport
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Email,
		&i.PropertyId,
		&i.PropertyAddress,
		&i.Type,
		&i.Status,
		&i.SourceType,
		&i.SourcePackId,
		&i.SourceAccessId,
		&i.StripePaymentId,
		&i.InvestmentCriteria,
		&i.MetricsData,
		&i.NarrativeData,
		&i.FullReport,
		&i.PdfUrl,
		&i.GenerationCost,
		&i.GenerationTimeMs,
		&i.AllocationDecrementedAt,
		&i.AllocationSnapshot,
		&i.CacheKey,
		&i.CriteriaHash,
		&i.CachedFromId,
		&i.SupersededById,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const GetLatestSnapshotByEmail = `-- name: GetLatestSnapshotByEmail :one
SELECT id, "sessionId", "userId", email, criteria, "criteriaHash", location, status, "snapshotNumber", "propertiesFound", properties, "resultId", "cacheKey", "cachedAt", "cacheExpiresAt", "ipAddress", "userAgent", source, "createdAt", "completedAt", "convertedAt" FROM snapshot_requests
WHERE email = $1
ORDER BY "createdAt" DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshotByEmail(ctx context.Context, email pgtype.Text) (SnapshotRequest, error) {
	row := q.db.QueryRow(ctx, GetLatestSnapshotByEmail, email)
	var i SnapshotRequest
	err := row.Scan(
		&i.ID,
		&i.SessionId,
		&i.UserId,
		&i.Email,
		&i.Criteria,
		&i.CriteriaHash,
		&i.Location,
		&i.Status,
		&i.SnapshotNumber,
		&i.PropertiesFound,
		&i.Properties,
		&i.ResultId,
		&i.CacheKey,
		&i.CachedAt,
		&i.CacheExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Source,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const GetPendingInvestorReports = `-- name: GetPendingInvestorReports :many
SELECT id, "userId", email, "propertyId", "propertyAddress", type, status, "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId", "investmentCriteria", "metricsData", "narrativeData", "fullReport", "pdfUrl", "generationCost", "generationTimeMs", "allocationDecrementedAt", "allocationSnapshot", "cacheKey", "criteriaHash", "cachedFromId", "supersededById", "supersededAt", "createdAt", "completedAt", "expiresAt" FROM investor_reports
WHERE status = 'PENDING' OR status = 'GENERATING'
ORDER BY "createdAt" ASC
LIMIT $1
`

func (q *Queries) GetPendingInvestorReports(ctx context.Context, limit int32) ([]InvestorReport, error) {
	rows, err := q.db.Query(ctx, GetPendingInvestorReports, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvestorReport{}
	for rows.Next() {
		var i InvestorReport
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Email,
			&i.PropertyId,
			&i.PropertyAddress,
			&i.Type,
			&i.Status,
			&i.SourceType,
			&i.SourcePackId,
			&i.SourceAccessId,
			&i.StripePaymentId,
			&i.InvestmentCriteria,
			&i.MetricsData,
			&i.NarrativeData,
			&i.FullReport,
			&i.PdfUrl,
			&i.GenerationCost,
			&i.GenerationTimeMs,
			&i.AllocationDecrementedAt,
			&i.AllocationSnapshot,
			&i.CacheKey,
			&i.CriteriaHash,
			&i.CachedFromId,
			&i.SupersededById,
			&i.SupersededAt,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetReportPackByID = `-- name: GetReportPackByID :one

SELECT id, "userId", "totalReports", "usedReports", "purchasedAt", "stripePaymentId", "lastUsedAt", "consumptionHistory", "createdAt", "updatedAt" FROM report_packs WHERE id = $1
`

// ReportPack Queries
func (q *Queries) GetReportPackByID(ctx context.Context, id string) (ReportPack, error) {
	row := q.db.QueryRow(ctx, GetReportPackByID, id)
	var i ReportPack
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.TotalReports,
		&i.UsedReports,
		&i.PurchasedAt,
		&i.StripePaymentId,
		&i.LastUsedAt,
		&i.ConsumptionHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetReportPacksByUserID = `-- name: GetReportPacksByUserID :many
SELECT id, "userId", "totalReports", "usedReports", "purchasedAt", "stripePaymentId", "lastUsedAt", "consumptionHistory", "createdAt", "updatedAt" FROM report_packs
WHERE "userId" = $1 AND "usedReports" < "totalReports"
ORDER BY "purchasedAt" ASC
`

func (q *Queries) GetReportPacksByUserID(ctx context.Context, userid string) ([]ReportPack, error) {
	rows, err := q.db.Query(ctx, GetReportPacksByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportPack{}
	for rows.Next() {
		var i ReportPack
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.TotalReports,
			&i.UsedReports,
			&i.PurchasedAt,
			&i.StripePaymentId,
			&i.LastUsedAt,
			&i.ConsumptionHistory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSnapshotByCacheKey = `-- name: GetSnapshotByCacheKey :one
SELECT id, "sessionId", "userId", email, criteria, "criteriaHash", location, status, "snapshotNumber", "propertiesFound", properties, "resultId", "cacheKey", "cachedAt", "cacheExpiresAt", "ipAddress", "userAgent", source, "createdAt", "completedAt", "convertedAt" FROM snapshot_requests
WHERE "cacheKey" = $1 AND status = 'COMPLETE' AND ("cacheExpiresAt" IS NULL OR "cacheExpiresAt" > NOW())
`

func (q *Queries) GetSnapshotByCacheKey(ctx context.Context, cachekey pgtype.Text) (SnapshotRequest, error) {
	row := q.db.QueryRow(ctx, GetSnapshotByCacheKey, cachekey)
	var i SnapshotRequest
	err := row.Scan(
		&i.ID,
		&i.SessionId,
		&i.UserId,
		&i.Email,
		&i.Criteria,
		&i.CriteriaHash,
		&i.Location,
		&i.Status,
		&i.SnapshotNumber,
		&i.PropertiesFound,
		&i.Properties,
		&i.ResultId,
		&i.CacheKey,
		&i.CachedAt,
		&i.CacheExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Source,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const GetSnapshotRequestByID = `-- name: GetSnapshotRequestByID :one

SELECT id, "sessionId", "userId", email, criteria, "criteriaHash", location, status, "snapshotNumber", "propertiesFound", properties, "resultId", "cacheKey", "cachedAt", "cacheExpiresAt", "ipAddress", "userAgent", source, "createdAt", "completedAt", "convertedAt" FROM snapshot_requests WHERE id = $1
`

// SnapshotRequest Queries
func (q *Queries) GetSnapshotRequestByID(ctx context.Context, id string) (SnapshotRequest, error) {
	row := q.db.QueryRow(ctx, GetSnapshotRequestByID, id)
	var i SnapshotRequest
	err := row.Scan(
		&i.ID,
		&i.SessionId,
		&i.UserId,
		&i.Email,
		&i.Criteria,
		&i.CriteriaHash,
		&i.Location,
		&i.Status,
		&i.SnapshotNumber,
		&i.PropertiesFound,
		&i.Properties,
		&i.ResultId,
		&i.CacheKey,
		&i.CachedAt,
		&i.CacheExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Source,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const GetSnapshotRequestBySessionID = `-- name: GetSnapshotRequestBySessionID :one
SELECT id, "sessionId", "userId", email, criteria, "criteriaHash", location, status, "snapshotNumber", "propertiesFound", properties, "resultId", "cacheKey", "cachedAt", "cacheExpiresAt", "ipAddress", "userAgent", source, "createdAt", "completedAt", "convertedAt" FROM snapshot_requests
WHERE "sessionId" = $1
ORDER BY "createdAt" DESC
LIMIT 1
`

func (q *Queries) GetSnapshotRequestBySessionID(ctx context.Context, sessionid string) (SnapshotRequest, error) {
	row := q.db.QueryRow(ctx, GetSnapshotRequestBySessionID, sessionid)
	var i SnapshotRequest
	err := row.Scan(
		&i.ID,
		&i.SessionId,
		&i.UserId,
		&i.Email,
		&i.Criteria,
		&i.CriteriaHash,
		&i.Location,
		&i.Status,
		&i.SnapshotNumber,
		&i.PropertiesFound,
		&i.Properties,
		&i.ResultId,
		&i.CacheKey,
		&i.CachedAt,
		&i.CacheExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Source,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const IncrementInsightAccessUsage = `-- name: IncrementInsightAccessUsage :one
UPDATE insight_access SET
    "reportsUsed" = "reportsUsed" + 1,
    "lastReportGeneratedAt" = NOW(),
    "updatedAt" = NOW()
WHERE id = $1
RETURNING id, "userId", tier, "billingFrequency", "reportsPerPeriod", "reportsPerYear", "reportsUsed", "rolloverReports", "lastRolloverDate", "periodStartDate", "periodEndDate", "startDate", "endDate", "stripeSubId", "stripePriceId", status, "lastReportGeneratedAt", "consumptionHistory", "createdAt", "updatedAt"
`

func (q *Queries) IncrementInsightAccessUsage(ctx context.Context, id string) (InsightAccess, error) {
	row := q.db.QueryRow(ctx, IncrementInsightAccessUsage, id)
	var i InsightAccess
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Tier,
		&i.BillingFrequency,
		&i.ReportsPerPeriod,
		&i.ReportsPerYear,
		&i.ReportsUsed,
		&i.RolloverReports,
		&i.LastRolloverDate,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.StartDate,
		&i.EndDate,
		&i.StripeSubId,
		&i.StripePriceId,
		&i.Status,
		&i.LastReportGeneratedAt,
		&i.ConsumptionHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const IncrementReportPackUsage = `-- name: IncrementReportPackUsage :one
UPDATE report_packs SET
    "usedReports" = "usedReports" + 1,
    "lastUsedAt" = NOW(),
    "updatedAt" = NOW()
WHERE id = $1
RETURNING id, "userId", "totalReports", "usedReports", "purchasedAt", "stripePaymentId", "lastUsedAt", "consumptionHistory", "createdAt", "updatedAt"
`

func (q *Queries) IncrementReportPackUsage(ctx context.Context, id string) (ReportPack, error) {
	row := q.db.QueryRow(ctx, IncrementReportPackUsage, id)
	var i ReportPack
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.TotalReports,
		&i.UsedReports,
		&i.PurchasedAt,
		&i.StripePaymentId,
		&i.LastUsedAt,
		&i.ConsumptionHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListExpiringInsightAccess = `-- name: ListExpiringInsightAccess :many
SELECT id, "userId", tier, "billingFrequency", "reportsPerPeriod", "reportsPerYear", "reportsUsed", "rolloverReports", "lastRolloverDate", "periodStartDate", "periodEndDate", "startDate", "endDate", "stripeSubId", "stripePriceId", status, "lastReportGeneratedAt", "consumptionHistory", "createdAt", "updatedAt" FROM insight_access
WHERE status = 'ACTIVE' AND "periodEndDate" <= $1
ORDER BY "periodEndDate" ASC
`

func (q *Queries) ListExpiringInsightAccess(ctx context.Context, periodenddate pgtype.Timestamp) ([]InsightAccess, error) {
	rows, err := q.db.Query(ctx, ListExpiringInsightAccess, periodenddate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightAccess{}
	for rows.Next() {
		var i InsightAccess
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Tier,
			&i.BillingFrequency,
			&i.ReportsPerPeriod,
			&i.ReportsPerYear,
			&i.ReportsUsed,
			&i.RolloverReports,
			&i.LastRolloverDate,
			&i.PeriodStartDate,
			&i.PeriodEndDate,
			&i.StartDate,
			&i.EndDate,
			&i.StripeSubId,
			&i.StripePriceId,
			&i.Status,
			&i.LastReportGeneratedAt,
			&i.ConsumptionHistory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUserInvestorReports = `-- name: ListUserInvestorReports :many
SELECT id, "userId", email, "propertyId", "propertyAddress", type, status, "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId", "investmentCriteria", "metricsData", "narrativeData", "fullReport", "pdfUrl", "generationCost", "generationTimeMs", "allocationDecrementedAt", "allocationSnapshot", "cacheKey", "criteriaHash", "cachedFromId", "supersededById", "supersededAt", "createdAt", "completedAt", "expiresAt" FROM investor_reports
WHERE "userId" = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListUserInvestorReportsParams struct {
	UserId pgtype.Text `json:"userId"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUserInvestorReports(ctx context.Context, arg ListUserInvestorReportsParams) ([]InvestorReport, error) {
	rows, err := q.db.Query(ctx, ListUserInvestorReports, arg.UserId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvestorReport{}
	for rows.Next() {
		var i InvestorReport
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Email,
			&i.PropertyId,
			&i.PropertyAddress,
			&i.Type,
			&i.Status,
			&i.SourceType,
			&i.SourcePackId,
			&i.SourceAccessId,
			&i.StripePaymentId,
			&i.InvestmentCriteria,
			&i.MetricsData,
			&i.NarrativeData,
			&i.FullReport,
			&i.PdfUrl,
			&i.GenerationCost,
			&i.GenerationTimeMs,
			&i.AllocationDecrementedAt,
			&i.AllocationSnapshot,
			&i.CacheKey,
			&i.CriteriaHash,
			&i.CachedFromId,
			&i.SupersededById,
			&i.SupersededAt,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUserInvestorReportsByStatus = `-- name: ListUserInvestorReportsByStatus :many
SELECT id, "userId", email, "propertyId", "propertyAddress", type, status, "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId", "investmentCriteria", "metricsData", "narrativeData", "fullReport", "pdfUrl", "generationCost", "generationTimeMs", "allocationDecrementedAt", "allocationSnapshot", "cacheKey", "criteriaHash", "cachedFromId", "supersededById", "supersededAt", "createdAt", "completedAt", "expiresAt" FROM investor_reports
WHERE "userId" = $1 AND status = $2
ORDER BY "createdAt" DESC
LIMIT $3 OFFSET $4
`

type ListUserInvestorReportsByStatusParams struct {
	UserId pgtype.Text `json:"userId"`
	Status interface{} `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUserInvestorReportsByStatus(ctx context.Context, arg ListUserInvestorReportsByStatusParams) ([]InvestorReport, error) {
	rows, err := q.db.Query(ctx, ListUserInvestorReportsByStatus,
		arg.UserId,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvestorReport{}
	for rows.Next() {
		var i InvestorReport
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Email,
			&i.PropertyId,
			&i.PropertyAddress,
			&i.Type,
			&i.Status,
			&i.SourceType,
			&i.SourcePackId,
			&i.SourceAccessId,
			&i.StripePaymentId,
			&i.InvestmentCriteria,
			&i.MetricsData,
			&i.NarrativeData,
			&i.FullReport,
			&i.PdfUrl,
			&i.GenerationCost,
			&i.GenerationTimeMs,
			&i.AllocationDecrementedAt,
			&i.AllocationSnapshot,
			&i.CacheKey,
			&i.CriteriaHash,
			&i.CachedFromId,
			&i.SupersededById,
			&i.SupersededAt,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUserSnapshots = `-- name: ListUserSnapshots :many
SELECT id, "sessionId", "userId", email, criteria, "criteriaHash", location, status, "snapshotNumber", "propertiesFound", properties, "resultId", "cacheKey", "cachedAt", "cacheExpiresAt", "ipAddress", "userAgent", source, "createdAt", "completedAt", "convertedAt" FROM snapshot_requests
WHERE "userId" = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListUserSnapshotsParams struct {
	UserId pgtype.Text `json:"userId"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUserSnapshots(ctx context.Context, arg ListUserSnapshotsParams) ([]SnapshotRequest, error) {
	rows, err := q.db.Query(ctx, ListUserSnapshots, arg.UserId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SnapshotRequest{}
	for rows.Next() {
		var i SnapshotRequest
		if err := rows.Scan(
			&i.ID,
			&i.SessionId,
			&i.UserId,
			&i.Email,
			&i.Criteria,
			&i.CriteriaHash,
			&i.Location,
			&i.Status,
			&i.SnapshotNumber,
			&i.PropertiesFound,
			&i.Properties,
			&i.ResultId,
			&i.CacheKey,
			&i.CachedAt,
			&i.CacheExpiresAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Source,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ConvertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkSnapshotConverted = `-- name: MarkSnapshotConverted :one
UPDATE snapshot_requests SET
    status = 'CONVERTED',
    "convertedAt" = NOW()
WHERE id = $1
RETURNING id, "sessionId", "userId", email, criteria, "criteriaHash", location, status, "snapshotNumber", "propertiesFound", properties, "resultId", "cacheKey", "cachedAt", "cacheExpiresAt", "ipAddress", "userAgent", source, "createdAt", "completedAt", "convertedAt"
`

func (q *Queries) MarkSnapshotConverted(ctx context.Context, id string) (SnapshotRequest, error) {
	row := q.db.QueryRow(ctx, MarkSnapshotConverted, id)
	var i SnapshotRequest
	err := row.Scan(
		&i.ID,
		&i.SessionId,
		&i.UserId,
		&i.Email,
		&i.Criteria,
		&i.CriteriaHash,
		&i.Location,
		&i.Status,
		&i.SnapshotNumber,
		&i.PropertiesFound,
		&i.Properties,
		&i.ResultId,
		&i.CacheKey,
		&i.CachedAt,
		&i.CacheExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Source,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const SupersedeInvestorReport = `-- name: SupersedeInvestorReport :exec
UPDATE investor_reports SET
    "supersededById" = $2,
    "supersededAt" = NOW()
WHERE id = $1
`

type SupersedeInvestorReportParams struct {
	ID             string      `json:"id"`
	SupersededById pgtype.Text `json:"supersededById"`
}

func (q *Queries) SupersedeInvestorReport(ctx context.Context, arg SupersedeInvestorReportParams) error {
	_, err := q.db.Exec(ctx, SupersedeInvestorReport, arg.ID, arg.SupersededById)
	return err
}

const UpdateInsightAccess = `-- name: UpdateInsightAccess :one
UPDATE insight_access SET
    tier = COALESCE($2, tier),
    "billingFrequency" = COALESCE($3, "billingFrequency"),
    "reportsPerPeriod" = COALESCE($4, "reportsPerPeriod"),
    "reportsUsed" = COALESCE($5, "reportsUsed"),
    "rolloverReports" = COALESCE($6, "rolloverReports"),
    "lastRolloverDate" = COALESCE($7, "lastRolloverDate"),
    "periodStartDate" = COALESCE($8, "periodStartDate"),
    "periodEndDate" = COALESCE($9, "periodEndDate"),
    status = COALESCE($10, status),
    "lastReportGeneratedAt" = COALESCE($11, "lastReportGeneratedAt"),
    "consumptionHistory" = COALESCE($12, "consumptionHistory"),
    "updatedAt" = NOW()
WHERE id = $1
RETURNING id, "userId", tier, "billingFrequency", "reportsPerPeriod", "reportsPerYear", "reportsUsed", "rolloverReports", "lastRolloverDate", "periodStartDate", "periodEndDate", "startDate", "endDate", "stripeSubId", "stripePriceId", status, "lastReportGeneratedAt", "consumptionHistory", "createdAt", "updatedAt"
`

type UpdateInsightAccessParams struct {
	ID                    string           `json:"id"`
	Tier                  interface{}      `json:"tier"`
	BillingFrequency      interface{}      `json:"billingFrequency"`
	ReportsPerPeriod      int32            `json:"reportsPerPeriod"`
	ReportsUsed           int32            `json:"reportsUsed"`
	RolloverReports       int32            `json:"rolloverReports"`
	LastRolloverDate      pgtype.Timestamp `json:"lastRolloverDate"`
	PeriodStartDate       pgtype.Timestamp `json:"periodStartDate"`
	PeriodEndDate         pgtype.Timestamp `json:"periodEndDate"`
	Status                interface{}      `json:"status"`
	LastReportGeneratedAt pgtype.Timestamp `json:"lastReportGeneratedAt"`
	ConsumptionHistory    []byte           `json:"consumptionHistory"`
}

func (q *Queries) UpdateInsightAccess(ctx context.Context, arg UpdateInsightAccessParams) (InsightAccess, error) {
	row := q.db.QueryRow(ctx, UpdateInsightAccess,
		arg.ID,
		arg.Tier,
		arg.BillingFrequency,
		arg.ReportsPerPeriod,
		arg.ReportsUsed,
		arg.RolloverReports,
		arg.LastRolloverDate,
		arg.PeriodStartDate,
		arg.PeriodEndDate,
		arg.Status,
		arg.LastReportGeneratedAt,
		arg.ConsumptionHistory,
	)
	var i InsightAccess
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Tier,
		&i.BillingFrequency,
		&i.ReportsPerPeriod,
		&i.ReportsPerYear,
		&i.ReportsUsed,
		&i.RolloverReports,
		&i.LastRolloverDate,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.StartDate,
		&i.EndDate,
		&i.StripeSubId,
		&i.StripePriceId,
		&i.Status,
		&i.LastReportGeneratedAt,
		&i.ConsumptionHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateInvestorReportAllocation = `-- name: UpdateInvestorReportAllocation :exec
UPDATE investor_reports SET
    "allocationDecrementedAt" = NOW(),
    "allocationSnapshot" = $2
WHERE id = $1
`

type UpdateInvestorReportAllocationParams struct {
	ID                 string `json:"id"`
	AllocationSnapshot []byte `json:"allocationSnapshot"`
}

func (q *Queries) UpdateInvestorReportAllocation(ctx context.Context, arg UpdateInvestorReportAllocationParams) error {
	_, err := q.db.Exec(ctx, UpdateInvestorReportAllocation, arg.ID, arg.AllocationSnapshot)
	return err
}

const UpdateInvestorReportData = `-- name: UpdateInvestorReportData :one
UPDATE investor_reports SET
    "metricsData" = COALESCE($2, "metricsData"),
    "narrativeData" = COALESCE($3, "narrativeData"),
    "fullReport" = COALESCE($4, "fullReport"),
    "pdfUrl" = COALESCE($5, "pdfUrl"),
    "generationCost" = COALESCE($6, "generationCost"),
    "generationTimeMs" = COALESCE($7, "generationTimeMs"),
    status = COALESCE($8, status),
    "completedAt" = CASE WHEN $8 = 'COMPLETE' THEN NOW() ELSE "completedAt" END
WHERE id = $1
RETURNING id, "userId", email, "propertyId", "propertyAddress", type, status, "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId", "investmentCriteria", "metricsData", "narrativeData", "fullReport", "pdfUrl", "generationCost", "generationTimeMs", "allocationDecrementedAt", "allocationSnapshot", "cacheKey", "criteriaHash", "cachedFromId", "supersededById", "supersededAt", "createdAt", "completedAt", "expiresAt"
`

type UpdateInvestorReportDataParams struct {
	ID               string         `json:"id"`
	MetricsData      []byte         `json:"metricsData"`
	NarrativeData    []byte         `json:"narrativeData"`
	FullReport       pgtype.Text    `json:"fullReport"`
	PdfUrl           pgtype.Text    `json:"pdfUrl"`
	GenerationCost   pgtype.Numeric `json:"generationCost"`
	GenerationTimeMs pgtype.Int4    `json:"generationTimeMs"`
	Status           interface{}    `json:"status"`
}

func (q *Queries) UpdateInvestorReportData(ctx context.Context, arg UpdateInvestorReportDataParams) (InvestorReport, error) {
	row := q.db.QueryRow(ctx, UpdateInvestorReportData,
		arg.ID,
		arg.MetricsData,
		arg.NarrativeData,
		arg.FullReport,
		arg.PdfUrl,
		arg.GenerationCost,
		arg.GenerationTimeMs,
		arg.Status,
	)
	var i InvestorReport
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Email,
		&i.PropertyId,
		&i.PropertyAddress,
		&i.Type,
		&i.Status,
		&i.SourceType,
		&i.SourcePackId,
		&i.SourceAccessId,
		&i.StripePaymentId,
		&i.InvestmentCriteria,
		&i.MetricsData,
		&i.NarrativeData,
		&i.FullReport,
		&i.PdfUrl,
		&i.GenerationCost,
		&i.GenerationTimeMs,
		&i.AllocationDecrementedAt,
		&i.AllocationSnapshot,
		&i.CacheKey,
		&i.CriteriaHash,
		&i.CachedFromId,
		&i.SupersededById,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const UpdateInvestorReportStatus = `-- name: UpdateInvestorReportStatus :one
UPDATE investor_reports SET
    status = $2,
    "completedAt" = CASE WHEN $2 = 'COMPLETE' THEN NOW() ELSE "completedAt" END
WHERE id = $1
RETURNING id, "userId", email, "propertyId", "propertyAddress", type, status, "sourceType", "sourcePackId", "sourceAccessId", "stripePaymentId", "investmentCriteria", "metricsData", "narrativeData", "fullReport", "pdfUrl", "generationCost", "generationTimeMs", "allocationDecrementedAt", "allocationSnapshot", "cacheKey", "criteriaHash", "cachedFromId", "supersededById", "supersededAt", "createdAt", "completedAt", "expiresAt"
`

type UpdateInvestorReportStatusParams struct {
	ID     string      `json:"id"`
	Status interface{} `json:"status"`
}

func (q *Queries) UpdateInvestorReportStatus(ctx context.Context, arg UpdateInvestorReportStatusParams) (InvestorReport, error) {
	row := q.db.QueryRow(ctx, UpdateInvestorReportStatus, arg.ID, arg.Status)
	var i InvestorReport
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Email,
		&i.PropertyId,
		&i.PropertyAddress,
		&i.Type,
		&i.Status,
		&i.SourceType,
		&i.SourcePackId,
		&i.SourceAccessId,
		&i.StripePaymentId,
		&i.InvestmentCriteria,
		&i.MetricsData,
		&i.NarrativeData,
		&i.FullReport,
		&i.PdfUrl,
		&i.GenerationCost,
		&i.GenerationTimeMs,
		&i.AllocationDecrementedAt,
		&i.AllocationSnapshot,
		&i.CacheKey,
		&i.CriteriaHash,
		&i.CachedFromId,
		&i.SupersededById,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const UpdateReportPackConsumptionHistory = `-- name: UpdateReportPackConsumptionHistory :exec
UPDATE report_packs SET
    "consumptionHistory" = $2,
    "updatedAt" = NOW()
WHERE id = $1
`

type UpdateReportPackConsumptionHistoryParams struct {
	ID                 string `json:"id"`
	ConsumptionHistory []byte `json:"consumptionHistory"`
}

func (q *Queries) UpdateReportPackConsumptionHistory(ctx context.Context, arg UpdateReportPackConsumptionHistoryParams) error {
	_, err := q.db.Exec(ctx, UpdateReportPackConsumptionHistory, arg.ID, arg.ConsumptionHistory)
	return err
}

const UpdateSnapshotRequestResults = `-- name: UpdateSnapshotRequestResults :one
UPDATE snapshot_requests SET
    status = 'COMPLETE',
    "propertiesFound" = $2,
    properties = $3,
    "resultId" = $4,
    "cacheKey" = $5,
    "cachedAt" = NOW(),
    "cacheExpiresAt" = $6,
    "completedAt" = NOW()
WHERE id = $1
RETURNING id, "sessionId", "userId", email, criteria, "criteriaHash", location, status, "snapshotNumber", "propertiesFound", properties, "resultId", "cacheKey", "cachedAt", "cacheExpiresAt", "ipAddress", "userAgent", source, "createdAt", "completedAt", "convertedAt"
`

type UpdateSnapshotRequestResultsParams struct {
	ID              string           `json:"id"`
	PropertiesFound int32            `json:"propertiesFound"`
	Properties      []byte           `json:"properties"`
	ResultId        pgtype.Text      `json:"resultId"`
	CacheKey        pgtype.Text      `json:"cacheKey"`
	CacheExpiresAt  pgtype.Timestamp `json:"cacheExpiresAt"`
}

func (q *Queries) UpdateSnapshotRequestResults(ctx context.Context, arg UpdateSnapshotRequestResultsParams) (SnapshotRequest, error) {
	row := q.db.QueryRow(ctx, UpdateSnapshotRequestResults,
		arg.ID,
		arg.PropertiesFound,
		arg.Properties,
		arg.ResultId,
		arg.CacheKey,
		arg.CacheExpiresAt,
	)
	var i SnapshotRequest
	err := row.Scan(
		&i.ID,
		&i.SessionId,
		&i.UserId,
		&i.Email,
		&i.Criteria,
		&i.CriteriaHash,
		&i.Location,
		&i.Status,
		&i.SnapshotNumber,
		&i.PropertiesFound,
		&i.Properties,
		&i.ResultId,
		&i.CacheKey,
		&i.CachedAt,
		&i.CacheExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Source,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ConvertedAt,
	)
	return i, err
}

const UpdateSnapshotRequestStatus = `-- name: UpdateSnapshotRequestStatus :one
UPDATE snapshot_requests SET
    status = $2,
    "completedAt" = CASE WHEN $2 = 'COMPLETE' THEN NOW() ELSE "completedAt" END
WHERE id = $1
RETURNING id, "sessionId", "userId", email, criteria, "criteriaHash", location, status, "snapshotNumber", "propertiesFound", properties, "resultId", "cacheKey", "cachedAt", "cacheExpiresAt", "ipAddress", "userAgent", source, "createdAt", "completedAt", "convertedAt"
`

type UpdateSnapshotRequestStatusParams struct {
	ID     string      `json:"id"`
	Status interface{} `json:"status"`
}

func (q *Queries) UpdateSnapshotRequestStatus(ctx context.Context, arg UpdateSnapshotRequestStatusParams) (SnapshotRequest, error) {
	row := q.db.QueryRow(ctx, UpdateSnapshotRequestStatus, arg.ID, arg.Status)
	var i SnapshotRequest
	err := row.Scan(
		&i.ID,
		&i.SessionId,
		&i.UserId,
		&i.Email,
		&i.Criteria,
		&i.CriteriaHash,
		&i.Location,
		&i.Status,
		&i.SnapshotNumber,
		&i.PropertiesFound,
		&i.Properties,
		&i.ResultId,
		&i.CacheKey,
		&i.CachedAt,
		&i.CacheExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Source,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ConvertedAt,
	)
	return i, err
}
