// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_cache.sql

package queries

import (
	"context"
	"encoding/json"
	"time"
)

const DeleteExpiredSystemCache = `-- name: DeleteExpiredSystemCache :execrows
DELETE FROM system_cache WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSystemCache(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredSystemCache)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteSystemCache = `-- name: DeleteSystemCache :exec
DELETE FROM system_cache WHERE key = $1
`

func (q *Queries) DeleteSystemCache(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, DeleteSystemCache, key)
	return err
}

const GetSystemCache = `-- name: GetSystemCache :one

SELECT key, value, expires_at, created_at, updated_at FROM system_cache
WHERE key = $1 AND expires_at > NOW()
`

// System Cache Queries
// For global data like FRED economic rates (not user-specific)
func (q *Queries) GetSystemCache(ctx context.Context, key string) (SystemCache, error) {
	row := q.db.QueryRow(ctx, GetSystemCache, key)
	var i SystemCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetSystemCacheIgnoreExpiry = `-- name: GetSystemCacheIgnoreExpiry :one
SELECT key, value, expires_at, created_at, updated_at FROM system_cache
WHERE key = $1
`

// Used when we want stale data as fallback
func (q *Queries) GetSystemCacheIgnoreExpiry(ctx context.Context, key string) (SystemCache, error) {
	row := q.db.QueryRow(ctx, GetSystemCacheIgnoreExpiry, key)
	var i SystemCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetSystemCacheStats = `-- name: GetSystemCacheStats :one
SELECT
    COUNT(*) as total_entries,
    COUNT(*) FILTER (WHERE expires_at > NOW()) as valid_entries,
    COUNT(*) FILTER (WHERE expires_at <= NOW()) as expired_entries
FROM system_cache
`

type GetSystemCacheStatsRow struct {
	TotalEntries   int64 `json:"total_entries"`
	ValidEntries   int64 `json:"valid_entries"`
	ExpiredEntries int64 `json:"expired_entries"`
}

func (q *Queries) GetSystemCacheStats(ctx context.Context) (GetSystemCacheStatsRow, error) {
	row := q.db.QueryRow(ctx, GetSystemCacheStats)
	var i GetSystemCacheStatsRow
	err := row.Scan(&i.TotalEntries, &i.ValidEntries, &i.ExpiredEntries)
	return i, err
}

const UpsertSystemCache = `-- name: UpsertSystemCache :one
INSERT INTO system_cache (key, value, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    expires_at = EXCLUDED.expires_at,
    updated_at = NOW()
RETURNING key, value, expires_at, created_at, updated_at
`

type UpsertSystemCacheParams struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	ExpiresAt time.Time       `json:"expires_at"`
}

func (q *Queries) UpsertSystemCache(ctx context.Context, arg UpsertSystemCacheParams) (SystemCache, error) {
	row := q.db.QueryRow(ctx, UpsertSystemCache, arg.Key, arg.Value, arg.ExpiresAt)
	var i SystemCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
