// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_activity.sql

package queries

import (
	"context"
	"time"
)

const CountUserActivityByLocation = `-- name: CountUserActivityByLocation :one
SELECT COUNT(*) FROM user_location_activity
WHERE user_id = $1
  AND location = $2
`

type CountUserActivityByLocationParams struct {
	UserID   string `json:"user_id"`
	Location string `json:"location"`
}

func (q *Queries) CountUserActivityByLocation(ctx context.Context, arg CountUserActivityByLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountUserActivityByLocation, arg.UserID, arg.Location)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetUserRecentActivity = `-- name: GetUserRecentActivity :many
SELECT location, activity_type, created_at
FROM user_location_activity
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetUserRecentActivityParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type GetUserRecentActivityRow struct {
	Location     string    `json:"location"`
	ActivityType string    `json:"activity_type"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetUserRecentActivity(ctx context.Context, arg GetUserRecentActivityParams) ([]GetUserRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, GetUserRecentActivity, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRecentActivityRow{}
	for rows.Next() {
		var i GetUserRecentActivityRow
		if err := rows.Scan(&i.Location, &i.ActivityType, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserTopLocations = `-- name: GetUserTopLocations :many
SELECT location, view_count, last_viewed_at
FROM user_location_preferences
WHERE user_id = $1
ORDER BY view_count DESC, last_viewed_at DESC
LIMIT $2
`

type GetUserTopLocationsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type GetUserTopLocationsRow struct {
	Location     string    `json:"location"`
	ViewCount    int32     `json:"view_count"`
	LastViewedAt time.Time `json:"last_viewed_at"`
}

func (q *Queries) GetUserTopLocations(ctx context.Context, arg GetUserTopLocationsParams) ([]GetUserTopLocationsRow, error) {
	rows, err := q.db.Query(ctx, GetUserTopLocations, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserTopLocationsRow{}
	for rows.Next() {
		var i GetUserTopLocationsRow
		if err := rows.Scan(&i.Location, &i.ViewCount, &i.LastViewedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TrackUserLocationActivity = `-- name: TrackUserLocationActivity :exec

INSERT INTO user_location_activity (id, user_id, location, activity_type, created_at)
VALUES ($1, $2, $3, $4, NOW())
`

type TrackUserLocationActivityParams struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	Location     string `json:"location"`
	ActivityType string `json:"activity_type"`
}

// User Activity Tracking Queries (ADR-087 Phase 5)
func (q *Queries) TrackUserLocationActivity(ctx context.Context, arg TrackUserLocationActivityParams) error {
	_, err := q.db.Exec(ctx, TrackUserLocationActivity,
		arg.ID,
		arg.UserID,
		arg.Location,
		arg.ActivityType,
	)
	return err
}

const UpsertUserLocationPreference = `-- name: UpsertUserLocationPreference :exec
INSERT INTO user_location_preferences (id, user_id, location, view_count, last_viewed_at, created_at)
VALUES ($1, $2, $3, 1, NOW(), NOW())
ON CONFLICT (user_id, location)
DO UPDATE SET
    view_count = user_location_preferences.view_count + 1,
    last_viewed_at = NOW()
`

type UpsertUserLocationPreferenceParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	Location string `json:"location"`
}

func (q *Queries) UpsertUserLocationPreference(ctx context.Context, arg UpsertUserLocationPreferenceParams) error {
	_, err := q.db.Exec(ctx, UpsertUserLocationPreference, arg.ID, arg.UserID, arg.Location)
	return err
}
