// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AdminUpdateUserProfile = `-- name: AdminUpdateUserProfile :exec
UPDATE users SET
    "firstName" = COALESCE($2::text, "firstName"),
    "lastName" = COALESCE($3::text, "lastName"),
    email = COALESCE($4::text, email),
    role = COALESCE($5::text::"UserRole", role),
    "subscriptionTier" = COALESCE($6::text, "subscriptionTier"),
    "updatedAt" = NOW()
WHERE id = $1
`

type AdminUpdateUserProfileParams struct {
	ID               string      `json:"id"`
	FirstName        pgtype.Text `json:"first_name"`
	LastName         pgtype.Text `json:"last_name"`
	Email            pgtype.Text `json:"email"`
	Role             pgtype.Text `json:"role"`
	SubscriptionTier pgtype.Text `json:"subscription_tier"`
}

func (q *Queries) AdminUpdateUserProfile(ctx context.Context, arg AdminUpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, AdminUpdateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Role,
		arg.SubscriptionTier,
	)
	return err
}

const CountUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateEarlyAccessUser = `-- name: CreateEarlyAccessUser :one
INSERT INTO users (
    id, email, "firstName", "lastName", role,
    "subscriptionTier", early_access_status, "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, 'USER', 'early_access', 'active', NOW(), NOW()
) RETURNING id, "createdAt", "updatedAt", email, "firstName", "lastName", "stripeCustomerId", role, "hasDataTier", password, theme, "subscriptionTier", phone, "streetAddress", city, state, "zipCode", "investorProfile", "iapPlatform", "iapProductId", "iapReceiptData", "iapExpiresAt", "iapLastValidated", "appleOriginalTransactionId", "appleEnvironment", "suspendedAt", "suspendedBy", "suspendReason", early_access_status
`

type CreateEarlyAccessUserParams struct {
	ID        string      `json:"id"`
	Email     string      `json:"email"`
	FirstName pgtype.Text `json:"firstName"`
	LastName  pgtype.Text `json:"lastName"`
}

// Creates an early access user without a password (password set via setup link)
func (q *Queries) CreateEarlyAccessUser(ctx context.Context, arg CreateEarlyAccessUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateEarlyAccessUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.StripeCustomerId,
		&i.Role,
		&i.HasDataTier,
		&i.Password,
		&i.Theme,
		&i.SubscriptionTier,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.InvestorProfile,
		&i.IapPlatform,
		&i.IapProductId,
		&i.IapReceiptData,
		&i.IapExpiresAt,
		&i.IapLastValidated,
		&i.AppleOriginalTransactionId,
		&i.AppleEnvironment,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.SuspendReason,
		&i.EarlyAccessStatus,
	)
	return i, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, "firstName", "lastName", role,
    "subscriptionTier", "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
) RETURNING id, "createdAt", "updatedAt", email, "firstName", "lastName", "stripeCustomerId", role, "hasDataTier", password, theme, "subscriptionTier", phone, "streetAddress", city, state, "zipCode", "investorProfile", "iapPlatform", "iapProductId", "iapReceiptData", "iapExpiresAt", "iapLastValidated", "appleOriginalTransactionId", "appleEnvironment", "suspendedAt", "suspendedBy", "suspendReason", early_access_status
`

type CreateUserParams struct {
	ID               string      `json:"id"`
	Email            string      `json:"email"`
	FirstName        pgtype.Text `json:"firstName"`
	LastName         pgtype.Text `json:"lastName"`
	Role             string      `json:"role"`
	SubscriptionTier pgtype.Text `json:"subscriptionTier"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.SubscriptionTier,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.StripeCustomerId,
		&i.Role,
		&i.HasDataTier,
		&i.Password,
		&i.Theme,
		&i.SubscriptionTier,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.InvestorProfile,
		&i.IapPlatform,
		&i.IapProductId,
		&i.IapReceiptData,
		&i.IapExpiresAt,
		&i.IapLastValidated,
		&i.AppleOriginalTransactionId,
		&i.AppleEnvironment,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.SuspendReason,
		&i.EarlyAccessStatus,
	)
	return i, err
}

const CreateUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (
    id, email, password, "firstName", "lastName", role,
    "subscriptionTier", "stripeCustomerId", "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
) RETURNING id, "createdAt", "updatedAt", email, "firstName", "lastName", "stripeCustomerId", role, "hasDataTier", password, theme, "subscriptionTier", phone, "streetAddress", city, state, "zipCode", "investorProfile", "iapPlatform", "iapProductId", "iapReceiptData", "iapExpiresAt", "iapLastValidated", "appleOriginalTransactionId", "appleEnvironment", "suspendedAt", "suspendedBy", "suspendReason", early_access_status
`

type CreateUserWithPasswordParams struct {
	ID               string      `json:"id"`
	Email            string      `json:"email"`
	Password         pgtype.Text `json:"password"`
	FirstName        pgtype.Text `json:"firstName"`
	LastName         pgtype.Text `json:"lastName"`
	Role             string      `json:"role"`
	SubscriptionTier pgtype.Text `json:"subscriptionTier"`
	StripeCustomerId pgtype.Text `json:"stripeCustomerId"`
}

// Creates a user with password hash and Stripe customer ID (for guest checkout signup)
func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUserWithPassword,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.SubscriptionTier,
		arg.StripeCustomerId,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.StripeCustomerId,
		&i.Role,
		&i.HasDataTier,
		&i.Password,
		&i.Theme,
		&i.SubscriptionTier,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.InvestorProfile,
		&i.IapPlatform,
		&i.IapProductId,
		&i.IapReceiptData,
		&i.IapExpiresAt,
		&i.IapLastValidated,
		&i.AppleOriginalTransactionId,
		&i.AppleEnvironment,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.SuspendReason,
		&i.EarlyAccessStatus,
	)
	return i, err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeleteUser, id)
	return err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, "createdAt", "updatedAt", email, "firstName", "lastName", "stripeCustomerId", role, "hasDataTier", password, theme, "subscriptionTier", phone, "streetAddress", city, state, "zipCode", "investorProfile", "iapPlatform", "iapProductId", "iapReceiptData", "iapExpiresAt", "iapLastValidated", "appleOriginalTransactionId", "appleEnvironment", "suspendedAt", "suspendedBy", "suspendReason", early_access_status FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.StripeCustomerId,
		&i.Role,
		&i.HasDataTier,
		&i.Password,
		&i.Theme,
		&i.SubscriptionTier,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.InvestorProfile,
		&i.IapPlatform,
		&i.IapProductId,
		&i.IapReceiptData,
		&i.IapExpiresAt,
		&i.IapLastValidated,
		&i.AppleOriginalTransactionId,
		&i.AppleEnvironment,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.SuspendReason,
		&i.EarlyAccessStatus,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, "createdAt", "updatedAt", email, "firstName", "lastName", "stripeCustomerId", role, "hasDataTier", password, theme, "subscriptionTier", phone, "streetAddress", city, state, "zipCode", "investorProfile", "iapPlatform", "iapProductId", "iapReceiptData", "iapExpiresAt", "iapLastValidated", "appleOriginalTransactionId", "appleEnvironment", "suspendedAt", "suspendedBy", "suspendReason", early_access_status FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.StripeCustomerId,
		&i.Role,
		&i.HasDataTier,
		&i.Password,
		&i.Theme,
		&i.SubscriptionTier,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.InvestorProfile,
		&i.IapPlatform,
		&i.IapProductId,
		&i.IapReceiptData,
		&i.IapExpiresAt,
		&i.IapLastValidated,
		&i.AppleOriginalTransactionId,
		&i.AppleEnvironment,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.SuspendReason,
		&i.EarlyAccessStatus,
	)
	return i, err
}

const GetUserByStripeCustomerID = `-- name: GetUserByStripeCustomerID :one
SELECT id, "createdAt", "updatedAt", email, "firstName", "lastName", "stripeCustomerId", role, "hasDataTier", password, theme, "subscriptionTier", phone, "streetAddress", city, state, "zipCode", "investorProfile", "iapPlatform", "iapProductId", "iapReceiptData", "iapExpiresAt", "iapLastValidated", "appleOriginalTransactionId", "appleEnvironment", "suspendedAt", "suspendedBy", "suspendReason", early_access_status FROM users WHERE "stripeCustomerId" = $1
`

func (q *Queries) GetUserByStripeCustomerID(ctx context.Context, stripecustomerid pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByStripeCustomerID, stripecustomerid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.StripeCustomerId,
		&i.Role,
		&i.HasDataTier,
		&i.Password,
		&i.Theme,
		&i.SubscriptionTier,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.InvestorProfile,
		&i.IapPlatform,
		&i.IapProductId,
		&i.IapReceiptData,
		&i.IapExpiresAt,
		&i.IapLastValidated,
		&i.AppleOriginalTransactionId,
		&i.AppleEnvironment,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.SuspendReason,
		&i.EarlyAccessStatus,
	)
	return i, err
}

const GetUserStats = `-- name: GetUserStats :one
SELECT
    COUNT(*) FILTER (WHERE role = 'ADMIN') as admin_count,
    COUNT(*) FILTER (WHERE role = 'USER') as user_count,
    COUNT(*) FILTER (WHERE "subscriptionTier" = 'free') as free_count,
    COUNT(*) FILTER (WHERE "subscriptionTier" = 'pro') as pro_count
FROM users
`

type GetUserStatsRow struct {
	AdminCount int64 `json:"admin_count"`
	UserCount  int64 `json:"user_count"`
	FreeCount  int64 `json:"free_count"`
	ProCount   int64 `json:"pro_count"`
}

func (q *Queries) GetUserStats(ctx context.Context) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, GetUserStats)
	var i GetUserStatsRow
	err := row.Scan(
		&i.AdminCount,
		&i.UserCount,
		&i.FreeCount,
		&i.ProCount,
	)
	return i, err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, "createdAt", "updatedAt", email, "firstName", "lastName", "stripeCustomerId", role, "hasDataTier", password, theme, "subscriptionTier", phone, "streetAddress", city, state, "zipCode", "investorProfile", "iapPlatform", "iapProductId", "iapReceiptData", "iapExpiresAt", "iapLastValidated", "appleOriginalTransactionId", "appleEnvironment", "suspendedAt", "suspendedBy", "suspendReason", early_access_status FROM users
ORDER BY "createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, ListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.StripeCustomerId,
			&i.Role,
			&i.HasDataTier,
			&i.Password,
			&i.Theme,
			&i.SubscriptionTier,
			&i.Phone,
			&i.StreetAddress,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.InvestorProfile,
			&i.IapPlatform,
			&i.IapProductId,
			&i.IapReceiptData,
			&i.IapExpiresAt,
			&i.IapLastValidated,
			&i.AppleOriginalTransactionId,
			&i.AppleEnvironment,
			&i.SuspendedAt,
			&i.SuspendedBy,
			&i.SuspendReason,
			&i.EarlyAccessStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUsersByRole = `-- name: ListUsersByRole :many
SELECT id, "createdAt", "updatedAt", email, "firstName", "lastName", "stripeCustomerId", role, "hasDataTier", password, theme, "subscriptionTier", phone, "streetAddress", city, state, "zipCode", "investorProfile", "iapPlatform", "iapProductId", "iapReceiptData", "iapExpiresAt", "iapLastValidated", "appleOriginalTransactionId", "appleEnvironment", "suspendedAt", "suspendedBy", "suspendReason", early_access_status FROM users
WHERE role = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListUsersByRoleParams struct {
	Role   string `json:"role"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, ListUsersByRole, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.StripeCustomerId,
			&i.Role,
			&i.HasDataTier,
			&i.Password,
			&i.Theme,
			&i.SubscriptionTier,
			&i.Phone,
			&i.StreetAddress,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.InvestorProfile,
			&i.IapPlatform,
			&i.IapProductId,
			&i.IapReceiptData,
			&i.IapExpiresAt,
			&i.IapLastValidated,
			&i.AppleOriginalTransactionId,
			&i.AppleEnvironment,
			&i.SuspendedAt,
			&i.SuspendedBy,
			&i.SuspendReason,
			&i.EarlyAccessStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchUsersByEmail = `-- name: SearchUsersByEmail :many
SELECT id, "createdAt", "updatedAt", email, "firstName", "lastName", "stripeCustomerId", role, "hasDataTier", password, theme, "subscriptionTier", phone, "streetAddress", city, state, "zipCode", "investorProfile", "iapPlatform", "iapProductId", "iapReceiptData", "iapExpiresAt", "iapLastValidated", "appleOriginalTransactionId", "appleEnvironment", "suspendedAt", "suspendedBy", "suspendReason", early_access_status FROM users
WHERE email ILIKE '%' || $1 || '%'
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type SearchUsersByEmailParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchUsersByEmail(ctx context.Context, arg SearchUsersByEmailParams) ([]User, error) {
	rows, err := q.db.Query(ctx, SearchUsersByEmail, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.StripeCustomerId,
			&i.Role,
			&i.HasDataTier,
			&i.Password,
			&i.Theme,
			&i.SubscriptionTier,
			&i.Phone,
			&i.StreetAddress,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.InvestorProfile,
			&i.IapPlatform,
			&i.IapProductId,
			&i.IapReceiptData,
			&i.IapExpiresAt,
			&i.IapLastValidated,
			&i.AppleOriginalTransactionId,
			&i.AppleEnvironment,
			&i.SuspendedAt,
			&i.SuspendedBy,
			&i.SuspendReason,
			&i.EarlyAccessStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetUserPasswordAndStatus = `-- name: SetUserPasswordAndStatus :exec
UPDATE users SET
    password = $2,
    early_access_status = 'active',
    "updatedAt" = NOW()
WHERE id = $1
`

type SetUserPasswordAndStatusParams struct {
	ID       string      `json:"id"`
	Password pgtype.Text `json:"password"`
}

// Sets password hash and marks account active (used in password setup flow)
func (q *Queries) SetUserPasswordAndStatus(ctx context.Context, arg SetUserPasswordAndStatusParams) error {
	_, err := q.db.Exec(ctx, SetUserPasswordAndStatus, arg.ID, arg.Password)
	return err
}

const SuspendUser = `-- name: SuspendUser :exec
UPDATE users SET
    "suspendedAt" = NOW(),
    "suspendedBy" = $2,
    "suspendReason" = $3,
    "updatedAt" = NOW()
WHERE id = $1
`

type SuspendUserParams struct {
	ID            string      `json:"id"`
	SuspendedBy   pgtype.Text `json:"suspendedBy"`
	SuspendReason pgtype.Text `json:"suspendReason"`
}

func (q *Queries) SuspendUser(ctx context.Context, arg SuspendUserParams) error {
	_, err := q.db.Exec(ctx, SuspendUser, arg.ID, arg.SuspendedBy, arg.SuspendReason)
	return err
}

const UnsuspendUser = `-- name: UnsuspendUser :exec
UPDATE users SET
    "suspendedAt" = NULL,
    "suspendedBy" = NULL,
    "suspendReason" = NULL,
    "updatedAt" = NOW()
WHERE id = $1
`

func (q *Queries) UnsuspendUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, UnsuspendUser, id)
	return err
}

const UpdateUserEarlyAccessStatus = `-- name: UpdateUserEarlyAccessStatus :exec
UPDATE users SET
    early_access_status = $2,
    "updatedAt" = NOW()
WHERE id = $1
`

type UpdateUserEarlyAccessStatusParams struct {
	ID                string      `json:"id"`
	EarlyAccessStatus pgtype.Text `json:"early_access_status"`
}

// Updates early_access_status and optionally the account status field
func (q *Queries) UpdateUserEarlyAccessStatus(ctx context.Context, arg UpdateUserEarlyAccessStatusParams) error {
	_, err := q.db.Exec(ctx, UpdateUserEarlyAccessStatus, arg.ID, arg.EarlyAccessStatus)
	return err
}

const UpdateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET
    password = $2,
    "updatedAt" = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       string      `json:"id"`
	Password pgtype.Text `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, UpdateUserPassword, arg.ID, arg.Password)
	return err
}

const UpdateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET
    "firstName" = COALESCE($2, "firstName"),
    "lastName" = COALESCE($3, "lastName"),
    email = COALESCE($4, email),
    "updatedAt" = NOW()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID        string      `json:"id"`
	FirstName pgtype.Text `json:"firstName"`
	LastName  pgtype.Text `json:"lastName"`
	Email     string      `json:"email"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, UpdateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
	)
	return err
}

const UpdateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET
    role = $2,
    "updatedAt" = NOW()
WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, UpdateUserRole, arg.ID, arg.Role)
	return err
}

const UpdateUserStripeCustomer = `-- name: UpdateUserStripeCustomer :exec
UPDATE users SET
    "stripeCustomerId" = $2,
    "updatedAt" = NOW()
WHERE id = $1
`

type UpdateUserStripeCustomerParams struct {
	ID               string      `json:"id"`
	StripeCustomerId pgtype.Text `json:"stripeCustomerId"`
}

func (q *Queries) UpdateUserStripeCustomer(ctx context.Context, arg UpdateUserStripeCustomerParams) error {
	_, err := q.db.Exec(ctx, UpdateUserStripeCustomer, arg.ID, arg.StripeCustomerId)
	return err
}

const UpdateUserSubscription = `-- name: UpdateUserSubscription :exec
UPDATE users SET
    "subscriptionTier" = $2,
    "stripeCustomerId" = $3,
    "updatedAt" = NOW()
WHERE id = $1
`

type UpdateUserSubscriptionParams struct {
	ID               string      `json:"id"`
	SubscriptionTier pgtype.Text `json:"subscriptionTier"`
	StripeCustomerId pgtype.Text `json:"stripeCustomerId"`
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error {
	_, err := q.db.Exec(ctx, UpdateUserSubscription, arg.ID, arg.SubscriptionTier, arg.StripeCustomerId)
	return err
}

const UpdateUserUpdatedAt = `-- name: UpdateUserUpdatedAt :exec
UPDATE users SET "updatedAt" = NOW() WHERE id = $1
`

func (q *Queries) UpdateUserUpdatedAt(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, UpdateUserUpdatedAt, id)
	return err
}
