// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webauthn.sql

package queries

import (
	"context"
)

const CountWebAuthnCredentialsByUser = `-- name: CountWebAuthnCredentialsByUser :one
SELECT COUNT(*) FROM webauthn_credentials
WHERE "userId" = $1
`

func (q *Queries) CountWebAuthnCredentialsByUser(ctx context.Context, userid string) (int64, error) {
	row := q.db.QueryRow(ctx, CountWebAuthnCredentialsByUser, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateWebAuthnCredential = `-- name: CreateWebAuthnCredential :one
INSERT INTO webauthn_credentials (
    id, "userId", credential_id, public_key, attestation_type,
    transport, flags_value, sign_count, aaguid, friendly_name,
    "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    NOW(), NOW()
) RETURNING id, "userId", credential_id, public_key, attestation_type, transport, flags_value, sign_count, aaguid, clone_warning, friendly_name, "createdAt", "lastUsedAt", "updatedAt"
`

type CreateWebAuthnCredentialParams struct {
	ID              string   `json:"id"`
	UserId          string   `json:"userId"`
	CredentialID    []byte   `json:"credential_id"`
	PublicKey       []byte   `json:"public_key"`
	AttestationType string   `json:"attestation_type"`
	Transport       []string `json:"transport"`
	FlagsValue      int32    `json:"flags_value"`
	SignCount       int64    `json:"sign_count"`
	Aaguid          []byte   `json:"aaguid"`
	FriendlyName    string   `json:"friendly_name"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, CreateWebAuthnCredential,
		arg.ID,
		arg.UserId,
		arg.CredentialID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transport,
		arg.FlagsValue,
		arg.SignCount,
		arg.Aaguid,
		arg.FriendlyName,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transport,
		&i.FlagsValue,
		&i.SignCount,
		&i.Aaguid,
		&i.CloneWarning,
		&i.FriendlyName,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM webauthn_credentials
WHERE id = $1 AND "userId" = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     string `json:"id"`
	UserId string `json:"userId"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, DeleteWebAuthnCredential, arg.ID, arg.UserId)
	return err
}

const GetWebAuthnCredentialByCredentialID = `-- name: GetWebAuthnCredentialByCredentialID :one
SELECT id, "userId", credential_id, public_key, attestation_type, transport, flags_value, sign_count, aaguid, clone_warning, friendly_name, "createdAt", "lastUsedAt", "updatedAt" FROM webauthn_credentials
WHERE credential_id = $1
`

func (q *Queries) GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, GetWebAuthnCredentialByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transport,
		&i.FlagsValue,
		&i.SignCount,
		&i.Aaguid,
		&i.CloneWarning,
		&i.FriendlyName,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetWebAuthnCredentialsByUserID = `-- name: GetWebAuthnCredentialsByUserID :many
SELECT id, "userId", credential_id, public_key, attestation_type, transport, flags_value, sign_count, aaguid, clone_warning, friendly_name, "createdAt", "lastUsedAt", "updatedAt" FROM webauthn_credentials
WHERE "userId" = $1
ORDER BY "createdAt" DESC
`

func (q *Queries) GetWebAuthnCredentialsByUserID(ctx context.Context, userid string) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, GetWebAuthnCredentialsByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.CredentialID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transport,
			&i.FlagsValue,
			&i.SignCount,
			&i.Aaguid,
			&i.CloneWarning,
			&i.FriendlyName,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateWebAuthnCredentialName = `-- name: UpdateWebAuthnCredentialName :exec
UPDATE webauthn_credentials
SET friendly_name = $2, "updatedAt" = NOW()
WHERE id = $1
`

type UpdateWebAuthnCredentialNameParams struct {
	ID           string `json:"id"`
	FriendlyName string `json:"friendly_name"`
}

func (q *Queries) UpdateWebAuthnCredentialName(ctx context.Context, arg UpdateWebAuthnCredentialNameParams) error {
	_, err := q.db.Exec(ctx, UpdateWebAuthnCredentialName, arg.ID, arg.FriendlyName)
	return err
}

const UpdateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :exec
UPDATE webauthn_credentials
SET sign_count = $2, "lastUsedAt" = NOW(), "updatedAt" = NOW()
WHERE id = $1
`

type UpdateWebAuthnCredentialSignCountParams struct {
	ID        string `json:"id"`
	SignCount int64  `json:"sign_count"`
}

func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, UpdateWebAuthnCredentialSignCount, arg.ID, arg.SignCount)
	return err
}
