// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: website.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountContactSubmissions = `-- name: CountContactSubmissions :one
SELECT COUNT(*) FROM contact_submissions
`

func (q *Queries) CountContactSubmissions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountContactSubmissions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountContactSubmissionsByStatus = `-- name: CountContactSubmissionsByStatus :one
SELECT COUNT(*) FROM contact_submissions WHERE status = $1
`

func (q *Queries) CountContactSubmissionsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, CountContactSubmissionsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountEarlyAccess = `-- name: CountEarlyAccess :one
SELECT COUNT(*) FROM early_access
`

func (q *Queries) CountEarlyAccess(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountEarlyAccess)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountPendingEarlyAccess = `-- name: CountPendingEarlyAccess :one
SELECT COUNT(*) FROM early_access WHERE "invitedAt" IS NULL
`

func (q *Queries) CountPendingEarlyAccess(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountPendingEarlyAccess)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateContactSubmission = `-- name: CreateContactSubmission :one
INSERT INTO contact_submissions (
    id, name, email, phone, subject, message, source,
    "ipAddress", "userAgent", status, "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW()
) RETURNING id, name, email, phone, subject, message, source, "ipAddress", "userAgent", status, notes, "respondedAt", "respondedBy", "createdAt", "updatedAt"
`

type CreateContactSubmissionParams struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Phone     pgtype.Text `json:"phone"`
	Subject   pgtype.Text `json:"subject"`
	Message   string      `json:"message"`
	Source    pgtype.Text `json:"source"`
	IpAddress pgtype.Text `json:"ipAddress"`
	UserAgent pgtype.Text `json:"userAgent"`
	Status    string      `json:"status"`
}

func (q *Queries) CreateContactSubmission(ctx context.Context, arg CreateContactSubmissionParams) (ContactSubmission, error) {
	row := q.db.QueryRow(ctx, CreateContactSubmission,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Subject,
		arg.Message,
		arg.Source,
		arg.IpAddress,
		arg.UserAgent,
		arg.Status,
	)
	var i ContactSubmission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Subject,
		&i.Message,
		&i.Source,
		&i.IpAddress,
		&i.UserAgent,
		&i.Status,
		&i.Notes,
		&i.RespondedAt,
		&i.RespondedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateEarlyAccess = `-- name: CreateEarlyAccess :one
INSERT INTO early_access (
    id, email, name, source, "ipAddress", "createdAt"
) VALUES (
    $1, $2, $3, $4, $5, NOW()
) RETURNING id, email, name, source, "ipAddress", "invitedAt", "acceptedAt", "createdAt"
`

type CreateEarlyAccessParams struct {
	ID        string      `json:"id"`
	Email     string      `json:"email"`
	Name      pgtype.Text `json:"name"`
	Source    pgtype.Text `json:"source"`
	IpAddress pgtype.Text `json:"ipAddress"`
}

func (q *Queries) CreateEarlyAccess(ctx context.Context, arg CreateEarlyAccessParams) (EarlyAccess, error) {
	row := q.db.QueryRow(ctx, CreateEarlyAccess,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Source,
		arg.IpAddress,
	)
	var i EarlyAccess
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Source,
		&i.IpAddress,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const CreateGuestSession = `-- name: CreateGuestSession :one
INSERT INTO guest_sessions (
    id, token, "ipAddress", "userAgent", "deviceFingerprint",
    "expiresAt", "createdAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
) RETURNING id, token, "ipAddress", "userAgent", "deviceFingerprint", "expiresAt", "snapshotsUsed", "lastActivityAt", "createdAt"
`

type CreateGuestSessionParams struct {
	ID                string           `json:"id"`
	Token             string           `json:"token"`
	IpAddress         pgtype.Text      `json:"ipAddress"`
	UserAgent         pgtype.Text      `json:"userAgent"`
	DeviceFingerprint pgtype.Text      `json:"deviceFingerprint"`
	ExpiresAt         pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) CreateGuestSession(ctx context.Context, arg CreateGuestSessionParams) (GuestSession, error) {
	row := q.db.QueryRow(ctx, CreateGuestSession,
		arg.ID,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceFingerprint,
		arg.ExpiresAt,
	)
	var i GuestSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.ExpiresAt,
		&i.SnapshotsUsed,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteExpiredGuestSessions = `-- name: DeleteExpiredGuestSessions :exec
DELETE FROM guest_sessions
WHERE "expiresAt" < NOW()
`

func (q *Queries) DeleteExpiredGuestSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, DeleteExpiredGuestSessions)
	return err
}

const GetContactSubmissionByID = `-- name: GetContactSubmissionByID :one


SELECT id, name, email, phone, subject, message, source, "ipAddress", "userAgent", status, notes, "respondedAt", "respondedBy", "createdAt", "updatedAt" FROM contact_submissions WHERE id = $1
`

// Website and Public API Queries
// Contact Submissions
func (q *Queries) GetContactSubmissionByID(ctx context.Context, id string) (ContactSubmission, error) {
	row := q.db.QueryRow(ctx, GetContactSubmissionByID, id)
	var i ContactSubmission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Subject,
		&i.Message,
		&i.Source,
		&i.IpAddress,
		&i.UserAgent,
		&i.Status,
		&i.Notes,
		&i.RespondedAt,
		&i.RespondedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetEarlyAccessByEmail = `-- name: GetEarlyAccessByEmail :one
SELECT id, email, name, source, "ipAddress", "invitedAt", "acceptedAt", "createdAt" FROM early_access WHERE email = $1
`

func (q *Queries) GetEarlyAccessByEmail(ctx context.Context, email string) (EarlyAccess, error) {
	row := q.db.QueryRow(ctx, GetEarlyAccessByEmail, email)
	var i EarlyAccess
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Source,
		&i.IpAddress,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetEarlyAccessByID = `-- name: GetEarlyAccessByID :one

SELECT id, email, name, source, "ipAddress", "invitedAt", "acceptedAt", "createdAt" FROM early_access WHERE id = $1
`

// Early Access (Waitlist)
func (q *Queries) GetEarlyAccessByID(ctx context.Context, id string) (EarlyAccess, error) {
	row := q.db.QueryRow(ctx, GetEarlyAccessByID, id)
	var i EarlyAccess
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Source,
		&i.IpAddress,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetGuestSessionByID = `-- name: GetGuestSessionByID :one

SELECT id, token, "ipAddress", "userAgent", "deviceFingerprint", "expiresAt", "snapshotsUsed", "lastActivityAt", "createdAt" FROM guest_sessions WHERE id = $1
`

// Guest Sessions
func (q *Queries) GetGuestSessionByID(ctx context.Context, id string) (GuestSession, error) {
	row := q.db.QueryRow(ctx, GetGuestSessionByID, id)
	var i GuestSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.ExpiresAt,
		&i.SnapshotsUsed,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetGuestSessionByToken = `-- name: GetGuestSessionByToken :one
SELECT id, token, "ipAddress", "userAgent", "deviceFingerprint", "expiresAt", "snapshotsUsed", "lastActivityAt", "createdAt" FROM guest_sessions WHERE token = $1 AND "expiresAt" > NOW()
`

func (q *Queries) GetGuestSessionByToken(ctx context.Context, token string) (GuestSession, error) {
	row := q.db.QueryRow(ctx, GetGuestSessionByToken, token)
	var i GuestSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.ExpiresAt,
		&i.SnapshotsUsed,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const IncrementGuestSessionSnapshots = `-- name: IncrementGuestSessionSnapshots :one
UPDATE guest_sessions SET
    "snapshotsUsed" = "snapshotsUsed" + 1,
    "lastActivityAt" = NOW()
WHERE id = $1
RETURNING id, token, "ipAddress", "userAgent", "deviceFingerprint", "expiresAt", "snapshotsUsed", "lastActivityAt", "createdAt"
`

func (q *Queries) IncrementGuestSessionSnapshots(ctx context.Context, id string) (GuestSession, error) {
	row := q.db.QueryRow(ctx, IncrementGuestSessionSnapshots, id)
	var i GuestSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.ExpiresAt,
		&i.SnapshotsUsed,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const ListContactSubmissions = `-- name: ListContactSubmissions :many
SELECT id, name, email, phone, subject, message, source, "ipAddress", "userAgent", status, notes, "respondedAt", "respondedBy", "createdAt", "updatedAt" FROM contact_submissions
ORDER BY "createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListContactSubmissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListContactSubmissions(ctx context.Context, arg ListContactSubmissionsParams) ([]ContactSubmission, error) {
	rows, err := q.db.Query(ctx, ListContactSubmissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactSubmission{}
	for rows.Next() {
		var i ContactSubmission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Subject,
			&i.Message,
			&i.Source,
			&i.IpAddress,
			&i.UserAgent,
			&i.Status,
			&i.Notes,
			&i.RespondedAt,
			&i.RespondedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListContactSubmissionsByStatus = `-- name: ListContactSubmissionsByStatus :many
SELECT id, name, email, phone, subject, message, source, "ipAddress", "userAgent", status, notes, "respondedAt", "respondedBy", "createdAt", "updatedAt" FROM contact_submissions
WHERE status = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListContactSubmissionsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListContactSubmissionsByStatus(ctx context.Context, arg ListContactSubmissionsByStatusParams) ([]ContactSubmission, error) {
	rows, err := q.db.Query(ctx, ListContactSubmissionsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactSubmission{}
	for rows.Next() {
		var i ContactSubmission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Subject,
			&i.Message,
			&i.Source,
			&i.IpAddress,
			&i.UserAgent,
			&i.Status,
			&i.Notes,
			&i.RespondedAt,
			&i.RespondedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListEarlyAccess = `-- name: ListEarlyAccess :many
SELECT id, email, name, source, "ipAddress", "invitedAt", "acceptedAt", "createdAt" FROM early_access
ORDER BY "createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListEarlyAccessParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEarlyAccess(ctx context.Context, arg ListEarlyAccessParams) ([]EarlyAccess, error) {
	rows, err := q.db.Query(ctx, ListEarlyAccess, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EarlyAccess{}
	for rows.Next() {
		var i EarlyAccess
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Source,
			&i.IpAddress,
			&i.InvitedAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListInvitedEarlyAccess = `-- name: ListInvitedEarlyAccess :many
SELECT id, email, name, source, "ipAddress", "invitedAt", "acceptedAt", "createdAt" FROM early_access
WHERE "invitedAt" IS NOT NULL AND "acceptedAt" IS NULL
ORDER BY "invitedAt" ASC
LIMIT $1
`

func (q *Queries) ListInvitedEarlyAccess(ctx context.Context, limit int32) ([]EarlyAccess, error) {
	rows, err := q.db.Query(ctx, ListInvitedEarlyAccess, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EarlyAccess{}
	for rows.Next() {
		var i EarlyAccess
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Source,
			&i.IpAddress,
			&i.InvitedAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPendingEarlyAccess = `-- name: ListPendingEarlyAccess :many
SELECT id, email, name, source, "ipAddress", "invitedAt", "acceptedAt", "createdAt" FROM early_access
WHERE "invitedAt" IS NULL
ORDER BY "createdAt" ASC
LIMIT $1
`

func (q *Queries) ListPendingEarlyAccess(ctx context.Context, limit int32) ([]EarlyAccess, error) {
	rows, err := q.db.Query(ctx, ListPendingEarlyAccess, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EarlyAccess{}
	for rows.Next() {
		var i EarlyAccess
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Source,
			&i.IpAddress,
			&i.InvitedAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateContactSubmissionStatus = `-- name: UpdateContactSubmissionStatus :one
UPDATE contact_submissions SET
    status = $2,
    notes = COALESCE($3, notes),
    "respondedAt" = CASE WHEN $2 = 'RESPONDED' THEN NOW() ELSE "respondedAt" END,
    "respondedBy" = COALESCE($4, "respondedBy"),
    "updatedAt" = NOW()
WHERE id = $1
RETURNING id, name, email, phone, subject, message, source, "ipAddress", "userAgent", status, notes, "respondedAt", "respondedBy", "createdAt", "updatedAt"
`

type UpdateContactSubmissionStatusParams struct {
	ID          string      `json:"id"`
	Status      string      `json:"status"`
	Notes       pgtype.Text `json:"notes"`
	RespondedBy pgtype.Text `json:"respondedBy"`
}

func (q *Queries) UpdateContactSubmissionStatus(ctx context.Context, arg UpdateContactSubmissionStatusParams) (ContactSubmission, error) {
	row := q.db.QueryRow(ctx, UpdateContactSubmissionStatus,
		arg.ID,
		arg.Status,
		arg.Notes,
		arg.RespondedBy,
	)
	var i ContactSubmission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Subject,
		&i.Message,
		&i.Source,
		&i.IpAddress,
		&i.UserAgent,
		&i.Status,
		&i.Notes,
		&i.RespondedAt,
		&i.RespondedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateEarlyAccessAccepted = `-- name: UpdateEarlyAccessAccepted :one
UPDATE early_access SET
    "acceptedAt" = NOW()
WHERE id = $1
RETURNING id, email, name, source, "ipAddress", "invitedAt", "acceptedAt", "createdAt"
`

func (q *Queries) UpdateEarlyAccessAccepted(ctx context.Context, id string) (EarlyAccess, error) {
	row := q.db.QueryRow(ctx, UpdateEarlyAccessAccepted, id)
	var i EarlyAccess
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Source,
		&i.IpAddress,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const UpdateEarlyAccessInvited = `-- name: UpdateEarlyAccessInvited :one
UPDATE early_access SET
    "invitedAt" = NOW()
WHERE id = $1
RETURNING id, email, name, source, "ipAddress", "invitedAt", "acceptedAt", "createdAt"
`

func (q *Queries) UpdateEarlyAccessInvited(ctx context.Context, id string) (EarlyAccess, error) {
	row := q.db.QueryRow(ctx, UpdateEarlyAccessInvited, id)
	var i EarlyAccess
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Source,
		&i.IpAddress,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const UpdateGuestSessionActivity = `-- name: UpdateGuestSessionActivity :one
UPDATE guest_sessions SET
    "lastActivityAt" = NOW(),
    "snapshotsUsed" = COALESCE($2, "snapshotsUsed")
WHERE id = $1
RETURNING id, token, "ipAddress", "userAgent", "deviceFingerprint", "expiresAt", "snapshotsUsed", "lastActivityAt", "createdAt"
`

type UpdateGuestSessionActivityParams struct {
	ID            string `json:"id"`
	SnapshotsUsed int32  `json:"snapshotsUsed"`
}

func (q *Queries) UpdateGuestSessionActivity(ctx context.Context, arg UpdateGuestSessionActivityParams) (GuestSession, error) {
	row := q.db.QueryRow(ctx, UpdateGuestSessionActivity, arg.ID, arg.SnapshotsUsed)
	var i GuestSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.ExpiresAt,
		&i.SnapshotsUsed,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}
