// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location.sql

package marketqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetCityByNameAndState = `-- name: GetCityByNameAndState :one
SELECT
    id,
    city,
    state_id,
    state_name,
    latitude,
    longitude,
    population
FROM city_states
WHERE LOWER(city) = LOWER($1)
  AND state_id = $2
ORDER BY population DESC
LIMIT 1
`

type GetCityByNameAndStateParams struct {
	City    string `json:"city"`
	StateID string `json:"state_id"`
}

type GetCityByNameAndStateRow struct {
	ID         string  `json:"id"`
	City       string  `json:"city"`
	StateID    string  `json:"state_id"`
	StateName  string  `json:"state_name"`
	Latitude   float64 `json:"latitude"`
	Longitude  float64 `json:"longitude"`
	Population int32   `json:"population"`
}

// Get exact city by name and state for coordinate lookup
func (q *Queries) GetCityByNameAndState(ctx context.Context, arg GetCityByNameAndStateParams) (GetCityByNameAndStateRow, error) {
	row := q.db.QueryRow(ctx, GetCityByNameAndState, arg.City, arg.StateID)
	var i GetCityByNameAndStateRow
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.StateID,
		&i.StateName,
		&i.Latitude,
		&i.Longitude,
		&i.Population,
	)
	return i, err
}

const SearchLocationsByCity = `-- name: SearchLocationsByCity :many
SELECT
    id,
    city,
    state_id,
    state_name,
    population
FROM city_states
WHERE city_lower LIKE $1 || '%'
ORDER BY population DESC, city
LIMIT $2
`

type SearchLocationsByCityParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

type SearchLocationsByCityRow struct {
	ID         string `json:"id"`
	City       string `json:"city"`
	StateID    string `json:"state_id"`
	StateName  string `json:"state_name"`
	Population int32  `json:"population"`
}

// Search cities by prefix, ordered by population
func (q *Queries) SearchLocationsByCity(ctx context.Context, arg SearchLocationsByCityParams) ([]SearchLocationsByCityRow, error) {
	rows, err := q.db.Query(ctx, SearchLocationsByCity, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchLocationsByCityRow{}
	for rows.Next() {
		var i SearchLocationsByCityRow
		if err := rows.Scan(
			&i.ID,
			&i.City,
			&i.StateID,
			&i.StateName,
			&i.Population,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchLocationsByCityAndState = `-- name: SearchLocationsByCityAndState :many
SELECT
    id,
    city,
    state_id,
    state_name,
    population
FROM city_states
WHERE city_lower LIKE $1 || '%' AND state_id = $2
ORDER BY population DESC, city
LIMIT $3
`

type SearchLocationsByCityAndStateParams struct {
	Column1 pgtype.Text `json:"column_1"`
	StateID string      `json:"state_id"`
	Limit   int32       `json:"limit"`
}

type SearchLocationsByCityAndStateRow struct {
	ID         string `json:"id"`
	City       string `json:"city"`
	StateID    string `json:"state_id"`
	StateName  string `json:"state_name"`
	Population int32  `json:"population"`
}

// Search cities by prefix and state filter, ordered by population
func (q *Queries) SearchLocationsByCityAndState(ctx context.Context, arg SearchLocationsByCityAndStateParams) ([]SearchLocationsByCityAndStateRow, error) {
	rows, err := q.db.Query(ctx, SearchLocationsByCityAndState, arg.Column1, arg.StateID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchLocationsByCityAndStateRow{}
	for rows.Next() {
		var i SearchLocationsByCityAndStateRow
		if err := rows.Scan(
			&i.ID,
			&i.City,
			&i.StateID,
			&i.StateName,
			&i.Population,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
