// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: market.sql

package marketqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetCityMetroMapping = `-- name: GetCityMetroMapping :one
SELECT id, city, state_code, metro_name, metro_region_id, created_at FROM city_metro_mapping
WHERE city ILIKE $1 AND state_code = $2
`

type GetCityMetroMappingParams struct {
	City      string `json:"city"`
	StateCode string `json:"state_code"`
}

func (q *Queries) GetCityMetroMapping(ctx context.Context, arg GetCityMetroMappingParams) (CityMetroMapping, error) {
	row := q.db.QueryRow(ctx, GetCityMetroMapping, arg.City, arg.StateCode)
	var i CityMetroMapping
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.StateCode,
		&i.MetroName,
		&i.MetroRegionID,
		&i.CreatedAt,
	)
	return i, err
}

const GetLatestMetroData = `-- name: GetLatestMetroData :one
SELECT id, region_id, region_name, region_type, state_code, metro, date, zhvi, zori, zhvi_forecast, zori_forecast, created_at, updated_at FROM metro_timeseries
WHERE region_name = $1 AND region_type = $2
ORDER BY date DESC
LIMIT 1
`

type GetLatestMetroDataParams struct {
	RegionName string `json:"region_name"`
	RegionType string `json:"region_type"`
}

func (q *Queries) GetLatestMetroData(ctx context.Context, arg GetLatestMetroDataParams) (MetroTimeseries, error) {
	row := q.db.QueryRow(ctx, GetLatestMetroData, arg.RegionName, arg.RegionType)
	var i MetroTimeseries
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.RegionName,
		&i.RegionType,
		&i.StateCode,
		&i.Metro,
		&i.Date,
		&i.Zhvi,
		&i.Zori,
		&i.ZhviForecast,
		&i.ZoriForecast,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetLatestMetroDataByID = `-- name: GetLatestMetroDataByID :one
SELECT id, region_id, region_name, region_type, state_code, metro, date, zhvi, zori, zhvi_forecast, zori_forecast, created_at, updated_at FROM metro_timeseries
WHERE region_id = $1
ORDER BY date DESC
LIMIT 1
`

func (q *Queries) GetLatestMetroDataByID(ctx context.Context, regionID int32) (MetroTimeseries, error) {
	row := q.db.QueryRow(ctx, GetLatestMetroDataByID, regionID)
	var i MetroTimeseries
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.RegionName,
		&i.RegionType,
		&i.StateCode,
		&i.Metro,
		&i.Date,
		&i.Zhvi,
		&i.Zori,
		&i.ZhviForecast,
		&i.ZoriForecast,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMetroDataByState = `-- name: GetMetroDataByState :many
SELECT m.id, m.region_id, m.region_name, m.region_type, m.state_code, m.metro, m.date, m.zhvi, m.zori, m.zhvi_forecast, m.zori_forecast, m.created_at, m.updated_at FROM metro_timeseries m
WHERE m.state_code = $1 AND m.region_type = $2
AND m.date = (SELECT MAX(sub.date) FROM metro_timeseries sub WHERE sub.state_code = $1)
ORDER BY m.region_name
`

type GetMetroDataByStateParams struct {
	StateCode  pgtype.Text `json:"state_code"`
	RegionType string      `json:"region_type"`
}

func (q *Queries) GetMetroDataByState(ctx context.Context, arg GetMetroDataByStateParams) ([]MetroTimeseries, error) {
	rows, err := q.db.Query(ctx, GetMetroDataByState, arg.StateCode, arg.RegionType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetroTimeseries{}
	for rows.Next() {
		var i MetroTimeseries
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.RegionName,
			&i.RegionType,
			&i.StateCode,
			&i.Metro,
			&i.Date,
			&i.Zhvi,
			&i.Zori,
			&i.ZhviForecast,
			&i.ZoriForecast,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMetroForCity = `-- name: GetMetroForCity :one
SELECT m.id, m.region_id, m.region_name, m.region_type, m.state_code, m.metro, m.date, m.zhvi, m.zori, m.zhvi_forecast, m.zori_forecast, m.created_at, m.updated_at FROM metro_timeseries m
JOIN city_metro_mapping c ON m.region_id = c.metro_region_id
WHERE c.city ILIKE $1 AND c.state_code = $2
ORDER BY m.date DESC
LIMIT 1
`

type GetMetroForCityParams struct {
	City      string `json:"city"`
	StateCode string `json:"state_code"`
}

func (q *Queries) GetMetroForCity(ctx context.Context, arg GetMetroForCityParams) (MetroTimeseries, error) {
	row := q.db.QueryRow(ctx, GetMetroForCity, arg.City, arg.StateCode)
	var i MetroTimeseries
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.RegionName,
		&i.RegionType,
		&i.StateCode,
		&i.Metro,
		&i.Date,
		&i.Zhvi,
		&i.Zori,
		&i.ZhviForecast,
		&i.ZoriForecast,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMetroTimeSeries = `-- name: GetMetroTimeSeries :many
SELECT id, region_id, region_name, region_type, state_code, metro, date, zhvi, zori, zhvi_forecast, zori_forecast, created_at, updated_at FROM metro_timeseries
WHERE region_name = $1 AND region_type = $2
AND date >= $3 AND date <= $4
ORDER BY date ASC
`

type GetMetroTimeSeriesParams struct {
	RegionName string      `json:"region_name"`
	RegionType string      `json:"region_type"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
}

func (q *Queries) GetMetroTimeSeries(ctx context.Context, arg GetMetroTimeSeriesParams) ([]MetroTimeseries, error) {
	rows, err := q.db.Query(ctx, GetMetroTimeSeries,
		arg.RegionName,
		arg.RegionType,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetroTimeseries{}
	for rows.Next() {
		var i MetroTimeseries
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.RegionName,
			&i.RegionType,
			&i.StateCode,
			&i.Metro,
			&i.Date,
			&i.Zhvi,
			&i.Zori,
			&i.ZhviForecast,
			&i.ZoriForecast,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMetroTimeSeriesByID = `-- name: GetMetroTimeSeriesByID :many
SELECT id, region_id, region_name, region_type, state_code, metro, date, zhvi, zori, zhvi_forecast, zori_forecast, created_at, updated_at FROM metro_timeseries
WHERE region_id = $1
AND date >= $2 AND date <= $3
ORDER BY date ASC
`

type GetMetroTimeSeriesByIDParams struct {
	RegionID int32       `json:"region_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

func (q *Queries) GetMetroTimeSeriesByID(ctx context.Context, arg GetMetroTimeSeriesByIDParams) ([]MetroTimeseries, error) {
	rows, err := q.db.Query(ctx, GetMetroTimeSeriesByID, arg.RegionID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetroTimeseries{}
	for rows.Next() {
		var i MetroTimeseries
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.RegionName,
			&i.RegionType,
			&i.StateCode,
			&i.Metro,
			&i.Date,
			&i.Zhvi,
			&i.Zori,
			&i.ZhviForecast,
			&i.ZoriForecast,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetYearOverYearChange = `-- name: GetYearOverYearChange :one
WITH latest AS (
    SELECT t.zhvi, t.zori, t.date FROM metro_timeseries t
    WHERE t.region_id = $1
    ORDER BY t.date DESC
    LIMIT 1
),
year_ago AS (
    SELECT sub.zhvi, sub.zori FROM metro_timeseries sub
    WHERE sub.region_id = $1
    AND sub.date <= (SELECT latest.date - INTERVAL '1 year' FROM latest)
    ORDER BY sub.date DESC
    LIMIT 1
)
SELECT
    l.zhvi AS current_zhvi,
    l.zori AS current_zori,
    l.date AS latest_date,
    CASE WHEN y.zhvi > 0 THEN ((l.zhvi - y.zhvi) / y.zhvi * 100) ELSE 0 END AS zhvi_yoy_pct,
    CASE WHEN y.zori > 0 THEN ((l.zori - y.zori) / y.zori * 100) ELSE 0 END AS zori_yoy_pct
FROM latest l, year_ago y
`

type GetYearOverYearChangeRow struct {
	CurrentZhvi pgtype.Numeric `json:"current_zhvi"`
	CurrentZori pgtype.Numeric `json:"current_zori"`
	LatestDate  pgtype.Date    `json:"latest_date"`
	ZhviYoyPct  int32          `json:"zhvi_yoy_pct"`
	ZoriYoyPct  int32          `json:"zori_yoy_pct"`
}

func (q *Queries) GetYearOverYearChange(ctx context.Context, regionID int32) (GetYearOverYearChangeRow, error) {
	row := q.db.QueryRow(ctx, GetYearOverYearChange, regionID)
	var i GetYearOverYearChangeRow
	err := row.Scan(
		&i.CurrentZhvi,
		&i.CurrentZori,
		&i.LatestDate,
		&i.ZhviYoyPct,
		&i.ZoriYoyPct,
	)
	return i, err
}

const ListAvailableRegions = `-- name: ListAvailableRegions :many
SELECT DISTINCT region_id, region_name, region_type, state_code
FROM metro_timeseries
WHERE region_type = $1
ORDER BY region_name
LIMIT $2 OFFSET $3
`

type ListAvailableRegionsParams struct {
	RegionType string `json:"region_type"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type ListAvailableRegionsRow struct {
	RegionID   int32       `json:"region_id"`
	RegionName string      `json:"region_name"`
	RegionType string      `json:"region_type"`
	StateCode  pgtype.Text `json:"state_code"`
}

func (q *Queries) ListAvailableRegions(ctx context.Context, arg ListAvailableRegionsParams) ([]ListAvailableRegionsRow, error) {
	rows, err := q.db.Query(ctx, ListAvailableRegions, arg.RegionType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableRegionsRow{}
	for rows.Next() {
		var i ListAvailableRegionsRow
		if err := rows.Scan(
			&i.RegionID,
			&i.RegionName,
			&i.RegionType,
			&i.StateCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchMetroByName = `-- name: SearchMetroByName :many
SELECT DISTINCT region_id, region_name, region_type, state_code, metro
FROM metro_timeseries
WHERE region_name ILIKE $1
ORDER BY region_name
LIMIT $2
`

type SearchMetroByNameParams struct {
	RegionName string `json:"region_name"`
	Limit      int32  `json:"limit"`
}

type SearchMetroByNameRow struct {
	RegionID   int32       `json:"region_id"`
	RegionName string      `json:"region_name"`
	RegionType string      `json:"region_type"`
	StateCode  pgtype.Text `json:"state_code"`
	Metro      pgtype.Text `json:"metro"`
}

func (q *Queries) SearchMetroByName(ctx context.Context, arg SearchMetroByNameParams) ([]SearchMetroByNameRow, error) {
	rows, err := q.db.Query(ctx, SearchMetroByName, arg.RegionName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMetroByNameRow{}
	for rows.Next() {
		var i SearchMetroByNameRow
		if err := rows.Scan(
			&i.RegionID,
			&i.RegionName,
			&i.RegionType,
			&i.StateCode,
			&i.Metro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
