// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: market.sql

package marketqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetCitiesNeedingRefresh = `-- name: GetCitiesNeedingRefresh :many
SELECT
    c.id,
    c.city,
    c.state,
    c.ttl_expires_at,
    c.last_updated
FROM city_market_cache c
WHERE c.ttl_expires_at < NOW()
ORDER BY c.ttl_expires_at
LIMIT $1
`

type GetCitiesNeedingRefreshRow struct {
	ID           int32            `json:"id"`
	City         string           `json:"city"`
	State        string           `json:"state"`
	TtlExpiresAt pgtype.Timestamp `json:"ttl_expires_at"`
	LastUpdated  pgtype.Timestamp `json:"last_updated"`
}

// Get cities where cache has expired
func (q *Queries) GetCitiesNeedingRefresh(ctx context.Context, limit int32) ([]GetCitiesNeedingRefreshRow, error) {
	rows, err := q.db.Query(ctx, GetCitiesNeedingRefresh, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCitiesNeedingRefreshRow{}
	for rows.Next() {
		var i GetCitiesNeedingRefreshRow
		if err := rows.Scan(
			&i.ID,
			&i.City,
			&i.State,
			&i.TtlExpiresAt,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetCityCount = `-- name: GetCityCount :one
SELECT COUNT(*) FROM city_market_cache
`

// Get total count of cached cities
func (q *Queries) GetCityCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, GetCityCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetCityCountByState = `-- name: GetCityCountByState :one
SELECT COUNT(*) FROM city_market_cache WHERE state = $1
`

// Get count of cached cities in a state
func (q *Queries) GetCityCountByState(ctx context.Context, state string) (int64, error) {
	row := q.db.QueryRow(ctx, GetCityCountByState, state)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetCityMarketData = `-- name: GetCityMarketData :one


SELECT
    c.id,
    c.location_key,
    c.city,
    c.state,
    c.metro_region_id,
    COALESCE(m.metro_name, '') AS metro_name,
    c.median_home_price,
    c.median_price_per_sqft,
    c.median_list_price,
    c.homes_sold,
    c.inventory_count,
    c.months_of_supply,
    c.median_days_on_market,
    c.price_yoy_change,
    c.forecast_growth,
    c.median_rent,
    c.rent_yoy_change,
    c.rental_yield,
    c.cap_rate,
    c.price_to_rent_ratio,
    c.vacancy_rate,
    c.population,
    c.median_household_income,
    c.unemployment_rate,
    c.market_heat_index,
    c.market_temperature,
    c.affordability_index,
    c.data_sources,
    c.data_quality_score,
    c.data_date,
    c.last_updated,
    c.is_ai_estimated,
    c.ai_confidence_score
FROM city_market_cache c
LEFT JOIN metro_time_series m ON c.metro_region_id = m.metro_region_id
WHERE c.city ILIKE $1 AND c.state = $2
LIMIT 1
`

type GetCityMarketDataParams struct {
	City  string `json:"city"`
	State string `json:"state"`
}

type GetCityMarketDataRow struct {
	ID                    int32            `json:"id"`
	LocationKey           string           `json:"location_key"`
	City                  string           `json:"city"`
	State                 string           `json:"state"`
	MetroRegionID         pgtype.Int4      `json:"metro_region_id"`
	MetroName             string           `json:"metro_name"`
	MedianHomePrice       pgtype.Numeric   `json:"median_home_price"`
	MedianPricePerSqft    pgtype.Numeric   `json:"median_price_per_sqft"`
	MedianListPrice       pgtype.Numeric   `json:"median_list_price"`
	HomesSold             pgtype.Int4      `json:"homes_sold"`
	InventoryCount        pgtype.Int4      `json:"inventory_count"`
	MonthsOfSupply        pgtype.Numeric   `json:"months_of_supply"`
	MedianDaysOnMarket    pgtype.Int4      `json:"median_days_on_market"`
	PriceYoyChange        pgtype.Numeric   `json:"price_yoy_change"`
	ForecastGrowth        pgtype.Numeric   `json:"forecast_growth"`
	MedianRent            pgtype.Numeric   `json:"median_rent"`
	RentYoyChange         pgtype.Numeric   `json:"rent_yoy_change"`
	RentalYield           pgtype.Numeric   `json:"rental_yield"`
	CapRate               pgtype.Numeric   `json:"cap_rate"`
	PriceToRentRatio      pgtype.Numeric   `json:"price_to_rent_ratio"`
	VacancyRate           pgtype.Numeric   `json:"vacancy_rate"`
	Population            pgtype.Int4      `json:"population"`
	MedianHouseholdIncome pgtype.Numeric   `json:"median_household_income"`
	UnemploymentRate      pgtype.Numeric   `json:"unemployment_rate"`
	MarketHeatIndex       pgtype.Numeric   `json:"market_heat_index"`
	MarketTemperature     pgtype.Text      `json:"market_temperature"`
	AffordabilityIndex    pgtype.Numeric   `json:"affordability_index"`
	DataSources           []byte           `json:"data_sources"`
	DataQualityScore      int32            `json:"data_quality_score"`
	DataDate              string           `json:"data_date"`
	LastUpdated           pgtype.Timestamp `json:"last_updated"`
	IsAiEstimated         bool             `json:"is_ai_estimated"`
	AiConfidenceScore     pgtype.Int4      `json:"ai_confidence_score"`
}

// Market Database Queries
// These queries are validated against the schema at compile time by sqlc.
// If column names don't match, sqlc will fail to generate code.
// ============================================================================
// CITY MARKET CACHE QUERIES
// ============================================================================
// Get market data for a specific city, joined with metro for metro name
func (q *Queries) GetCityMarketData(ctx context.Context, arg GetCityMarketDataParams) (GetCityMarketDataRow, error) {
	row := q.db.QueryRow(ctx, GetCityMarketData, arg.City, arg.State)
	var i GetCityMarketDataRow
	err := row.Scan(
		&i.ID,
		&i.LocationKey,
		&i.City,
		&i.State,
		&i.MetroRegionID,
		&i.MetroName,
		&i.MedianHomePrice,
		&i.MedianPricePerSqft,
		&i.MedianListPrice,
		&i.HomesSold,
		&i.InventoryCount,
		&i.MonthsOfSupply,
		&i.MedianDaysOnMarket,
		&i.PriceYoyChange,
		&i.ForecastGrowth,
		&i.MedianRent,
		&i.RentYoyChange,
		&i.RentalYield,
		&i.CapRate,
		&i.PriceToRentRatio,
		&i.VacancyRate,
		&i.Population,
		&i.MedianHouseholdIncome,
		&i.UnemploymentRate,
		&i.MarketHeatIndex,
		&i.MarketTemperature,
		&i.AffordabilityIndex,
		&i.DataSources,
		&i.DataQualityScore,
		&i.DataDate,
		&i.LastUpdated,
		&i.IsAiEstimated,
		&i.AiConfidenceScore,
	)
	return i, err
}

const GetCityMetroMapping = `-- name: GetCityMetroMapping :one
SELECT
    c.city,
    c.state,
    COALESCE(m.metro_name, '') AS metro_name,
    COALESCE(c.metro_region_id, 0) AS metro_region_id
FROM city_market_cache c
LEFT JOIN metro_time_series m ON c.metro_region_id = m.metro_region_id
WHERE c.city ILIKE $1 AND c.state = $2
LIMIT 1
`

type GetCityMetroMappingParams struct {
	City  string `json:"city"`
	State string `json:"state"`
}

type GetCityMetroMappingRow struct {
	City          string `json:"city"`
	State         string `json:"state"`
	MetroName     string `json:"metro_name"`
	MetroRegionID int32  `json:"metro_region_id"`
}

// Get the metro mapping for a city (for fallback to metro-level data)
func (q *Queries) GetCityMetroMapping(ctx context.Context, arg GetCityMetroMappingParams) (GetCityMetroMappingRow, error) {
	row := q.db.QueryRow(ctx, GetCityMetroMapping, arg.City, arg.State)
	var i GetCityMetroMappingRow
	err := row.Scan(
		&i.City,
		&i.State,
		&i.MetroName,
		&i.MetroRegionID,
	)
	return i, err
}

const GetCitySnapshot = `-- name: GetCitySnapshot :one

SELECT
    c.id,
    c.location_key,
    c.city,
    c.state,
    c.metro_region_id,
    COALESCE(m.metro_name, '') AS metro_name,
    c.median_home_price,
    c.median_price_per_sqft,
    c.median_list_price,
    c.homes_sold,
    c.inventory_count,
    c.months_of_supply,
    c.median_days_on_market,
    c.price_yoy_change,
    c.forecast_growth,
    c.median_rent,
    c.rent_yoy_change,
    c.rental_yield,
    c.cap_rate,
    c.price_to_rent_ratio,
    c.vacancy_rate,
    c.hud_fmr_0br,
    c.hud_fmr_1br,
    c.hud_fmr_2br,
    c.hud_fmr_3br,
    c.hud_fmr_4br,
    c.population,
    c.population_growth_rate,
    c.median_household_income,
    c.unemployment_rate,
    c.employment_growth_rate,
    c.market_heat_index,
    c.market_temperature,
    c.affordability_index,
    c.affordability_burden,
    c.price_to_income_ratio,
    c.data_sources,
    c.data_quality_score,
    c.data_date,
    c.last_updated,
    c.is_ai_estimated,
    c.ai_confidence_score
FROM city_market_cache c
LEFT JOIN metro_time_series m ON c.metro_region_id = m.metro_region_id
WHERE c.city ILIKE $1 AND c.state = $2
LIMIT 1
`

type GetCitySnapshotParams struct {
	City  string `json:"city"`
	State string `json:"state"`
}

type GetCitySnapshotRow struct {
	ID                    int32            `json:"id"`
	LocationKey           string           `json:"location_key"`
	City                  string           `json:"city"`
	State                 string           `json:"state"`
	MetroRegionID         pgtype.Int4      `json:"metro_region_id"`
	MetroName             string           `json:"metro_name"`
	MedianHomePrice       pgtype.Numeric   `json:"median_home_price"`
	MedianPricePerSqft    pgtype.Numeric   `json:"median_price_per_sqft"`
	MedianListPrice       pgtype.Numeric   `json:"median_list_price"`
	HomesSold             pgtype.Int4      `json:"homes_sold"`
	InventoryCount        pgtype.Int4      `json:"inventory_count"`
	MonthsOfSupply        pgtype.Numeric   `json:"months_of_supply"`
	MedianDaysOnMarket    pgtype.Int4      `json:"median_days_on_market"`
	PriceYoyChange        pgtype.Numeric   `json:"price_yoy_change"`
	ForecastGrowth        pgtype.Numeric   `json:"forecast_growth"`
	MedianRent            pgtype.Numeric   `json:"median_rent"`
	RentYoyChange         pgtype.Numeric   `json:"rent_yoy_change"`
	RentalYield           pgtype.Numeric   `json:"rental_yield"`
	CapRate               pgtype.Numeric   `json:"cap_rate"`
	PriceToRentRatio      pgtype.Numeric   `json:"price_to_rent_ratio"`
	VacancyRate           pgtype.Numeric   `json:"vacancy_rate"`
	HudFmr0br             pgtype.Numeric   `json:"hud_fmr_0br"`
	HudFmr1br             pgtype.Numeric   `json:"hud_fmr_1br"`
	HudFmr2br             pgtype.Numeric   `json:"hud_fmr_2br"`
	HudFmr3br             pgtype.Numeric   `json:"hud_fmr_3br"`
	HudFmr4br             pgtype.Numeric   `json:"hud_fmr_4br"`
	Population            pgtype.Int4      `json:"population"`
	PopulationGrowthRate  pgtype.Numeric   `json:"population_growth_rate"`
	MedianHouseholdIncome pgtype.Numeric   `json:"median_household_income"`
	UnemploymentRate      pgtype.Numeric   `json:"unemployment_rate"`
	EmploymentGrowthRate  pgtype.Numeric   `json:"employment_growth_rate"`
	MarketHeatIndex       pgtype.Numeric   `json:"market_heat_index"`
	MarketTemperature     pgtype.Text      `json:"market_temperature"`
	AffordabilityIndex    pgtype.Numeric   `json:"affordability_index"`
	AffordabilityBurden   pgtype.Text      `json:"affordability_burden"`
	PriceToIncomeRatio    pgtype.Numeric   `json:"price_to_income_ratio"`
	DataSources           []byte           `json:"data_sources"`
	DataQualityScore      int32            `json:"data_quality_score"`
	DataDate              string           `json:"data_date"`
	LastUpdated           pgtype.Timestamp `json:"last_updated"`
	IsAiEstimated         bool             `json:"is_ai_estimated"`
	AiConfidenceScore     pgtype.Int4      `json:"ai_confidence_score"`
}

// ============================================================================
// AUTOCOMPLETE QUERIES (ADR-073: Market Intelligence)
// ============================================================================
// Get ALL fields from city_market_cache for a city (ADR-074: DATA_PAYLOAD builder)
func (q *Queries) GetCitySnapshot(ctx context.Context, arg GetCitySnapshotParams) (GetCitySnapshotRow, error) {
	row := q.db.QueryRow(ctx, GetCitySnapshot, arg.City, arg.State)
	var i GetCitySnapshotRow
	err := row.Scan(
		&i.ID,
		&i.LocationKey,
		&i.City,
		&i.State,
		&i.MetroRegionID,
		&i.MetroName,
		&i.MedianHomePrice,
		&i.MedianPricePerSqft,
		&i.MedianListPrice,
		&i.HomesSold,
		&i.InventoryCount,
		&i.MonthsOfSupply,
		&i.MedianDaysOnMarket,
		&i.PriceYoyChange,
		&i.ForecastGrowth,
		&i.MedianRent,
		&i.RentYoyChange,
		&i.RentalYield,
		&i.CapRate,
		&i.PriceToRentRatio,
		&i.VacancyRate,
		&i.HudFmr0br,
		&i.HudFmr1br,
		&i.HudFmr2br,
		&i.HudFmr3br,
		&i.HudFmr4br,
		&i.Population,
		&i.PopulationGrowthRate,
		&i.MedianHouseholdIncome,
		&i.UnemploymentRate,
		&i.EmploymentGrowthRate,
		&i.MarketHeatIndex,
		&i.MarketTemperature,
		&i.AffordabilityIndex,
		&i.AffordabilityBurden,
		&i.PriceToIncomeRatio,
		&i.DataSources,
		&i.DataQualityScore,
		&i.DataDate,
		&i.LastUpdated,
		&i.IsAiEstimated,
		&i.AiConfidenceScore,
	)
	return i, err
}

const GetMetroByName = `-- name: GetMetroByName :one

SELECT
    id,
    metro_region_id,
    metro_name,
    state_name,
    zhvi_data,
    zori_data,
    zhvf_data,
    sales_count_data,
    days_on_market_data,
    market_heat_data,
    created_at,
    updated_at
FROM metro_time_series
WHERE metro_name ILIKE $1
LIMIT 1
`

type GetMetroByNameRow struct {
	ID               int32            `json:"id"`
	MetroRegionID    int32            `json:"metro_region_id"`
	MetroName        string           `json:"metro_name"`
	StateName        pgtype.Text      `json:"state_name"`
	ZhviData         []byte           `json:"zhvi_data"`
	ZoriData         []byte           `json:"zori_data"`
	ZhvfData         []byte           `json:"zhvf_data"`
	SalesCountData   []byte           `json:"sales_count_data"`
	DaysOnMarketData []byte           `json:"days_on_market_data"`
	MarketHeatData   []byte           `json:"market_heat_data"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

// ============================================================================
// METRO TIME SERIES QUERIES
// ============================================================================
// Get metro data by name
func (q *Queries) GetMetroByName(ctx context.Context, metroName string) (GetMetroByNameRow, error) {
	row := q.db.QueryRow(ctx, GetMetroByName, metroName)
	var i GetMetroByNameRow
	err := row.Scan(
		&i.ID,
		&i.MetroRegionID,
		&i.MetroName,
		&i.StateName,
		&i.ZhviData,
		&i.ZoriData,
		&i.ZhvfData,
		&i.SalesCountData,
		&i.DaysOnMarketData,
		&i.MarketHeatData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMetroByRegionID = `-- name: GetMetroByRegionID :one
SELECT
    id,
    metro_region_id,
    metro_name,
    state_name,
    zhvi_data,
    zori_data,
    zhvf_data,
    sales_count_data,
    days_on_market_data,
    market_heat_data,
    created_at,
    updated_at
FROM metro_time_series
WHERE metro_region_id = $1
LIMIT 1
`

type GetMetroByRegionIDRow struct {
	ID               int32            `json:"id"`
	MetroRegionID    int32            `json:"metro_region_id"`
	MetroName        string           `json:"metro_name"`
	StateName        pgtype.Text      `json:"state_name"`
	ZhviData         []byte           `json:"zhvi_data"`
	ZoriData         []byte           `json:"zori_data"`
	ZhvfData         []byte           `json:"zhvf_data"`
	SalesCountData   []byte           `json:"sales_count_data"`
	DaysOnMarketData []byte           `json:"days_on_market_data"`
	MarketHeatData   []byte           `json:"market_heat_data"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

// Get metro data by region ID
func (q *Queries) GetMetroByRegionID(ctx context.Context, metroRegionID int32) (GetMetroByRegionIDRow, error) {
	row := q.db.QueryRow(ctx, GetMetroByRegionID, metroRegionID)
	var i GetMetroByRegionIDRow
	err := row.Scan(
		&i.ID,
		&i.MetroRegionID,
		&i.MetroName,
		&i.StateName,
		&i.ZhviData,
		&i.ZoriData,
		&i.ZhvfData,
		&i.SalesCountData,
		&i.DaysOnMarketData,
		&i.MarketHeatData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMetroCount = `-- name: GetMetroCount :one
SELECT COUNT(*) FROM metro_time_series
`

// Get total count of metros
func (q *Queries) GetMetroCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, GetMetroCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetNationalTimeSeries = `-- name: GetNationalTimeSeries :one
SELECT
    metro_region_id,
    metro_name,
    zhvi_data,
    zori_data,
    zhvf_data,
    updated_at
FROM metro_time_series
WHERE metro_region_id = 0
LIMIT 1
`

type GetNationalTimeSeriesRow struct {
	MetroRegionID int32            `json:"metro_region_id"`
	MetroName     string           `json:"metro_name"`
	ZhviData      []byte           `json:"zhvi_data"`
	ZoriData      []byte           `json:"zori_data"`
	ZhvfData      []byte           `json:"zhvf_data"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

// Get national aggregate ZHVI/ZORI from metro_time_series (metro_region_id=0)
// Used for national benchmark comparison in DATA_PAYLOAD (ADR-074)
func (q *Queries) GetNationalTimeSeries(ctx context.Context) (GetNationalTimeSeriesRow, error) {
	row := q.db.QueryRow(ctx, GetNationalTimeSeries)
	var i GetNationalTimeSeriesRow
	err := row.Scan(
		&i.MetroRegionID,
		&i.MetroName,
		&i.ZhviData,
		&i.ZoriData,
		&i.ZhvfData,
		&i.UpdatedAt,
	)
	return i, err
}

const ListCitiesByState = `-- name: ListCitiesByState :many
SELECT
    c.city,
    c.state,
    c.median_home_price,
    c.median_rent,
    c.cap_rate,
    c.data_quality_score,
    c.is_ai_estimated
FROM city_market_cache c
WHERE c.state = $1
ORDER BY c.city
LIMIT $2 OFFSET $3
`

type ListCitiesByStateParams struct {
	State  string `json:"state"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListCitiesByStateRow struct {
	City             string         `json:"city"`
	State            string         `json:"state"`
	MedianHomePrice  pgtype.Numeric `json:"median_home_price"`
	MedianRent       pgtype.Numeric `json:"median_rent"`
	CapRate          pgtype.Numeric `json:"cap_rate"`
	DataQualityScore int32          `json:"data_quality_score"`
	IsAiEstimated    bool           `json:"is_ai_estimated"`
}

// List all cities in a state with their market data
func (q *Queries) ListCitiesByState(ctx context.Context, arg ListCitiesByStateParams) ([]ListCitiesByStateRow, error) {
	rows, err := q.db.Query(ctx, ListCitiesByState, arg.State, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCitiesByStateRow{}
	for rows.Next() {
		var i ListCitiesByStateRow
		if err := rows.Scan(
			&i.City,
			&i.State,
			&i.MedianHomePrice,
			&i.MedianRent,
			&i.CapRate,
			&i.DataQualityScore,
			&i.IsAiEstimated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMetrosByState = `-- name: ListMetrosByState :many
SELECT
    metro_region_id,
    metro_name,
    state_name
FROM metro_time_series
WHERE state_name = $1
ORDER BY metro_name
`

type ListMetrosByStateRow struct {
	MetroRegionID int32       `json:"metro_region_id"`
	MetroName     string      `json:"metro_name"`
	StateName     pgtype.Text `json:"state_name"`
}

// List all metros in a state
func (q *Queries) ListMetrosByState(ctx context.Context, stateName pgtype.Text) ([]ListMetrosByStateRow, error) {
	rows, err := q.db.Query(ctx, ListMetrosByState, stateName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMetrosByStateRow{}
	for rows.Next() {
		var i ListMetrosByStateRow
		if err := rows.Scan(&i.MetroRegionID, &i.MetroName, &i.StateName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchCities = `-- name: SearchCities :many
SELECT
    c.city,
    c.state,
    COALESCE(c.population, 0) AS population,
    COALESCE(m.metro_name, '') AS metro_name,
    CASE WHEN c.median_home_price IS NOT NULL THEN true ELSE false END AS has_market_data,
    CASE WHEN c.median_rent IS NOT NULL THEN true ELSE false END AS has_rental_data
FROM city_market_cache c
LEFT JOIN metro_time_series m ON c.metro_region_id = m.metro_region_id
WHERE c.city ILIKE $1
ORDER BY COALESCE(c.population, 0) DESC
LIMIT $2
`

type SearchCitiesParams struct {
	City  string `json:"city"`
	Limit int32  `json:"limit"`
}

type SearchCitiesRow struct {
	City          string `json:"city"`
	State         string `json:"state"`
	Population    int32  `json:"population"`
	MetroName     string `json:"metro_name"`
	HasMarketData bool   `json:"has_market_data"`
	HasRentalData bool   `json:"has_rental_data"`
}

// Search cities by name for autocomplete
func (q *Queries) SearchCities(ctx context.Context, arg SearchCitiesParams) ([]SearchCitiesRow, error) {
	rows, err := q.db.Query(ctx, SearchCities, arg.City, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCitiesRow{}
	for rows.Next() {
		var i SearchCitiesRow
		if err := rows.Scan(
			&i.City,
			&i.State,
			&i.Population,
			&i.MetroName,
			&i.HasMarketData,
			&i.HasRentalData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchMetros = `-- name: SearchMetros :many
SELECT DISTINCT
    metro_region_id,
    metro_name,
    state_name
FROM metro_time_series
WHERE metro_name ILIKE $1
ORDER BY metro_name
LIMIT $2
`

type SearchMetrosParams struct {
	MetroName string `json:"metro_name"`
	Limit     int32  `json:"limit"`
}

type SearchMetrosRow struct {
	MetroRegionID int32       `json:"metro_region_id"`
	MetroName     string      `json:"metro_name"`
	StateName     pgtype.Text `json:"state_name"`
}

// Search metros by name pattern
func (q *Queries) SearchMetros(ctx context.Context, arg SearchMetrosParams) ([]SearchMetrosRow, error) {
	rows, err := q.db.Query(ctx, SearchMetros, arg.MetroName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMetrosRow{}
	for rows.Next() {
		var i SearchMetrosRow
		if err := rows.Scan(&i.MetroRegionID, &i.MetroName, &i.StateName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
