// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package marketqueries

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CityMetroMapping struct {
	ID            int32       `json:"id"`
	City          string      `json:"city"`
	StateCode     string      `json:"state_code"`
	MetroName     string      `json:"metro_name"`
	MetroRegionID pgtype.Int4 `json:"metro_region_id"`
	CreatedAt     time.Time   `json:"created_at"`
}

type MetroTimeseries struct {
	ID           int32          `json:"id"`
	RegionID     int32          `json:"region_id"`
	RegionName   string         `json:"region_name"`
	RegionType   string         `json:"region_type"`
	StateCode    pgtype.Text    `json:"state_code"`
	Metro        pgtype.Text    `json:"metro"`
	Date         pgtype.Date    `json:"date"`
	Zhvi         pgtype.Numeric `json:"zhvi"`
	Zori         pgtype.Numeric `json:"zori"`
	ZhviForecast pgtype.Numeric `json:"zhvi_forecast"`
	ZoriForecast pgtype.Numeric `json:"zori_forecast"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
