// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package marketqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Get all metros for city→metro linking during import
	GetAllMetroLookup(ctx context.Context) ([]GetAllMetroLookupRow, error)
	// Get all state ZHVI data for national aggregation
	GetAllStateZHVI(ctx context.Context) ([]GetAllStateZHVIRow, error)
	// Get cities where cache has expired
	GetCitiesNeedingRefresh(ctx context.Context, limit int32) ([]GetCitiesNeedingRefreshRow, error)
	// Get total count of cached cities
	GetCityCount(ctx context.Context) (int64, error)
	// Get count of cached cities in a state
	GetCityCountByState(ctx context.Context, state string) (int64, error)
	// Market Database Queries
	// These queries are validated against the schema at compile time by sqlc.
	// If column names don't match, sqlc will fail to generate code.
	// ============================================================================
	// CITY MARKET CACHE QUERIES
	// ============================================================================
	// Get market data for a specific city, joined with metro for metro name
	GetCityMarketData(ctx context.Context, arg GetCityMarketDataParams) (GetCityMarketDataRow, error)
	// Get the metro mapping for a city (for fallback to metro-level data)
	GetCityMetroMapping(ctx context.Context, arg GetCityMetroMappingParams) (GetCityMetroMappingRow, error)
	// ============================================================================
	// AUTOCOMPLETE QUERIES (ADR-073: Market Intelligence)
	// ============================================================================
	// Get ALL fields from city_market_cache for a city (ADR-074: DATA_PAYLOAD builder)
	GetCitySnapshot(ctx context.Context, arg GetCitySnapshotParams) (GetCitySnapshotRow, error)
	// Get total count of city time-series entries
	GetCityTimeSeriesCount(ctx context.Context) (int64, error)
	// Get most recent city time-series update timestamp
	GetCityTimeSeriesFreshness(ctx context.Context) (interface{}, error)
	// Get most recent county update timestamp
	GetCountyFreshness(ctx context.Context) (interface{}, error)
	// Get total count of county time-series entries
	GetCountyTimeSeriesCount(ctx context.Context) (int64, error)
	// Returns total counts of tracked cities and metros
	GetMarketPulseCounts(ctx context.Context) (GetMarketPulseCountsRow, error)
	// Market Pulse Queries
	// Public-facing queries for the sign-in page market pulse display.
	// Returns high-quality cities and counts for the live market ticker.
	// Returns high-quality cities for the market pulse ticker display
	GetMarketPulseTickerCities(ctx context.Context) ([]GetMarketPulseTickerCitiesRow, error)
	// ============================================================================
	// METRO TIME SERIES QUERIES
	// ============================================================================
	// Get metro data by name
	GetMetroByName(ctx context.Context, metroName string) (GetMetroByNameRow, error)
	// Get metro data by region ID
	GetMetroByRegionID(ctx context.Context, metroRegionID int32) (GetMetroByRegionIDRow, error)
	// Get total count of metros
	GetMetroCount(ctx context.Context) (int64, error)
	// ============================================================================
	// STATUS QUERIES (ADR-075: Market data freshness)
	// ============================================================================
	// Get most recent metro update timestamp
	GetMetroFreshness(ctx context.Context) (interface{}, error)
	// Get national aggregate ZHVI/ZORI from metro_time_series (metro_region_id=0)
	// Used for national benchmark comparison in DATA_PAYLOAD (ADR-074)
	GetNationalTimeSeries(ctx context.Context) (GetNationalTimeSeriesRow, error)
	// Returns metros that have ZHVI data (for daily-rotating sparkline selection).
	// Orders by metro_name for deterministic rotation.
	GetSparklineMetros(ctx context.Context) ([]GetSparklineMetrosRow, error)
	// Get most recent state update timestamp
	GetStateFreshness(ctx context.Context) (interface{}, error)
	// Get total count of state time-series entries
	GetStateTimeSeriesCount(ctx context.Context) (int64, error)
	// Get most recent zip update timestamp
	GetZipFreshness(ctx context.Context) (interface{}, error)
	// Get total count of zip time-series entries
	GetZipTimeSeriesCount(ctx context.Context) (int64, error)
	// List all cities in a state with their market data
	ListCitiesByState(ctx context.Context, arg ListCitiesByStateParams) ([]ListCitiesByStateRow, error)
	// List all metros in a state
	ListMetrosByState(ctx context.Context, stateName pgtype.Text) ([]ListMetrosByStateRow, error)
	// Search cities by name for autocomplete
	SearchCities(ctx context.Context, arg SearchCitiesParams) ([]SearchCitiesRow, error)
	// Search metros by name pattern
	SearchMetros(ctx context.Context, arg SearchMetrosParams) ([]SearchMetrosRow, error)
	// Upsert city Redfin data (keyed by city_name + state since Redfin has no region IDs)
	UpsertCityRedfin(ctx context.Context, arg UpsertCityRedfinParams) error
	// ============================================================================
	// CITY TIME SERIES UPSERT QUERIES (ADR-075)
	// ============================================================================
	// Upsert city ZHVI time-series data
	UpsertCityZHVI(ctx context.Context, arg UpsertCityZHVIParams) error
	// Upsert city ZORI time-series data
	UpsertCityZORI(ctx context.Context, arg UpsertCityZORIParams) error
	// ============================================================================
	// COUNTY TIME SERIES UPSERT QUERIES (ADR-075)
	// ============================================================================
	// Upsert county Redfin data (keyed by county_region_id since county_fips may be null)
	UpsertCountyRedfin(ctx context.Context, arg UpsertCountyRedfinParams) error
	// Upsert metro sales/DOM/heat/affordability metrics
	UpsertMetroMetrics(ctx context.Context, arg UpsertMetroMetricsParams) error
	// Upsert metro Redfin data
	UpsertMetroRedfin(ctx context.Context, arg UpsertMetroRedfinParams) error
	// Upsert metro ZHVI forecast data
	UpsertMetroZHVF(ctx context.Context, arg UpsertMetroZHVFParams) error
	// ============================================================================
	// METRO TIME SERIES UPSERT QUERIES (ADR-075: Market Data Import)
	// ============================================================================
	// Upsert metro ZHVI time-series data
	UpsertMetroZHVI(ctx context.Context, arg UpsertMetroZHVIParams) error
	// Upsert metro ZORI time-series data
	UpsertMetroZORI(ctx context.Context, arg UpsertMetroZORIParams) error
	// Upsert state Redfin data
	UpsertStateRedfin(ctx context.Context, arg UpsertStateRedfinParams) error
	// ============================================================================
	// STATE TIME SERIES UPSERT QUERIES (ADR-075)
	// ============================================================================
	// Upsert state ZHVI time-series data
	UpsertStateZHVI(ctx context.Context, arg UpsertStateZHVIParams) error
	// Upsert zip Redfin data
	UpsertZipRedfin(ctx context.Context, arg UpsertZipRedfinParams) error
	// ============================================================================
	// ZIP TIME SERIES UPSERT QUERIES (ADR-075)
	// ============================================================================
	// Upsert zip ZHVI time-series data
	UpsertZipZHVI(ctx context.Context, arg UpsertZipZHVIParams) error
	// Upsert zip ZORI time-series data
	UpsertZipZORI(ctx context.Context, arg UpsertZipZORIParams) error
}

var _ Querier = (*Queries)(nil)
