// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package marketqueries

import (
	"context"
)

type Querier interface {
	GetCityMetroMapping(ctx context.Context, arg GetCityMetroMappingParams) (CityMetroMapping, error)
	GetLatestMetroData(ctx context.Context, arg GetLatestMetroDataParams) (MetroTimeseries, error)
	GetLatestMetroDataByID(ctx context.Context, regionID int32) (MetroTimeseries, error)
	GetMetroDataByState(ctx context.Context, arg GetMetroDataByStateParams) ([]MetroTimeseries, error)
	GetMetroForCity(ctx context.Context, arg GetMetroForCityParams) (MetroTimeseries, error)
	GetMetroTimeSeries(ctx context.Context, arg GetMetroTimeSeriesParams) ([]MetroTimeseries, error)
	GetMetroTimeSeriesByID(ctx context.Context, arg GetMetroTimeSeriesByIDParams) ([]MetroTimeseries, error)
	GetYearOverYearChange(ctx context.Context, regionID int32) (GetYearOverYearChangeRow, error)
	ListAvailableRegions(ctx context.Context, arg ListAvailableRegionsParams) ([]ListAvailableRegionsRow, error)
	SearchMetroByName(ctx context.Context, arg SearchMetroByNameParams) ([]SearchMetroByNameRow, error)
}

var _ Querier = (*Queries)(nil)
