-- AI Usage tracking (for sqlc validation)
-- Note: This table is managed by Prisma/legacy migrations, schema is for sqlc only

CREATE TABLE IF NOT EXISTS ai_usage (
    id TEXT PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    model TEXT NOT NULL,
    "inputTokens" INTEGER NOT NULL,
    "outputTokens" INTEGER NOT NULL,
    "cacheCreationTokens" INTEGER NOT NULL DEFAULT 0,
    "cacheReadTokens" INTEGER NOT NULL DEFAULT 0,
    "totalTokens" INTEGER NOT NULL,
    "baseInputCost" NUMERIC(10,6) NOT NULL,
    "cacheCreationCost" NUMERIC(10,6) NOT NULL DEFAULT 0,
    "cacheReadCost" NUMERIC(10,6) NOT NULL DEFAULT 0,
    "outputCost" NUMERIC(10,6) NOT NULL,
    "totalCost" NUMERIC(10,6) NOT NULL,
    "requestType" TEXT NOT NULL,
    feature TEXT NOT NULL,
    location TEXT,
    "requestId" TEXT NOT NULL,
    "userAgent" TEXT,
    "ipAddress" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "actualResponseTime" INTEGER,
    "agentType" TEXT,
    "agentVersion" TEXT,
    "apiLatency" INTEGER,
    "cacheHit" BOOLEAN NOT NULL DEFAULT false,
    "contentFiltered" BOOLEAN NOT NULL DEFAULT false,
    "errorCode" TEXT,
    "errorMessage" TEXT,
    "errorType" TEXT,
    "fallbackModel" TEXT,
    "fallbackUsed" BOOLEAN NOT NULL DEFAULT false,
    "processingTime" INTEGER,
    "queueTime" INTEGER,
    "responseComplexity" TEXT,
    "responseLength" INTEGER,
    "retryCount" INTEGER NOT NULL DEFAULT 0,
    "securityProcessed" BOOLEAN NOT NULL DEFAULT true,
    "userRating" INTEGER,
    "validationScore" NUMERIC
);
