-- ADR-101: Pipeline schema for sqlc validation

CREATE TABLE IF NOT EXISTS pipeline_deals (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          TEXT NOT NULL,
    name             TEXT NOT NULL,
    source           TEXT NOT NULL DEFAULT 'broker',
    status           TEXT NOT NULL DEFAULT 'under_review',
    notes            TEXT,
    property_count   INTEGER NOT NULL DEFAULT 0,
    memo_count       INTEGER NOT NULL DEFAULT 0,
    portfolio_excluded BOOLEAN NOT NULL DEFAULT FALSE,
    last_activity_at TIMESTAMPTZ,
    closed_outcome   TEXT,
    input_complete   BOOLEAN NOT NULL DEFAULT false, -- ADR-107: deal ready for analysis
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pipeline_properties (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pipeline_deal_id  UUID NOT NULL REFERENCES pipeline_deals(id) ON DELETE CASCADE,
    address           TEXT NOT NULL,
    city              TEXT,
    state             TEXT,
    zip               TEXT,
    property_type     TEXT,
    beds              NUMERIC,
    baths             NUMERIC,
    sqft              INTEGER,
    year_built        INTEGER,
    units             INTEGER,
    asking_price      NUMERIC,
    target_price      NUMERIC,
    down_payment_pct  NUMERIC,
    financing_type    TEXT,
    interest_rate     NUMERIC,
    broker_rent       NUMERIC,
    system_rent       NUMERIC,
    current_occupancy NUMERIC,
    expense_overrides JSONB,
    unit_mix          JSONB,     -- per-unit-type breakdown for MF/condo; null for SFH
    lot_sqft          INTEGER,   -- land parcel area (sqft = building area)
    building_count    INTEGER,   -- number of structures on the parcel
    notes             TEXT,
    source_type       TEXT NOT NULL DEFAULT 'manual',
    -- ADR-105: OM data model
    om_data           JSONB,     -- All extracted OM content (flexible-first)
    broker_cap_rate   NUMERIC,   -- Typed cap rate from OM (as decimal, e.g. 0.065)
    om_file_path      TEXT,      -- Volume-relative path (preferred)
    om_file_data      BYTEA,     -- Fallback storage if no volume configured
    om_file_name      TEXT,      -- Original filename
    om_file_type      TEXT,      -- MIME type
    -- ADR-106: OM validation workflow
    om_validation_status TEXT NOT NULL DEFAULT 'not_uploaded', -- 'not_uploaded' | 'incomplete' | 'validated'
    om_questions         JSONB,  -- OMQuestion[] generated by Claude
    om_validated_data    JSONB,  -- Merged: om_data + user answers + corrections
    -- ADR-107: property completeness validation
    property_completeness TEXT NOT NULL DEFAULT 'incomplete', -- 'incomplete' | 'sufficient' | 'complete'
    -- ADR-107 Phase 2: commercial property fields (mixed_use, warehouse, retail, industrial, nnn)
    lease_type              TEXT,     -- 'nnn' | 'modified_gross' | 'gross' | 'full_service'
    tenant_count            INTEGER,
    anchor_tenant           TEXT,
    weighted_avg_lease_yrs  NUMERIC,  -- WALR in years
    commercial_sqft         INTEGER,  -- for mixed_use: residential=sqft, commercial=commercial_sqft
    commercial_mix          JSONB,    -- [{ tenantName, sqft, monthlyRent, leaseType, leaseExpiry }]
    -- ADR-108: physical detail columns from type-aware OM extraction
    year_renovated          INTEGER,
    stories                 INTEGER,
    zoning                  TEXT,
    construction            TEXT,
    parking_spaces          INTEGER,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
